import type { GrammarPage } from "../types";
const p=(id:string,slug:string,titleUk:string,titlePt:string,titleEn:string,summary:string,intro:string,teachingNote:string,examples:GrammarPage["examples"],related:string[]=[]):GrammarPage=>({id,slug,category:"adjectives",titleUk,titlePt,titleEn,summary,aliases:[titleUk,slug] ,related,intro:teachingNote ? `${i}\n\n${teachingNote}` : i,examples,markers:[],mistakes:[]});
export const pages:GrammarPage[]=[
p("adjective-agreement","agreement","Узгодження прикметників","Concordância dos adjetivos","Adjective agreement","Рід і число прикметника.","Атрибутивний прикметник узгоджується з іменником у роді та числі. Для прикметників на -e або приголосний форма може не змінювати рід, але число зазвичай маркується.","Аналізуйте форму прикметника разом із головним іменником.",[{pt:"casa bonita",uk:"гарний будинок"},{pt:"casas bonitas",uk:"гарні будинки"},{pt:"homens inteligentes",uk:"розумні чоловіки"}],["noun-gender","noun-number","agreement-na"]),
p("adjective-position","position","Позиція прикметника","Posição do adjetivo","Adjective position","До- та постпозиція прикметника.","Багато прикметників нейтрально стоять після іменника, але позиція перед іменником теж можлива й може змінювати фокус, інтерпретацію або стиль.","Не перекладайте український порядок механічно.",[{pt:"uma casa grande",uk:"великий будинок"},{pt:"um grande problema",uk:"велика проблема"}],["adjective-meaning","word-order"]),
p("adjective-meaning","position-meaning","Позиція і значення прикметника","Posição e significado","Adjective position and meaning","Лексичні та семантичні відмінності позиції.","Для частини прикметників позиція змінює значення: um grande homem може означати «видатний чоловік», тоді як um homem grande — чоловік великого розміру.","Такі пари краще вчити лексично з контекстом.",[{pt:"um grande amigo",uk:"добрий / близький друг"},{pt:"um amigo grande",uk:"великий на зріст друг"}],["adjective-position","aspect-overview"]),
p("comparatives","comparatives","Ступені порівняння","Graus de comparação","Comparatives","Більший, менший, такий самий.","Порівняння будується через mais, menos, tão ... como/quanto та нерегулярні форми melhor, pior, maior, menor.","Відрізняйте порівняльну конструкцію від абсолютного суперлатива.",[{pt:"mais alto do que eu",uk:"вищий за мене"},{pt:"tão importante como antes",uk:"такий самий важливий, як раніше"},{pt:"melhor do que ontem",uk:"кращий, ніж учора"}],["superlatives","absolute-superlative"]),
p("superlatives","superlatives","Відносний суперлатив","Superlativo relativo","Relative superlative","Найвищий ступінь у межах групи.","Модель o/a mais ... de порівнює один референт із групою: a cidade mais antiga do país. Артикль є частиною типової конструкції.","Перекладайте значення групового порівняння, а не окреме слово mais.",[{pt:"a mais antiga da região",uk:"найстаріша в регіоні"},{pt:"o menos caro da loja",uk:"найдешевший у магазині"}],["comparatives","articles-definite"]),
p("absolute-superlative","absolute-superlative","Абсолютний суперлатив","Superlativo absoluto","Absolute superlative","Дуже високий ступінь без порівняльної групи.","Абсолютний суперлатив може будуватися через muito або суфіксальні форми на -íssimo. Друга модель має сильні орфографічні та лексичні особливості.","Форма -íssimo не означає автоматично най- у значенні групового порівняння.",[{pt:"muito importante",uk:"дуже важливий"},{pt:"importantíssimo",uk:"надзвичайно важливий"}],["superlatives","word-formation-affixes"]),
p("irregular-adjectives","irregular","Нерегулярні прикметники","Adjetivos irregulares","Irregular adjectives","Нерегулярні форми ступенів порівняння.","bom → melhor, mau → pior, grande → maior, pequeno → menor мають окремі порівняльні форми. Вони не є просто суфіксальними варіантами.","Вивчайте їх разом із моделлю порівняння.",[{pt:"Este livro é melhor.",uk:"Ця книжка краща."},{pt:"A cidade é maior.",uk:"Місто більше."}],["comparatives","adjective-meaning"])
];