import type { GrammarPage } from "../types";
import { ex, mistake, page } from "../helpers";

const GULBENKIAN_I = "https://gulbenkian.pt/publications/gramatica-do-portugues-vol-i/";
const GULBENKIAN_II = "https://gulbenkian.pt/publications/gramatica-do-portugues-vol-ii/";
const GULBENKIAN_III = "https://gulbenkian.pt/publications/gramatica-do-portugues-vol-iii/";
const CAMOES_PLE = "https://www.instituto-camoes.pt/activity/centro-virtual/referencial-camoes-ple";

export const pages: GrammarPage[] = [
  page({
    id: "sentence-type-vs-intonation",
    slug: "sentence-type-vs-intonation",
    category: "syntax",
    titleUk: "Тип речення та інтонація",
    titlePt: "Tipo de frase e entoação",
    titleEn: "Sentence type and intonation",
    summary: "Як граматичний тип речення взаємодіє з інтонацією, фокусом і контекстом.",
    aliases: ["тип речення та інтонація", "sentence type and intonation", "tipo de frase", "entoação"],
    related: ["sentence-type-vs-speech-act", "sentence-type-vs-punctuation", "intonation", "questions"],
    status: "review",
    origin: "handwritten",
    depth: "high",
    ukrainianContrast: "high",
    intro: "Питальність, ствердження, спонукання та окличність не зводяться до одного контуру інтонації. У португальській інтонація допомагає слухачеві визначити комунікативну інтерпретацію, але граматична структура, лексика й контекст також мають значення. Одна й та сама синтаксична форма може отримувати різний прагматичний ефект залежно від просодії.",
    definition: "Тип речення — граматична характеристика конструкції, тоді як інтонація — просодична організація висловлення. Вони взаємодіють, але не є взаємозамінними.",
    formulas: [
      { label: "Полярне питання", pattern: "oração declarativa + contexto/entoação interrogativa → pergunta", note: "Питальність може бути виражена без англійського do-support; інтонація часто є важливою частиною усної інтерпретації." },
      { label: "Ствердження", pattern: "oração declarativa + entoação declarativa → asserção", note: "Контекст може перетворити формально декларативну форму на прохання, здивування або інший мовленнєвий акт." },
    ],
    uses: [
      { title: "Питання без зміни базового порядку", body: "У розмовній португальській питальна інтерпретація часто підтримується інтонацією.", examples: [ex("Tu vais amanhã?", "Ти йдеш завтра?")] },
      { title: "Контрастивний фокус", body: "Просодія може виділити один компонент, змінюючи інформаційну структуру без обов'язкової зміни граматичного типу.", examples: [ex("ELE comprou o livro.", "Саме ВІН купив книжку.")] },
      { title: "Контекст", body: "Форма речення не передбачає автоматично одного мовленнєвого акту.", examples: [ex("Pode fechar a janela?", "Можете зачинити вікно? — формально питання, прагматично прохання.")] },
    ],
    examples: [
      ex("Tu vais amanhã?", "Ти йдеш завтра?", { purpose: "comprehension" }),
      ex("ELE comprou o livro.", "Саме ВІН купив книжку.", { purpose: "contrast" }),
      ex("Pode fechar a janela?", "Можете зачинити вікно?", { purpose: "production" }),
    ],
    mistakes: [
      mistake("вважати, що питальність завжди потребує окремого порядку слів", "розрізняти синтаксичну структуру, інтонацію та прагматичний контекст", "Португальська не копіює англійську модель інверсії допоміжного дієслова."),
    ],
    ukrainian: "Українська також використовує інтонацію для питань, фокусу та ставлення мовця. Це корисна аналогія, але порівнюйте конкретні просодичні й синтаксичні моделі, а не лише розділові знаки.",
    regional: "Інтонаційні реалізації можуть відрізнятися між PT-BR, PT-PT та іншими різновидами; без аудіоконтексту не варто перетворювати один опис контуру на універсальне правило.",
    brPt: "У PT-BR і PT-PT спільне граматичне ядро не означає тотожності всіх просодичних реалізацій. Для слухового аналізу різновид і конкретна ситуація мають значення.",
    sources: [
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. III", url: GULBENKIAN_III },
      { label: "Camões — Referencial Camões PLE", url: CAMOES_PLE },
    ],
  }),
  page({
    id: "sentence-type-vs-punctuation",
    slug: "sentence-type-vs-punctuation",
    category: "syntax",
    titleUk: "Тип речення та пунктуація",
    titlePt: "Tipo de frase e pontuação",
    titleEn: "Sentence type and punctuation",
    summary: "Чому крапка, знак питання й знак оклику не є повною граматичною класифікацією речення.",
    aliases: ["тип речення та пунктуація", "sentence type and punctuation", "pontuação", "tipo de frase"],
    related: ["sentence-type-vs-speech-act", "sentence-type-vs-intonation", "punctuation", "questions"],
    status: "review",
    origin: "handwritten",
    depth: "high",
    ukrainianContrast: "high",
    intro: "Пунктуація кодує частину письмової організації висловлення, але не є прямою копією синтаксичного дерева. Знак питання зазвичай сигналізує питальну інтерпретацію, однак декларативна структура може використовуватися для питання, а окличний знак може супроводжувати різні типи речень. Тому під час навчання треба розділяти граматичний тип, письмову пунктуацію та мовленнєвий акт.",
    definition: "Пунктуація — графічна система організації письмового тексту; тип речення — граматична характеристика; мовленнєвий акт — комунікативна функція висловлення.",
    uses: [
      { title: "Питальний знак", body: "Знак питання є сильним письмовим сигналом, але він не пояснює саму синтаксичну структуру.", examples: [ex("Quando chegas?", "Коли ти приїдеш?")] },
      { title: "Декларативна форма", body: "У контексті декларативне речення може передавати питання або запит на підтвердження.", examples: [ex("Tu vais amanhã.", "Ти йдеш завтра. — у відповідному контексті це може бути перепитування, хоча форма декларативна.")] },
      { title: "Окличність", body: "Окличний знак може посилювати емоційний ефект, не створюючи окремої морфологічної категорії.", examples: [ex("Que surpresa!", "Яка несподіванка!")] },
    ],
    examples: [
      ex("Quando chegas?", "Коли ти приїдеш?", { purpose: "comprehension" }),
      ex("Tu vais amanhã.", "Ти йдеш завтра.", { purpose: "contrast" }),
      ex("Que surpresa!", "Яка несподіванка!", { purpose: "production" }),
    ],
    mistakes: [
      mistake("ототожнювати знак питання з окремою граматичною формою питання", "аналізувати синтаксис, просодію/контекст і пунктуацію окремо", "Письмовий знак допомагає читачеві, але не замінює граматичного аналізу."),
    ],
    ukrainian: "Українська теж розрізняє синтаксичну структуру та пунктуацію, тому пряме зіставлення можливе на функціональному рівні. Проте конкретні правила ком і графічного оформлення треба вивчати окремо.",
    regional: "Норми пунктуації можуть мати стилістичні відмінності між різновидами португальської. Не переносіть одну редакційну практику на всі португаломовні тексти.",
    sources: [
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. III", url: GULBENKIAN_III },
      { label: "Camões — Referencial Camões PLE", url: CAMOES_PLE },
    ],
  }),
  page({
    id: "illocutionary-force-and-grammatical-form",
    slug: "illocutionary-force-and-grammatical-form",
    category: "pragmatics",
    titleUk: "Іллокутивна сила та граматична форма",
    titlePt: "Força ilocutória e forma gramatical",
    titleEn: "Illocutionary force and grammatical form",
    summary: "Як одна граматична форма може виконувати різні комунікативні дії, а одна дія — різні форми.",
    aliases: ["іллокутивна сила", "illocutionary force", "força ilocutória", "граматична форма і мовленнєвий акт"],
    related: ["sentence-type-vs-speech-act", "speech-acts", "politeness", "register-and-directness"],
    status: "review",
    origin: "handwritten",
    depth: "high",
    ukrainianContrast: "high",
    intro: "Іллокутивна сила відповідає за те, що мовець робить висловленням: стверджує, питає, просить, наказує, радить, обіцяє тощо. Граматична форма дає підказки, але не визначає силу механічно. Особливо важливо це для ввічливих прохань: питальна форма може бути проханням, а декларативна — порадою або попередженням.",
    definition: "Іллокутивна сила — комунікативна функція висловлення як мовленнєвої дії. Вона формується взаємодією граматики, лексики, просодії та контексту.",
    uses: [
      { title: "Питання як прохання", body: "Питальна форма може не вимагати інформації, а спонукати адресата до дії.", examples: [ex("Pode abrir a porta?", "Можете відчинити двері?")] },
      { title: "Декларативна порада", body: "Стверджувальна форма може бути інтерпретована як рекомендація залежно від ситуації.", examples: [ex("Era melhor esperar.", "Краще було б почекати.")] },
      { title: "Імператив і сила", body: "Імператив без додаткового контексту легко сприймається як директива, але лексика й регістр можуть пом'якшити або посилити її.", examples: [ex("Entre, por favor.", "Заходьте, будь ласка.")] },
    ],
    examples: [
      ex("Pode abrir a porta?", "Можете відчинити двері?", { purpose: "production" }),
      ex("Era melhor esperar.", "Краще було б почекати.", { purpose: "comprehension" }),
      ex("Entre, por favor.", "Заходьте, будь ласка.", { purpose: "contrast" }),
    ],
    mistakes: [
      mistake("визначати мовленнєвий акт лише за назвою типу речення", "додавати до синтаксичного аналізу адресата, ситуацію, інтонацію та регістр", "Питальне речення може бути проханням, а декларативне — попередженням або порадою."),
    ],
    ukrainian: "Українська має подібну прагматичну взаємодію форми й функції. Корисно порівнювати конкретні ситуації, але не припускати повної тотожності ввічливих формул.",
    regional: "Ступінь прямоти й вибір формули прохання залежать від соціального контексту, регістру та різновиду португальської. Частотність окремої формули не є універсальним правилом.",
    brPt: "PT-BR і PT-PT можуть відрізнятися у виборі займенників звертання, модальних форм і клітичних моделей. Іллокутивна функція при цьому може залишатися тією самою.",
    sources: [
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. III", url: GULBENKIAN_III },
      { label: "Camões — Referencial Camões PLE", url: CAMOES_PLE },
    ],
  }),
  page({
    id: "grammaticalisation-of-discourse-functions",
    slug: "grammaticalisation-of-discourse-functions",
    category: "discourse",
    titleUk: "Граматикалізація дискурсивних функцій",
    titlePt: "Gramaticalização de funções discursivas",
    titleEn: "Grammaticalisation of discourse functions",
    summary: "Як дискурсивні значення можуть закріплюватися в граматичних моделях і конструкціях.",
    aliases: ["граматикалізація", "grammaticalisation", "funções discursivas", "дискурсивні функції"],
    related: ["discourse-overview", "discourse-markers", "modal-particles", "pragmatics-overview"],
    status: "review",
    origin: "handwritten",
    depth: "high",
    ukrainianContrast: "high",
    intro: "Граматикалізація — історичний процес, у якому лексичні або менш граматикалізовані елементи можуть розвивати більш абстрактні граматичні функції. Для студента важливо не плутати цей діахронічний процес із синхронним правилом: те, що форма історично походить від повнозначного слова, не означає, що сучасний носій аналізує її саме так.",
    definition: "Граматикалізація — процес мовної зміни, за якого певна форма або конструкція набуває більш граматикалізованих функцій. Дискурсивні функції можуть бути одним із напрямів такого розвитку.",
    uses: [
      { title: "Конструкція як цілісна модель", body: "Сучасна граматика може закріпити значення, яке не виводиться простим складанням значень компонентів.", examples: [ex("Acabei de chegar.", "Я щойно прийшов/прийшла.")] },
      { title: "Дискурсивний елемент", body: "Елемент може організовувати текст або позицію мовця, а не лише описувати предметну ситуацію.", examples: [ex("Afinal, o que aconteceu?", "То зрештою, що сталося?")] },
      { title: "Синхронія проти історії", body: "Етимологія пояснює походження, але не замінює сучасного синтаксичного опису.", examples: [ex("Enfim, continuemos.", "Зрештою, продовжімо.")] },
    ],
    examples: [
      ex("Acabei de chegar.", "Я щойно прийшов/прийшла.", { purpose: "comprehension" }),
      ex("Afinal, o que aconteceu?", "То зрештою, що сталося?", { purpose: "production" }),
      ex("Enfim, continuemos.", "Зрештою, продовжімо.", { purpose: "contrast" }),
    ],
    mistakes: [
      mistake("вважати історичне походження конструкції її сучасним синтаксичним аналізом", "розділяти діахронічну граматикалізацію та синхронну функцію", "Історія форми корисна для пояснення, але студенту потрібне сучасне правило її вживання."),
    ],
    ukrainian: "Українська також має граматикалізовані конструкції та дискурсивні елементи. Порівнюйте процеси обережно: спільна історична тенденція не означає однакового результату в двох мовах.",
    regional: "Граматикалізація — діахронічний процес, тому сучасні різновиди португальської можуть демонструвати різний ступінь закріплення окремих моделей. Це не слід перетворювати на просту карту «країна → правило».",
    sources: [
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. II", url: GULBENKIAN_II },
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. III", url: GULBENKIAN_III },
    ],
  }),
  page({
    id: "null-and-expletive-subjects",
    slug: "null-expletive",
    category: "syntax",
    titleUk: "Нульові та формальні підмети",
    titlePt: "Sujeitos nulos e expletivos",
    titleEn: "Null and expletive subjects",
    summary: "Як розрізняти опущений підмет, формальний підмет і конструкції без лексично вираженого підмета.",
    aliases: ["нульовий підмет", "формальний підмет", "null subject", "expletive subject", "sujeito nulo"],
    related: ["null-subject", "definite-null-subjects", "indefinite-null-subjects", "expletive-null-subjects"],
    status: "review",
    origin: "handwritten",
    depth: "high",
    ukrainianContrast: "high",
    intro: "Португальська часто дозволяє не виражати лексичний підмет, але це не означає, що в кожному такому реченні «підмету немає». Потрібно розрізняти нульовий підмет, який можна інтерпретувати з граматичних або дискурсивних ознак, і expletive/формальний підмет у конструкціях, де семантичний учасник не потрібен або не виражений як звичайний референт.",
    definition: "Нульовий підмет — невиражений синтаксичний суб'єкт, який може мати референтну або неконкретну інтерпретацію. Expletive subject — формальний елемент без звичайного лексичного референта; португальська часто реалізує такі конструкції без окремого займенника.",
    uses: [
      { title: "Відновлюваний підмет", body: "Закінчення дієслова та контекст можуть дозволити зрозуміти, хто виконує дію.", examples: [ex("Cheguei cedo.", "Я прийшов/прийшла рано.")] },
      { title: "Погодний предикат", body: "У безособових погодних конструкціях не потрібно вставляти португальський еквівалент англійського it.", examples: [ex("Está a chover.", "Дощить / Іде дощ.")] },
      { title: "Неозначений діяч", body: "Невиражений суб'єкт може мати загальну або неідентифіковану інтерпретацію.", examples: [ex("Bateram à porta.", "У двері постукали.")] },
    ],
    examples: [
      ex("Cheguei cedo.", "Я прийшов/прийшла рано.", { purpose: "production" }),
      ex("Está a chover.", "Дощить / Іде дощ.", { purpose: "comprehension", variety: "PT" }),
      ex("Bateram à porta.", "У двері постукали.", { purpose: "contrast" }),
    ],
    mistakes: [
      mistake("додавати португальське займенникове «воно» до кожного безособового речення за аналогією з англійською", "спочатку визначити, чи португальська конструкція має референтний або expletive суб'єкт", "Португальська й англійська по-різному реалізують формальний суб'єкт."),
    ],
    ukrainian: "Українська також часто опускає підмет і має безособові конструкції, тому аналогія корисна. Однак португальське дієслівне узгодження та набір конструкцій треба аналізувати самостійно.",
    regional: "Стратегії вираження суб'єкта можуть відрізнятися між PT-BR та PT-PT, особливо через зміни системи займенників і частотність явних підметів. Це не скасовує спільної null-subject спадщини португальської.",
    brPt: "PT-BR у багатьох контекстах частіше виражає займенниковий підмет, ніж традиційний опис європейської португальської; водночас обидва різновиди мають широкий набір конструкцій із невираженим суб'єктом. Не робіть із частотності абсолютного правила.",
    sources: [
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. II", url: GULBENKIAN_II },
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. III", url: GULBENKIAN_III },
    ],
  }),
  page({
    id: "subject-object-order",
    slug: "subject-object-order",
    category: "syntax",
    titleUk: "Порядок підмета й додатка",
    titlePt: "Ordem do sujeito e do objeto",
    titleEn: "Subject-object order",
    summary: "Як базовий порядок слів взаємодіє з фокусом, топіком, типом предиката та інформаційною структурою.",
    aliases: ["порядок підмета й додатка", "subject-object order", "ordem sujeito objeto", "SVO"],
    related: ["word-order", "subject-placement", "topicalization", "information-structure"],
    status: "review",
    origin: "handwritten",
    depth: "high",
    ukrainianContrast: "high",
    intro: "Португальська має типовий порядок SVO, але це не означає, що будь-яка перестановка компонентів неможлива або що будь-яка нестандартна позиція є помилкою. Порядок може змінюватися через інформаційну структуру, дискурс, тип предиката та синтаксичну конструкцію. Для україномовного студента особливо небезпечно переносити відносно вільні українські перестановки без урахування фокусу.",
    definition: "Порядок SVO — типова нейтральна модель для багатьох транзитивних речень: Subject + Verb + Object. Відхилення від неї мають синтаксичні або інформаційно-прагматичні мотиви.",
    formulas: [
      { label: "Нейтральна транзитивна модель", pattern: "S + V + O", note: "Це базова відправна точка, а не правило про неможливість інших порядків." },
      { label: "Топік", pattern: "Topic + clause", note: "Винесений компонент може бути тематичним і мати окрему інформаційну функцію." },
    ],
    uses: [
      { title: "Нейтральний порядок", body: "Підмет перед дієсловом і прямий додаток після нього є типовою моделлю.", examples: [ex("A Maria comprou o livro.", "Марія купила книжку.")] },
      { title: "Топікалізація", body: "Об'єкт може бути винесений уперед для тематичного або контрастивного ефекту.", examples: [ex("Esse livro, a Maria comprou ontem.", "Цю книжку Марія купила вчора.")] },
      { title: "Фокус", body: "Наголос і порядок взаємодіють: незвична позиція часто несе інформаційну мотивацію.", examples: [ex("Foi a Maria que comprou o livro.", "Саме Марія купила книжку.")] },
    ],
    examples: [
      ex("A Maria comprou o livro.", "Марія купила книжку.", { purpose: "comprehension" }),
      ex("Esse livro, a Maria comprou ontem.", "Цю книжку Марія купила вчора.", { purpose: "contrast" }),
      ex("Foi a Maria que comprou o livro.", "Саме Марія купила книжку.", { purpose: "production" }),
    ],
    mistakes: [
      mistake("вважати SVO єдиним можливим порядком або, навпаки, переносити українську свободу перестановок", "визначати нейтральний порядок, потім шукати інформаційну або синтаксичну причину відхилення", "Позиція компонента часто є частиною інформаційної структури."),
    ],
    ukrainian: "Українська допускає більше перестановок завдяки відмінковій морфології. У португальській порядок слів частіше допомагає сигналізувати синтаксичні ролі та інформаційну структуру.",
    regional: "Порядок слів і частотність постпозиційних/передпозиційних підметів можуть відрізнятися між різновидами. Описуйте конкретну конструкцію, а не оголошуйте одну послідовність універсальною.",
    brPt: "PT-BR має власні дискурсивні стратегії, зокрема ширше використання явного підмета в певних контекстах; це не означає, що SVO перестає бути базовою моделлю.",
    sources: [
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. II", url: GULBENKIAN_II },
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. III", url: GULBENKIAN_III },
    ],
  }),
  page({
    id: "subordination-and-coordination",
    slug: "subordination-coordination",
    category: "syntax",
    titleUk: "Сурядність і підрядність",
    titlePt: "Coordenação e subordinação",
    titleEn: "Coordination and subordination",
    summary: "Як розрізняти незалежні/координовані частини та залежні підрядні конструкції.",
    aliases: ["сурядність і підрядність", "coordination and subordination", "coordenação", "subordinação"],
    related: ["coordination", "subordinate", "conjunctions-overview", "subordinate-clause-punctuation"],
    status: "review",
    origin: "handwritten",
    depth: "high",
    ukrainianContrast: "high",
    intro: "Сурядність поєднує компоненти одного синтаксичного рівня, тоді як підрядність встановлює залежність однієї частини від іншої. Важливо не визначати відношення лише за українським перекладом сполучника: однакова семантична функція може реалізовуватися різними синтаксичними моделями.",
    definition: "Координація — синтаксичне поєднання рівноправних компонентів; субординація — включення залежної конструкції до структури іншої.",
    uses: [
      { title: "Сурядність", body: "Дві пропозиції можуть бути пов'язані como, e, mas та іншими координаторами.", examples: [ex("Cheguei e sentei-me.", "Я прийшов/прийшла і сів/сіла.")] },
      { title: "Підрядність", body: "Залежна частина виконує певну синтаксичну функцію щодо головної.", examples: [ex("Quero que venhas.", "Я хочу, щоб ти прийшов/прийшла.")] },
      { title: "Семантичне відношення", body: "Причина, умова, час або мета не визначають самі по собі синтаксичний статус; аналізуйте структуру.", examples: [ex("Quando chegares, liga-me.", "Коли прийдеш, зателефонуй мені.")] },
    ],
    examples: [
      ex("Cheguei e sentei-me.", "Я прийшов/прийшла і сів/сіла.", { purpose: "comprehension" }),
      ex("Quero que venhas.", "Я хочу, щоб ти прийшов/прийшла.", { purpose: "production" }),
      ex("Quando chegares, liga-me.", "Коли прийдеш, зателефонуй мені.", { purpose: "contrast" }),
    ],
    mistakes: [
      mistake("вважати всі сполучники лише маркерами значення «і/але/коли» без синтаксичної функції", "визначати, який компонент є залежним і яку функцію виконує частина", "Семантичний переклад не замінює синтаксичного аналізу."),
    ],
    ukrainian: "Українська має ті самі базові поняття координації та субординації, тому термінологічна аналогія корисна. Розбіжності з'являються в конкретному керуванні, інфінітивних моделях і виборі modo.",
    regional: "Основний поділ на координацію та субординацію спільний для португальської, але реалізація окремих конструкцій і переваги стилю можуть відрізнятися між різновидами.",
    sources: [
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. II", url: GULBENKIAN_II },
      { label: "Camões — Referencial Camões PLE", url: CAMOES_PLE },
    ],
  }),
  page({
    id: "reduced-clauses",
    slug: "reduced",
    category: "subordinate",
    titleUk: "Зредуковані підрядні конструкції",
    titlePt: "Orações reduzidas",
    titleEn: "Reduced clauses",
    summary: "Як нефінітні конструкції можуть виконувати функції, подібні до фінітних підрядних.",
    aliases: ["зредуковані підрядні", "reduced clauses", "orações reduzidas", "нефінітні підрядні"],
    related: ["infinitival-reduced-clauses", "gerundial-reduced-clauses", "participial-reduced-clauses", "finite-vs-nonfinite-subordination"],
    status: "review",
    origin: "handwritten",
    depth: "high",
    ukrainianContrast: "high",
    intro: "У португальській підрядна конструкція може бути реалізована інфінітивом, герундієм або дієприкметниковою формою замість фінітного дієслова. «Зредукована» не означає «неповна»: така конструкція має власну граматичну структуру, а її суб'єкт, часові та логічні відношення треба відновлювати з форми й контексту.",
    definition: "Зредукована підрядна конструкція — підрядна структура з нефінітним предикативним центром, де частина граматичної інформації виражається не так, як у фінітному реченні.",
    uses: [
      { title: "Інфінітив", body: "Інфінітив може виражати мету, зміст, часову або іншу залежну ситуацію.", examples: [ex("Para estudar, fechou a porta.", "Щоб учитися, він/вона зачинив/зачинила двері.")] },
      { title: "Герундій", body: "Gerúndio може встановлювати часові, причинні, способові та інші відношення залежно від контексту.", examples: [ex("Chegando a casa, ligou-me.", "Прийшовши додому, він/вона мені зателефонував/зателефонувала.")] },
      { title: "Дієприкметникова форма", body: "Participial constructions можуть мати пасивну, результативну або іншу залежну інтерпретацію.", examples: [ex("Terminada a reunião, saímos.", "Коли нарада закінчилася, ми вийшли.")] },
    ],
    examples: [
      ex("Para estudar, fechou a porta.", "Щоб учитися, він/вона зачинив/зачинила двері.", { purpose: "production" }),
      ex("Chegando a casa, ligou-me.", "Прийшовши додому, він/вона мені зателефонував/зателефонувала.", { purpose: "comprehension" }),
      ex("Terminada a reunião, saímos.", "Коли нарада закінчилася, ми вийшли.", { purpose: "contrast" }),
    ],
    mistakes: [
      mistake("вважати нефінітну конструкцію просто «скороченим реченням» без власної синтаксичної структури", "визначити предикативний центр, його суб'єкт та відношення до головної частини", "Зредукція змінює спосіб кодування граматичної інформації, але не скасовує синтаксичні відношення."),
    ],
    ukrainian: "Українська також використовує дієприкметникові й дієприслівникові конструкції, тому є корисна функціональна аналогія. Але португальський інфінітив і герундій мають власний розподіл.",
    regional: "Частотність нефінітних конструкцій і конкретні стилістичні переваги можуть відрізнятися між письмовими та усними різновидами й між національними нормами.",
    sources: [
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. II", url: GULBENKIAN_II },
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. III", url: GULBENKIAN_III },
    ],
  }),
  page({
    id: "infinitival-reduced-clauses",
    slug: "reduced-infinitival",
    category: "subordinate",
    titleUk: "Інфінітивні зредуковані підрядні",
    titlePt: "Orações reduzidas de infinitivo",
    titleEn: "Infinitival reduced clauses",
    summary: "Як інфінітивні конструкції кодують залежну ситуацію та коли суб'єкт може бути виражений окремо.",
    aliases: ["інфінітивні зредуковані", "infinitival clauses", "orações infinitivas", "personal infinitive"],
    related: ["personal-infinitive", "reduced-clauses", "verb-government-infinitive", "complement-clauses-advanced"],
    status: "review",
    origin: "handwritten",
    depth: "high",
    ukrainianContrast: "high",
    intro: "Португальський інфінітив може бути центром залежної конструкції. У частині випадків суб'єкт інфінітива збігається з суб'єктом головного дієслова й не виражається, а в інших його можна або потрібно виразити. Особистий інфінітив є важливою особливістю португальської: його форма може сигналізувати особу й число.",
    definition: "Інфінітивна підрядна конструкція — залежна структура з infinitivo як предикативним центром. Вона може мати нульовий або виражений суб'єкт залежно від конструкції.",
    formulas: [
      { label: "Спільний суб'єкт", pattern: "S₁ + V₁ + infinitivo", note: "Суб'єкт інфінітивної ситуації може бути зрозумілий із головної частини." },
      { label: "Окремий суб'єкт", pattern: "V₁ + [NP + infinitivo]", note: "Особистий інфінітив дозволяє чіткіше виразити суб'єкта залежної ситуації." },
    ],
    uses: [
      { title: "Мета", body: "Інфінітивна конструкція може виражати мету.", examples: [ex("Fui lá para falar com ele.", "Я пішов/пішла туди, щоб поговорити з ним.")] },
      { title: "Зміст дієслова", body: "Багато дієслів керують інфінітивом.", examples: [ex("Quero sair.", "Я хочу піти.")] },
      { title: "Окремий суб'єкт", body: "У певних конструкціях суб'єкт залежного інфінітива виражений явно.", examples: [ex("É importante eles estudarem.", "Важливо, щоб вони вчилися.")] },
    ],
    examples: [
      ex("Fui lá para falar com ele.", "Я пішов/пішла туди, щоб поговорити з ним.", { purpose: "production" }),
      ex("Quero sair.", "Я хочу піти.", { purpose: "comprehension" }),
      ex("É importante eles estudarem.", "Важливо, щоб вони вчилися.", { purpose: "contrast" }),
    ],
    mistakes: [
      mistake("вважати, що будь-який португальський інфінітив має такий самий суб'єкт, як головне дієслово", "перевіряти, чи є окремий суб'єкт і чи потрібен особистий інфінітив", "Суб'єкт інфінітивної ситуації визначається конструкцією, а не лише перекладом."),
    ],
    ukrainian: "Українська часто використовує конструкції з «щоб» або узгоджені форми минулого/теперішнього часу там, де португальська може мати інфінітив. Особистий інфінітив не має прямого українського морфологічного двійника.",
    regional: "Розподіл особистого й неособистого інфінітива залежить від конструкції, стилю та різновиду; не зводьте вибір до одного правила «коротше/довше».",
    brPt: "Особистий інфінітив є частиною спільної португальської системи, хоча конкретна частотність конструкцій і переваги можуть різнитися між PT-BR та PT-PT.",
    sources: [
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. II", url: GULBENKIAN_II },
      { label: "Camões — Referencial Camões PLE", url: CAMOES_PLE },
    ],
  }),
  page({
    id: "gerundial-reduced-clauses",
    slug: "reduced-gerundial",
    category: "subordinate",
    titleUk: "Герундіальні зредуковані підрядні",
    titlePt: "Orações reduzidas de gerúndio",
    titleEn: "Gerundial reduced clauses",
    summary: "Як gerúndio створює нефінітні залежні конструкції та чому їхній зміст залежить від контексту.",
    aliases: ["герундіальні зредуковані", "gerundial clauses", "orações reduzidas de gerúndio", "gerúndio"],
    related: ["reduced-clauses", "gerund", "progressive-br-pt", "finite-vs-nonfinite-subordination"],
    status: "review",
    origin: "handwritten",
    depth: "high",
    ukrainianContrast: "high",
    intro: "Gerúndio не має одного універсального українського перекладу. У залежній конструкції він може виражати одночасність, спосіб, причину, умову або інший зв'язок, який встановлюється контекстом. Для PT-BR і PT-PT також важливо не плутати загальну функцію герундія зі стратегією прогресиву.",
    definition: "Герундіальна зредукована конструкція — нефінітна залежна структура з gerúndio. Її семантичне відношення до головної частини визначається конструкцією та контекстом.",
    uses: [
      { title: "Одночасність", body: "Дві події можуть бути представлені як такі, що відбуваються одночасно.", examples: [ex("Saiu falando ao telefone.", "Він/вона вийшов/вийшла, розмовляючи телефоном.")] },
      { title: "Обставинний зв'язок", body: "Контекст може давати причинне, часове або спосібове читання.", examples: [ex("Estudando mais, pode melhorar.", "Якщо/навчаючись більше, можна покращити результат.")] },
      { title: "Не плутати з прогресивом", body: "Gerúndio може бути частиною прогресивної конструкції, але не кожен герундій є прогресивом.", examples: [ex("Estou estudando.", "Я зараз навчаюся — прогресивна конструкція PT-BR.")] },
    ],
    examples: [
      ex("Saiu falando ao telefone.", "Він/вона вийшов/вийшла, розмовляючи телефоном.", { purpose: "comprehension" }),
      ex("Estudando mais, pode melhorar.", "Якщо/навчаючись більше, можна покращити результат.", { purpose: "contrast" }),
      ex("Estou estudando.", "Я зараз навчаюся.", { purpose: "production", variety: "BR" }),
    ],
    mistakes: [
      mistake("перекладати кожен gerúndio українським «-ючи» без аналізу відношення", "визначати часовий, причинний, спосібовий або інший зв'язок із головною частиною", "Українська форма може передавати функцію, але не встановлює португальську конструкцію автоматично."),
    ],
    ukrainian: "Український дієприслівник дає корисну функціональну аналогію для частини випадків, але не покриває весь розподіл португальського gerúndio.",
    regional: "У PT-BR gerúndio широко входить до прогресивної моделі estar + gerúndio; PT-PT часто використовує estar a + infinitivo. Це не означає, що сам gerúndio існує лише в одній із норм.",
    brPt: "Розрізняйте gerúndio як нефінітну форму та прогресивну конструкцію. У PT-BR модель estar + gerúndio є типовою; у PT-PT широко вживається estar a + infinitivo для тієї самої базової прогресивної функції.",
    sources: [
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. II", url: GULBENKIAN_II },
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. III", url: GULBENKIAN_III },
    ],
  }),
];
