import type { GrammarPage } from "../types";
import { ex, mistake, page } from "../helpers";

const GULBENKIAN_I = "https://gulbenkian.pt/publications/gramatica-do-portugues-vol-i/";
const GULBENKIAN_II = "https://gulbenkian.pt/publications/gramatica-do-portugues-vol-ii/";
const GULBENKIAN_III = "https://gulbenkian.pt/publications/gramatica-do-portugues-vol-iii/";
const CAMOES_PLE = "https://www.instituto-camoes.pt/activity/centro-virtual/referencial-camoes-ple";

export const pages: GrammarPage[] = [
  page({
    id: "adverb-scope",
    slug: "adverb-scope",
    category: "adverbs",
    titleUk: "Область дії прислівника",
    titlePt: "Escopo dos advérbios",
    titleEn: "Adverb scope",
    summary: "Як визначати, до чого саме належить прислівник: до дієслова, групи слів чи всього висловлення.",
    aliases: ["область дії прислівника", "adverb scope", "escopo dos advérbios", "escopo adverbial"],
    related: ["adverb-position", "scope-and-reference", "semantic-ambiguity", "adverbs-degree"],
    status: "review",
    origin: "handwritten",
    depth: "high",
    ukrainianContrast: "high",
    intro: "Одна з головних причин неоднозначності прислівників — їхня область дії. Só, também, quase, provavelmente та інші форми можуть стосуватися різних компонентів або всього висловлення. Тому правильний аналіз не закінчується перекладом прислівника: треба встановити, який компонент він модифікує або який зміст коментує.",
    definition: "Область дії прислівника — компонент, група або рівень висловлення, на який поширюється його семантичний чи прагматичний вплив.",
    formulas: [
      { label: "Локальна область дії", pattern: "ADV + constituent → ADV модифікує constituent", note: "Позиція є важливою підказкою, але не є єдиним критерієм інтерпретації." },
      { label: "Широка область дії", pattern: "ADV + clause → ADV коментує всю пропозицію", note: "Особливо характерно для епістемічних та оцінних прислівників." },
    ],
    uses: [
      { title: "Обмеження іменної групи", body: "Só може обмежувати конкретний компонент, а не всю подію.", examples: [ex("Só a Ana veio.", "Прийшла лише Ана.")] },
      { title: "Додавання", body: "Também може приєднувати новий факт до вже активного контексту.", examples: [ex("A Ana também veio.", "Ана теж прийшла.")] },
      { title: "Оцінка пропозиції", body: "Епістемічний прислівник може мати широку область дії.", examples: [ex("Provavelmente, a Ana vem amanhã.", "Імовірно, Ана прийде завтра.")] },
    ],
    examples: [
      ex("Só a Ana veio.", "Прийшла лише Ана.", { purpose: "contrast", function: "Обмеження референта" }),
      ex("A Ana só comprou o livro.", "Ана купила лише книжку.", { purpose: "contrast", function: "Обмеження об'єкта" }),
      ex("Provavelmente, a Ana vem amanhã.", "Імовірно, Ана прийде завтра.", { purpose: "comprehension", function: "Широка епістемічна область дії" }),
    ],
    mistakes: [
      mistake("вважати, що переклад автоматично показує область дії прислівника", "перефразувати речення так, щоб було видно, що саме обмежується або оцінюється", "Одна українська конструкція може приховувати структурну неоднозначність португальського речення."),
    ],
    ukrainian: "Українська також має прислівники з різною областю дії — зокрема «лише», «теж», «майже», «ймовірно». Це корисна аналогія, але аналізуйте не тільки переклад, а й компонент, до якого належить прислівник.",
    regional: "Область дії взаємодіє з інтонацією та інформаційною структурою, особливо в усному мовленні. Письмова позиція часто допомагає, але не завжди однозначно визначає інтерпретацію.",
    sources: [
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. II", url: GULBENKIAN_II },
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. III", url: GULBENKIAN_III },
    ],
  }),
  page({
    id: "sentence-adverbs",
    slug: "sentence-adverbs",
    category: "adverbs",
    titleUk: "Прислівники всього речення",
    titlePt: "Advérbios de frase",
    titleEn: "Sentence adverbs",
    summary: "Прислівники та прислівникові елементи, що коментують пропозицію або ставлення мовця до неї.",
    aliases: ["прислівники речення", "sentence adverbs", "advérbios de frase"],
    related: ["adverbs-overview", "epistemic-adverbs", "discourse-markers", "adverb-position"],
    status: "review",
    origin: "handwritten",
    depth: "high",
    ukrainianContrast: "high",
    intro: "Не всі прислівники описують спосіб виконання дії. Частина з них коментує все повідомлення: виражає оцінку, ступінь упевненості, ставлення мовця або дискурсивний перехід. Такі елементи треба відрізняти від звичайних обставинних прислівників, навіть якщо формально вони належать до тієї самої частини мови.",
    definition: "Прислівник речення — прислівниковий елемент, чия семантична або прагматична область дії охоплює пропозицію чи ставлення мовця до неї.",
    uses: [
      { title: "Епістемічна оцінка", body: "Прислівник оцінює ймовірність істинності висловлення.", examples: [ex("Provavelmente, ele já chegou.", "Імовірно, він уже прийшов.")] },
      { title: "Оцінка ситуації", body: "Оціночний прислівник виражає ставлення мовця до описуваної ситуації.", examples: [ex("Infelizmente, não podemos ficar.", "На жаль, ми не можемо залишитися.")] },
      { title: "Дискурсивна організація", body: "Деякі елементи на периферії речення організовують зв'язок висловлень.", examples: [ex("Enfim, vamos continuar.", "Зрештою, продовжімо.")] },
    ],
    examples: [
      ex("Provavelmente, ele já chegou.", "Імовірно, він уже прийшов.", { purpose: "comprehension" }),
      ex("Infelizmente, não podemos ficar.", "На жаль, ми не можемо залишитися.", { purpose: "production" }),
      ex("Enfim, vamos continuar.", "Зрештою, продовжімо.", { purpose: "contrast" }),
    ],
    mistakes: [
      mistake("вважати всі прислівники однаковими обставинами способу", "визначати, чи прислівник описує подію, чи коментує всю пропозицію", "Переклад може бути природним, але не показувати синтаксичну та прагматичну роль елемента."),
    ],
    ukrainian: "Українська має подібну відмінність між обставинними прислівниками та словами або сполуками, що коментують усе повідомлення. Це позитивна аналогія, але португальські класи та позиційні моделі не слід ототожнювати один до одного.",
    regional: "Межа між прислівником речення, дискурсивним маркером і часткою може залежати від конкретної лексеми та контексту. Не всі елементи на периферії речення мають однаковий синтаксичний статус.",
    sources: [
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. II", url: GULBENKIAN_II },
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. III", url: GULBENKIAN_III },
      { label: "Camões — Referencial Camões PLE", url: CAMOES_PLE },
    ],
  }),
  page({
    id: "epistemic-adverbs",
    slug: "epistemic-adverbs",
    category: "adverbs",
    titleUk: "Епістемічні прислівники",
    titlePt: "Advérbios epistémicos",
    titleEn: "Epistemic adverbs",
    summary: "Як прислівники виражають оцінку ймовірності, впевненості та ставлення до істинності висловлення.",
    aliases: ["епістемічні прислівники", "epistemic adverbs", "advérbios epistémicos"],
    related: ["sentence-adverbs", "modality-overview", "adverb-scope", "modal-particles"],
    status: "review",
    origin: "handwritten",
    depth: "high",
    ukrainianContrast: "high",
    intro: "Епістемічні прислівники повідомляють не стільки про саму подію, скільки про оцінку мовця щодо її істинності. Provavelmente, certamente, possivelmente та talvez можуть по-різному організовувати ступінь упевненості. Важливо також не змішувати прислівникову модальність із вибором modo verbal: прислівник може взаємодіяти з indicativo або conjuntivo, але не замінює собою всю систему модальності.",
    definition: "Епістемічний прислівник — прислівниковий засіб, що кодує або сигналізує оцінку ймовірності, впевненості чи іншого епістемічного ставлення до пропозиції.",
    uses: [
      { title: "Висока впевненість", body: "Certamente подає пропозицію як таку, яку мовець оцінює як певну або дуже ймовірну.", examples: [ex("Certamente, ele sabe a resposta.", "Безперечно, він знає відповідь.")] },
      { title: "Імовірність", body: "Provavelmente зменшує категоричність твердження й маркує високу, але не абсолютну впевненість.", examples: [ex("Provavelmente, ela chega amanhã.", "Імовірно, вона приїде завтра.")] },
      { title: "Можливість", body: "Talvez може вводити припущення та часто взаємодіє з conjuntivo.", examples: [ex("Talvez ele venha amanhã.", "Можливо, він прийде завтра.")] },
    ],
    examples: [
      ex("Certamente, ele sabe a resposta.", "Безперечно, він знає відповідь.", { purpose: "comprehension" }),
      ex("Provavelmente, ela chega amanhã.", "Імовірно, вона приїде завтра.", { purpose: "production" }),
      ex("Talvez ele venha amanhã.", "Можливо, він прийде завтра.", { purpose: "contrast" }),
    ],
    mistakes: [
      mistake("вважати епістемічний прислівник простим синонімом модального дієслова", "визначати, чи модальність виражена прислівником, дієсловом, способом або їхньою комбінацією", "Українське «можливо» може відповідати різним португальським конструкціям залежно від синтаксису й комунікативної мети."),
    ],
    ukrainian: "Українська має функціональні відповідники «ймовірно», «можливо», «безперечно», «напевно». Це дає добру семантичну опору, але не встановлює автоматичної відповідності між конкретним українським словом і португальською конструкцією.",
    regional: "Частотність та позиційні переваги окремих епістемічних прислівників залежать від регістру та контексту. Частотні твердження тут не варто робити без корпусної перевірки.",
    sources: [
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. II", url: GULBENKIAN_II },
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. III", url: GULBENKIAN_III },
      { label: "Camões — Referencial Camões PLE", url: CAMOES_PLE },
    ],
  }),
  page({
    id: "connective-adverbs",
    slug: "connective-adverbs",
    category: "adverbs",
    titleUk: "Зв'язкові прислівники",
    titlePt: "Advérbios conectivos",
    titleEn: "Connective adverbs",
    summary: "Прислівникові елементи, що організовують логічний і дискурсивний зв'язок між висловленнями.",
    aliases: ["зв'язкові прислівники", "connective adverbs", "advérbios conectivos"],
    related: ["adverbs-overview", "discourse-markers", "coordinating", "subordinating"],
    status: "review",
    origin: "handwritten",
    depth: "high",
    ukrainianContrast: "high",
    intro: "Portanto, contudo, além disso та подібні елементи можуть сигналізувати наслідок, протиставлення або додавання. Їх легко назвати «сполучниками» за українським перекладом, але переклад не визначає синтаксичний статус. Для довідника важливо розрізняти власне сполучник, прислівниковий зв'язковий елемент і дискурсивний маркер.",
    definition: "Зв'язковий прислівник — прислівниковий або прислівниково-подібний елемент, який організовує логічний чи дискурсивний зв'язок між частинами тексту.",
    uses: [
      { title: "Наслідок або висновок", body: "Portanto може сигналізувати висновок або наслідок.", examples: [ex("Estava cansado; portanto, foi para casa.", "Він був утомлений; тому пішов додому.")] },
      { title: "Протиставлення", body: "Contudo вводить контраст із попереднім висловленням.", examples: [ex("Queria ir; contudo, fiquei em casa.", "Я хотів/хотіла піти, проте залишився/залишилася вдома.")] },
      { title: "Додавання", body: "Além disso додає новий аргумент або факт.", examples: [ex("É barato e, além disso, funciona bem.", "Це дешево й, крім того, добре працює.")] },
    ],
    examples: [
      ex("Estava cansado; portanto, foi para casa.", "Він був утомлений; тому пішов додому.", { purpose: "comprehension" }),
      ex("Queria ir; contudo, fiquei em casa.", "Я хотів/хотіла піти, проте залишився/залишилася вдома.", { purpose: "production" }),
      ex("É barato e, além disso, funciona bem.", "Це дешево й, крім того, добре працює.", { purpose: "contrast" }),
    ],
    mistakes: [
      mistake("називати всі зв'язкові слова сполучниками", "перевіряти синтаксичний статус елемента та його зв'язок із сусідніми висловленнями", "Українські «тому», «проте», «крім того» також можуть мати різний синтаксичний статус; буквальна відповідність ненадійна."),
    ],
    ukrainian: "Українська має подібні зв'язкові прислівники та прислівникові сполуки. Порівнюйте їх насамперед за функцією — додавання, контраст, наслідок, висновок — і лише потім за формою.",
    regional: "Частина зв'язкових елементів має різну частотність у писемному та усному мовленні. Регістр і пунктуація особливо важливі для формальніших елементів.",
    sources: [
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. II", url: GULBENKIAN_II },
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. III", url: GULBENKIAN_III },
      { label: "Camões — Referencial Camões PLE", url: CAMOES_PLE },
    ],
  }),
  page({
    id: "adverbs-mente",
    slug: "adverbs-mente",
    category: "adverbs",
    titleUk: "Прислівники на -mente",
    titlePt: "Advérbios em -mente",
    titleEn: "Adverbs ending in -mente",
    summary: "Як утворюються, узгоджуються та функціонують прислівники на -mente.",
    aliases: ["прислівники на -mente", "adverbs in -mente", "advérbios em -mente"],
    related: ["mente-formation", "adverb-position", "sentence-adverbs", "adjective-agreement"],
    status: "review",
    origin: "handwritten",
    depth: "high",
    ukrainianContrast: "medium",
    intro: "Суфікс -mente утворює велику кількість прислівників від прикметників: claro → claramente, rápido → rapidamente, possível → possivelmente. Але правило не зводиться до механічного додавання суфікса: важливо визначити твірну форму, орфографію, значення та функцію готового прислівника.",
    definition: "Прислівник на -mente — прислівникова форма, історично пов'язана з жіночою формою прикметника та компонентом mente, яка в сучасній португальській функціонує як прислівниковий утворювач.",
    formulas: [
      { label: "Типове утворення", pattern: "adjetivo (forma feminina) + -mente → advérbio", note: "Для прикметників із формою жіночого роду важливо спочатку встановити відповідну основу." },
      { label: "Кілька прикметників", pattern: "adjetivo₁ + -mente + adjetivo₂ + -mente", note: "У координації можливі спеціальні стилістичні моделі; не варто поширювати один скорочений шаблон на всі випадки без перевірки." },
    ],
    uses: [
      { title: "Спосіб дії", body: "Прислівник може описувати спосіб виконання дії.", examples: [ex("Ela explicou claramente o problema.", "Вона чітко пояснила проблему.")] },
      { title: "Оцінка висловлення", body: "Деякі форми на -mente мають широку область дії.", examples: [ex("Felizmente, chegámos cedo.", "На щастя, ми прийшли рано.")] },
      { title: "Незмінність", body: "Готовий прислівник не узгоджується з підметом чи іменником.", examples: [ex("Eles falaram claramente.", "Вони говорили чітко.")] },
    ],
    examples: [
      ex("clara → claramente", "чітка → чітко", { purpose: "comprehension" }),
      ex("Ela explicou claramente o problema.", "Вона чітко пояснила проблему.", { purpose: "production" }),
      ex("Felizmente, chegámos cedo.", "На щастя, ми прийшли рано.", { purpose: "contrast" }),
    ],
    mistakes: [
      mistake("вважати, що будь-яке слово на -mente є механічним перекладом українського прислівника на -о", "визначати твірний прикметник, правильну форму та функцію утвореного прислівника", "Українська має іншу словотвірну систему; формальна аналогія за суфіксом не встановлює португальську морфологічну модель."),
    ],
    ukrainian: "Українська широко утворює прислівники від прикметників, часто за допомогою -о, тому загальна словотвірна аналогія корисна. Проте португальську модель -mente треба засвоювати як окрему морфологічну конструкцію.",
    regional: "Форми на -mente не мають однакової частотності чи стилістичного профілю. Конкретні твердження про продуктивність або частотність варто перевіряти за словниками та корпусами.",
    sources: [
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. I", url: GULBENKIAN_I },
      { label: "Fundação Calouste Gulbenkian — Gramática do Português, Vol. II", url: GULBENKIAN_II },
      { label: "Camões — Referencial Camões PLE", url: CAMOES_PLE },
    ],
  }),
];
