import type { GrammarPage } from "../types";
const p=(id:string,slug:string,titleUk:string,titlePt:string,titleEn:string,summary:string,intro:string,examples:GrammarPage["examples"],related:string[]=[]):GrammarPage=>({id,slug,category:"adverbs",titleUk,titlePt,titleEn,summary,aliases:[titleUk,slug],related,intro,examples,markers:[],mistakes:[]});
export const pages:GrammarPage[]=[
p("adverbs-overview","overview","Прислівники: огляд","Advérbios","Adverbs overview","Час, місце, спосіб, міра та оцінка.","Прислівник модифікує дієслово, прикметник, інший прислівник або ширшу пропозицію. Клас неоднорідний: частина форм лексична, частина продуктивно утворюється від прикметників.","Позиція прислівника залежить від його семантичного типу й фокусу.",[{pt:"Ele fala bem.",uk:"Він добре говорить."},{pt:"Muito interessante.",uk:"Дуже цікаво."}],["adverb-position","adverbs-degree"]),
p("mente-formation","mente","Прислівники на -mente","Advérbios em -mente","-mente adverbs","Продуктивне утворення прислівників способу.","До жіночої форми прикметника додається -mente: rápida → rapidamente, clara → claramente. Не кожне слово допускає механічне додавання цього суфікса.","Перевіряйте лексичну основу та орфографію.",[{pt:"rápido → rapidamente",uk:"швидко"},{pt:"claro → claramente",uk:"ясно"}],["word-formation-affixes","adverb-position"]),
p("adverb-position","position","Позиція прислівника","Posição do advérbio","Adverb position","Де стоїть прислівник у реченні.","Позиція залежить від семантики. Обставинні прислівники можуть стояти після дієслова, перед ним або на початку речення; прислівники фокусу мають тісніший зв'язок із компонентом, який вони модифікують.","Не існує одного універсального правила про позицію всіх прислівників.",[{pt:"Ele chegou ontem.",uk:"Він прийшов учора."},{pt:"Ontem, ele chegou cedo.",uk:"Учора він прийшов рано."}],["word-order","information-structure"]),
p("ja-ainda","ja-ainda","já та ainda","Já e ainda","já and ainda","Час, уже/ще та прагматичні значення.","já часто позначає досягнення або зміну стану, ainda — продовження стану чи очікування. У питанні й запереченні вони можуть мати контекстні відтінки.","Переклад já як одного українського слова вже не охоплює всіх уживань.",[{pt:"Já chegou.",uk:"Він уже прийшов."},{pt:"Ainda não chegou.",uk:"Він ще не прийшов."}],["aspect-overview","negation-nao"]),
p("sim-nao-emphasis","sim-nao","sim і não як відповіді та фокус","Sim e não","Yes/no and emphasis","Ствердження, заперечення та фокусування.","sim і não можуть бути самостійними відповідями або частиною ширшої конструкції. Повторення заперечення не завжди є помилкою: у португальській воно має системні функції.","Розрізняйте лексичне заперечення й прагматичне підтвердження.",[{pt:"Sim, vou.",uk:"Так, піду."},{pt:"Não, não vou.",uk:"Ні, не піду."}],["negation-nao","double-negation"]),
p("adverbs-degree","degree","Прислівники міри","Advérbios de grau","Degree adverbs","muito, pouco, bastante, tão та інші модифікатори.","Прислівники міри змінюють інтенсивність прикметника, прислівника або дієслова. muito має різну поведінку як прислівник і як квантор при іменнику.","Порівнюйте muito trabalho та trabalhar muito: граматична функція різна.",[{pt:"muito trabalho",uk:"багато роботи"},{pt:"trabalhar muito",uk:"багато працювати"},{pt:"muito interessante",uk:"дуже цікаво"}],["quantifiers-overview","comparatives"])
];