import type { GrammarPage } from "../types";
import { ex, mistake, page } from "../helpers";

const G2="https://gulbenkian.pt/publications/gramatica-do-portugues-vol-ii/";
const G3="https://gulbenkian.pt/publications/gramatica-do-portugues-vol-iii/";
const C="https://www.instituto-camoes.pt/activity/centro-virtual/referencial-camoes-ple";

export const pages: GrammarPage[] = [
page({id:"conformative-clauses",slug:"conformative-clauses",category:"subordinate",titleUk:"Відповідні (конформативні) підрядні",titlePt:"Orações conformativas",titleEn:"Conformative clauses",summary:"Підрядні конструкції, що виражають відповідність джерелу, правилу, способу, домовленості або вже описаній інформації.",aliases:["конформативні підрядні","conformative clauses","orações conformativas","відповідні підрядні"],related:["causal-clauses","comparative-clauses","modal-clauses","discourse-markers"],status:"review",origin:"handwritten",depth:"high",ukrainianContrast:"high",intro:"Конформативні підрядні повідомляють, що ситуація відбувається відповідно до певного джерела, правила, очікування або способу дії. Найтиповіші сполуки — conforme, segundo, como та locuções на кшталт de acordo com. Важливо не змішувати їх із порівняльними конструкціями: спільне «як» в українському перекладі не означає однакової синтаксичної функції.",definition:"Конформативне підрядне встановлює відношення відповідності між основною ситуацією та орієнтиром, заданим підрядною частиною.",formation:"У ролі сполучникових маркерів виступають conforme, segundo, como та споріднені моделі. Вибір форми залежить від того, чи виражається правило, джерело, спосіб або відповідність опису.",uses:[
{title:"Відповідність правилу",body:"Конструкція може показувати, що дія виконується за певною нормою або інструкцією.",examples:[ex("Fiz tudo conforme me explicaram.","Я зробив/ла все так, як мені пояснили.")]},
{title:"Відповідність джерелу",body:"Segundo може вводити інформацію, яку мовець приписує певному джерелу.",examples:[ex("Segundo informou a agência, o voo foi cancelado.","Як повідомило агентство, рейс скасували.")]},
{title:"Відповідність способу",body:"Conforme та como можуть пов'язувати дію зі способом, уже заданим у контексті.",examples:[ex("Faça conforme combinámos.","Зробіть так, як ми домовилися.")]},
{title:"Паралельна зміна",body:"Conforme може мати й інші значення, тому контекст визначає, чи маємо саме конформативне відношення.",examples:[ex("Conforme o tempo passa, a situação muda.","У міру того як минає час, ситуація змінюється."])}
],examples:[ex("Conforme previsto, a reunião começou às nove.","Як і було передбачено, зустріч почалася о дев'ятій.",{purpose:"production"}),ex("Segundo explicou o professor, a regra mudou.","Як пояснив викладач, правило змінилося.",{purpose:"comprehension"})],mistakes:[
mistake("перекладати conforme завжди як «відповідно до»","визначати значення conforme за структурою й контекстом","Conforme бере участь у кількох типах конструкцій.","predicted-l1-transfer","high"),
mistake("ототожнювати segundo з часовим «другий»","аналізувати segundo como marcador de fonte","У дискурсивній конструкції segundo може вводити джерело інформації.","lexical","medium"),
mistake("вважати como у такій конструкції автоматично порівняльним","визначати, чи виражено відповідність способу або порівняння","Португальське como має кілька синтаксичних функцій.","grammar","high")],ukrainian:"Українські «згідно з», «відповідно до», «як повідомив» і «так, як» перекривають частину функцій, але не утворюють прямої таблиці відповідностей. Особливо важливо відрізняти джерело інформації від порівняння.",regional:"Основні маркери функціонують у PT-BR і PT-PT; частотність та вибір конструкцій залежать від жанру й регістру.",sources:[{label:"Gramática do Português, Vol. II",url:G2},{label:"Gramática do Português, Vol. III",url:G3},{label:"Camões — Referencial Camões PLE",url:C}]}),
page({id:"proportional-clauses",slug:"proportional-clauses",category:"subordinate",titleUk:"Пропорційні підрядні",titlePt:"Orações proporcionais",titleEn:"Proportional clauses",summary:"Конструкції, у яких зміна однієї ситуації або ступеня пов'язується зі зміною іншої.",aliases:["пропорційні підрядні","proportional clauses","orações proporcionais"],related:["temporal-clauses","comparative-clauses","consecutive-clauses"],status:"review",origin:"handwritten",depth:"high",ukrainianContrast:"high",intro:"Пропорційність описує не просто одночасність двох подій, а системний зв'язок між їхніми змінами: коли одна величина, інтенсивність або ситуація змінюється, друга змінюється разом із нею. Типовими засобами є à medida que, à proporção que та conforme в релевантних контекстах.",definition:"Пропорційне підрядне виражає кореляцію між зміною двох ситуацій, параметрів або ступенів.",formation:"Найвиразніші моделі — à medida que, à proporção que; можливі також конструкції з conforme, якщо контекст виражає корельовану зміну. Обидві частини можуть містити градуйовані предикати.",uses:[
{title:"Поступова зміна",body:"Одна ситуація змінюється паралельно іншій.",examples:[ex("À medida que estudava, compreendia melhor.","У міру того як він/вона вчився/лася, краще розумів/ла.")]},
{title:"Кореляція ступенів",body:"Дві величини або характеристики змінюються разом.",examples:[ex("À proporção que a procura aumenta, os preços sobem.","У міру зростання попиту ціни підвищуються.")]},
{title:"Повторювана закономірність",body:"Пропорційна конструкція може описувати регулярний зв'язок, а не одну конкретну подію.",examples:[ex("À medida que envelhecemos, mudamos de hábitos.","У міру того як ми старіємо, змінюємо звички.")]},
{title:"Відмежування від часу",body:"Часова конструкція відповідає на питання «коли», тоді як пропорційна — на питання про взаємозалежність змін.",examples:[ex("Quando cresce, aprende novas coisas.","Коли він/вона росте, дізнається нове.")]}
],examples:[ex("À medida que o projeto avança, surgem novos problemas.","У міру просування проєкту виникають нові проблеми.",{purpose:"production"}),ex("À proporção que a noite avançava, a rua ficava mais vazia.","У міру того як минав вечір, вулиця ставала порожнішою.",{purpose:"comprehension"})],mistakes:[
mistake("перекладати à medida que лише як «коли»","перевіряти, чи є кореляція між двома змінами","Часова близькість сама по собі не створює пропорційності.","concept","high"),
mistake("вважати qualquer conforme пропорційним","аналізувати семантичний зв'язок між частинами","Conforme має кілька значень і функцій.","grammar","high"),
mistake("будувати пропорційність без зміни в обох частинах","перевіряти наявність корельованої динаміки","Якщо одна частина лише задає час, конструкція може бути часовою.","concept","medium")],ukrainian:"Українські «у міру того як», «чим..., тим...» та близькі моделі передають подібну ідею кореляції. Однак португальські сполучники не мають механічної відповідності кожній українській моделі.",regional:"Моделі à medida que та à proporção que використовуються в обох основних різновидах; вибір значною мірою залежить від стилю.",sources:[{label:"Gramática do Português, Vol. II",url:G2},{label:"Gramática do Português, Vol. III",url:G3},{label:"Camões — Referencial Camões PLE",url:C}]}),
page({id:"modal-clauses",slug:"modal-clauses",category:"subordinate",titleUk:"Модальні підрядні",titlePt:"Orações modais",titleEn:"Modal clauses",summary:"Підрядні конструкції, що описують спосіб, манеру або обставину, у якій відбувається дія.",aliases:["модальні підрядні","modal clauses","orações modais"],related:["conformative-clauses","temporal-clauses","comparative-clauses","gerundial-reduced-clauses"],status:"review",origin:"handwritten",depth:"high",ukrainianContrast:"high",intro:"Модальні підрядні відповідають передусім на питання про те, як саме відбувається ситуація. У португальській модальність способу часто виражається como, como se та іншими моделями, а межа між модальним, порівняльним і конформативним значенням визначається контекстом.",definition:"Модальне підрядне характеризує спосіб або манеру реалізації дії чи стану головної частини.",formation:"Маркерами можуть бути como та складніші сполуки, зокрема como se. Форма como se поєднує модальну інтерпретацію з умовно-ірреальним порівнянням і часто вимагає особливого вибору способу.",uses:[
{title:"Спосіб дії",body:"Como вводить спосіб, за яким відбувається дія.",examples:[ex("Faça como eu lhe mostrei.","Зробіть так, як я вам показав/ла.")]},
{title:"Уявна манера",body:"Como se описує ситуацію так, ніби вона відбувається певним чином.",examples:[ex("Ele fala como se soubesse tudo.","Він говорить так, ніби знає все.")]},
{title:"Модальне порівняння",body:"У деяких контекстах конструкція одночасно порівнює реальну поведінку з уявною манерою.",examples:[ex("Ela age como se nada tivesse acontecido.","Вона поводиться так, ніби нічого не сталося.")]},
{title:"Відмежування від відповідності",body:"Конструкція conforme pode означати «відповідно до», тоді як como часто фокусується на способі дії.",examples:[ex("Organizou tudo como combinámos.","Він/вона організував/ла все так, як ми домовилися.")]}
],examples:[ex("Ele respondeu como lhe ensinaram.","Він відповів так, як його навчили.",{purpose:"production"}),ex("Ela olha para mim como se me conhecesse.","Вона дивиться на мене так, ніби знає мене.",{purpose:"comprehension"})],mistakes:[
mistake("вважати como se звичайним «якщо»","розпізнавати значення «ніби/так, наче»","Como se вводить уявну або гіпотетичну манеру, а не звичайну умову.","grammar","high"),
mistake("замінювати como se індикативом без урахування конструкції","вивчати модель разом із відповідною формою дієслова","У como se вибір способу пов'язаний із характером уявної ситуації.","grammar","high"),
mistake("ототожнювати всі речення з como","визначати функцію: спосіб, порівняння, відповідність чи інше значення","Одна форма може реалізувати різні синтаксико-семантичні відношення.","concept","high")],ukrainian:"Українські «як», «так, як», «ніби», «наче» покривають значну частину цих значень. Проте португальське como потребує аналізу всієї конструкції, а не перекладу одного слова.",regional:"Основні модальні моделі спільні для PT-BR та PT-PT; відмінності частіше стосуються регістру, лексичного вибору й частотності.",sources:[{label:"Gramática do Português, Vol. II",url:G2},{label:"Gramática do Português, Vol. III",url:G3},{label:"Camões — Referencial Camões PLE",url:C}]})
];