import type { GrammarPage } from "../types";
import { ex, mistake, page } from "../helpers";

export const pages: GrammarPage[] = [
  page({
    id: "determiners-overview",
    slug: "overview",
    category: "determiners",
    titleUk: "Детермінативи: система перед іменником",
    titlePt: "Determinantes",
    titleEn: "Determiners overview",
    summary: "Артиклі, вказівні, присвійні та квантори як система референції й кількості.",
    aliases: ["детермінативи","determinantes","determiners"],
    related: ["articles-definite","articles-indefinite","zero-article","quantifiers-overview","determiners-agreement"],
    status: "draft", origin: "handwritten", depth: "high", ukrainianContrast: "high",
    intro: "Перед іменником португальська може кодувати не лише його рід і число, а й референцію, кількість, належність та дискурсивний статус. Артиклі, вказівні, присвійні та квантори тому зручно вивчати як одну систему, хоча конкретні слова належать до різних граматичних класів.",
    definition: "Детермінатив — елемент іменної групи, який допомагає визначити її референцію, кількість або інший спосіб ідентифікації іменника.",
    uses: [
      { title: "Референція", body: "o/a та um/uma допомагають розрізняти означені й неозначені іменні групи.", examples: [ex("Vi um cão. O cão era pequeno.", "Я побачив/побачила собаку. Собака була маленька.")] },
      { title: "Вказування", body: "este/esse/aquele кодують дейктичну або дискурсивну відстань.", examples: [ex("Este livro é meu.", "Ця книжка моя.")] },
      { title: "Належність", body: "meu/seu тощо пов'язують іменну групу з власником.", examples: [ex("O meu livro está aqui.", "Моя книжка тут.")] },
      { title: "Кількість", body: "todo, cada, algum, nenhum та інші елементи обмежують множину або розподіл.", examples: [ex("Cada aluno recebeu um livro.", "Кожен учень отримав книжку.")] }
    ],
    examples: [ex("O livro está na mesa.", "Книжка на столі."), ex("Este livro é meu.", "Ця книжка моя."), ex("Cada aluno recebeu um livro.", "Кожен учень отримав книжку.")],
    mistakes: [mistake("вважати артикль прямим аналогом українського слова","визначати референцію всієї іменної групи","Українська часто кодує ті самі відношення контекстом, порядком слів або лексичними засобами.","predicted-l1-transfer","high")],
    ukrainian: "Українська не має артиклів, але має інші засоби означеності, вказування, належності та кількості. Тому корисно переносити не українську форму, а питання: про який референт, яку кількість і який статус групи йдеться.",
    regional: "Система детермінативів спільна для основних різновидів, але окремі моделі вживання артиклів і присвійних мають регіональну варіантність.",

  }),
  page({
    id: "articles-proper-names",
    slug: "proper-names",
    category: "articles",
    titleUk: "Артикль із власними назвами",
    titlePt: "Artigo com nomes próprios",
    titleEn: "Articles with proper names",
    summary: "Коли власна назва вживається з артиклем і чому це не зводиться до правила «імена завжди без артикля».",
    aliases: ["артикль імена","o João","a Maria","nomes próprios"],
    related: ["articles-definite","articles-geography","articles-regional","personal-names"],
    status: "draft", origin: "handwritten", depth: "high", ukrainianContrast: "high",
    intro: "Власна назва вже сама по собі ідентифікує референт, але португальська не тому автоматично забороняє артикль. Особливо важливі особові імена та географічні назви: вибір залежить від назви, різновиду мови й контексту.",
    definition: "Артикль при власній назві — означений артикль, що входить до іменної групи з власним іменем.",
    uses: [
      { title: "Особові імена", body: "У PT-PT означений артикль перед особовими іменами широко вживається; у PT-BR безартиклеве вживання багатьох імен значно звичніше.", examples: [ex("A Maria chegou cedo.", "Марія прийшла рано.", { variety: "PT" }), ex("Maria chegou cedo.", "Марія прийшла рано.", { variety: "BR" })] },
      { title: "Назва як уже ідентифікований референт", body: "Артикль може бути частиною усталеної моделі конкретної назви.", examples: [ex("O João vive no Porto.", "Жуан живе в Порту.", { variety: "PT" })] }
    ],
    examples: [ex("A Maria telefonou.", "Марія зателефонувала.", { variety: "PT" }), ex("Maria telefonou.", "Марія зателефонувала.", { variety: "BR" })],
    mistakes: [mistake("вважати всі власні імена безартиклевими","перевіряти конкретну назву, різновид і регістр","Артикль із власними назвами має системну варіантність.","predicted-l1-transfer","high")],
    ukrainian: "В українській особове ім'я зазвичай не потребує артикля. Це не означає, що португальська модель має бути безартиклевою.",
    regional: "PT-PT і PT-BR відрізняються частотністю та нормативними моделями при особових іменах; не перетворюйте це на дві взаємовиключні системи.",
    brPt: "PT-PT: артикль при особових іменах типовий у багатьох контекстах. PT-BR: безартиклеве ім'я часто є нейтральним. Конкретна норма залежить від конструкції та регіону.",

  }),
  page({
    id: "articles-geography",
    slug: "geography",
    category: "articles",
    titleUk: "Артикль із географічними назвами",
    titlePt: "Artigos com topónimos",
    titleEn: "Articles with place names",
    summary: "Країни, міста, річки, гори та інші географічні назви.",
    aliases: ["географічні назви","topónimos","o Brasil","Portugal","a França"],
    related: ["articles-definite","articles-regional","prep-em","articles-proper-names"],
    status: "draft", origin: "handwritten", depth: "medium", ukrainianContrast: "high",
    intro: "Географічні назви не утворюють одного простого класу щодо артикля. Частина країн і регіонів уживається з означеним артиклем, частина — без нього; міста, річки та інші назви мають власні моделі.",
    definition: "Географічний артикль — уживання означеного артикля як частини іменної групи з географічною назвою.",
    uses: [
      { title: "Країни з артиклем", body: "Назва може мати усталений артикль: o Brasil, a França.", examples: [ex("O Brasil é grande.", "Бразилія велика."), ex("A França fica na Europa.", "Франція розташована в Європі.")] },
      { title: "Країни без артикля", body: "Інші назви вживаються без нього: Portugal.", examples: [ex("Portugal fica na Europa.", "Португалія розташована в Європі.")] },
      { title: "Прийменник + назва", body: "Після em, de та інших прийменників форма залежить від того, чи має назва артикль.", examples: [ex("No Brasil.", "У Бразилії."), ex("Em Portugal.", "У Португалії.")] }
    ],
    examples: [ex("Vivo em Portugal.", "Я живу в Португалії."), ex("Vivo no Brasil.", "Я живу в Бразилії.")],
    mistakes: [mistake("додавати артикль до кожної назви країни","вивчати географічну назву разом із її нормативною моделлю","Артикль не передбачується лише семантичним класом «країна».","predicted-l1-transfer","high")],
    ukrainian: "Українська не має артикля при назвах країн. У португальській краще запам'ятовувати країну разом із моделлю артикля та типовими прийменниковими формами.",
    regional: "Деякі географічні назви мають варіантність за різновидом або локальною традицією; конкретний випадок треба перевіряти окремо.",

  }),
  page({
    id: "articles-possessives",
    slug: "possessives",
    category: "articles",
    titleUk: "Артикль із присвійними",
    titlePt: "Artigo + possessivo",
    titleEn: "Articles with possessives",
    summary: "o meu / meu: взаємодія означеного артикля та присвійного.",
    aliases: ["присвійний артикль","o meu","meu livro","artigo + possessivo"],
    related: ["possessives","articles-definite","articles-regional"],
    status: "draft", origin: "handwritten", depth: "high", ukrainianContrast: "high",
    intro: "Присвійний meu, teu, seu тощо вже ідентифікує власника, але португальська може також мати означений артикль перед присвійним: o meu livro. Це зона, де PT-PT і PT-BR мають різні частотні та нормативні профілі.",
    definition: "Конструкція artigo + possessivo — іменна група, де означений артикль передує присвійному детермінативу.",
    uses: [
      { title: "Означена група з присвійним", body: "У багатьох контекстах PT-PT типовим є o meu livro, a minha casa.", examples: [ex("O meu livro está aqui.", "Моя книжка тут.", { variety: "PT" })] },
      { title: "Без артикля", body: "Безартиклевий possessivo + noun також нормативний у частині різновидів і конструкцій, особливо в PT-BR.", examples: [ex("Meu livro está aqui.", "Моя книжка тут.", { variety: "BR" })] }
    ],
    examples: [ex("A minha irmã mora aqui.", "Моя сестра живе тут.", { variety: "PT" }), ex("Minha irmã mora aqui.", "Моя сестра живе тут.", { variety: "BR" })],
    mistakes: [mistake("вважати o meu єдиною можливою формою","перевіряти різновид і конструкцію","Артикль із присвійним має нормативну та частотну варіантність.","predicted-l1-transfer","high")],
    ukrainian: "Українське «мій/моя» не потребує артикля, тому форма o meu може спочатку виглядати надлишковою. Її треба сприймати як частину португальської іменної групи.",
    regional: "Різниця PT-PT/PT-BR тут особливо помітна, але частотність не дорівнює граматичності: безартиклеві й артиклеві моделі треба оцінювати в конкретному різновиді та контексті.",
    brPt: "PT-PT широко використовує artigo + possessivo. PT-BR безартиклевий possessivo + noun дуже продуктивний; артикль теж можливий у багатьох контекстах.",

  }),
  page({
    id: "generic-reference-articles",
    slug: "generic-reference",
    category: "articles",
    titleUk: "Узагальнення: клас чи окремий представник",
    titlePt: "Referência genérica",
    titleEn: "Generic reference",
    summary: "Як означений, неозначений і нульовий детермінативи можуть подавати загальний клас.",
    aliases: ["узагальнення","generic reference","referência genérica"],
    related: ["articles-definite","zero-article","articles-indefinite"],
    status: "draft", origin: "handwritten", depth: "medium", ukrainianContrast: "high",
    intro: "Узагальнене висловлення говорить не про одного конкретного референта, а про клас або тип. Португальська може реалізувати таке читання різними моделями, тому «generic = os» є надто грубим правилом.",
    definition: "Generic reference — референція до класу, виду або узагальненої ситуації, а не до одного конкретного екземпляра.",
    uses: [
      { title: "Множина з означеним артиклем", body: "Може охоплювати весь клас.", examples: [ex("Os cães são animais domésticos.", "Собаки — домашні тварини.")] },
      { title: "Голий plurals", body: "Нульова детермінація теж може мати узагальнене читання залежно від конструкції.", examples: [ex("Cães precisam de exercício.", "Собакам потрібні фізичні навантаження.")] },
      { title: "Неозначений однини", body: "Може представляти типовий екземпляр класу.", examples: [ex("Um cão precisa de cuidados.", "Собака потребує догляду.")] }
    ],
    examples: [ex("Os gatos gostam de dormir.", "Коти люблять спати."), ex("Um gato precisa de cuidados.", "Кіт потребує догляду.")],
    mistakes: [mistake("вчити один артикль як єдиний спосіб узагальнення","визначати тип узагальнення та іменної групи","Різні детермінативні моделі можуть мати generic reading.","editorial","high")],
    ukrainian: "Українська часто виражає узагальнення голим множинним або одниною без артикля. Не перекладайте цю відсутність форми механічно на португальську.",
    regional: "Вибір моделі залежить від синтаксису та дискурсу; не зводьте generic reference до простої таблиці артиклів.",

  }),
  page({
    id: "determiners-agreement",
    slug: "agreement",
    category: "determiners",
    titleUk: "Узгодження детермінативів",
    titlePt: "Concordância dos determinantes",
    titleEn: "Determiner agreement",
    summary: "Рід і число в артиклях, вказівних, присвійних та інших детермінативах.",
    aliases: ["узгодження детермінативів","concordância","determinantes"],
    related: ["determiners-overview","noun-gender","noun-number","possessives"],
    status: "draft", origin: "handwritten", depth: "medium", ukrainianContrast: "high",
    intro: "Багато детермінативів узгоджуються з іменником за родом і числом: este livro / esta casa / estes livros / estas casas. У присвійних формах рід і число зазвичай стосуються належної речі, а не власника.",
    definition: "Узгодження детермінатива — морфологічна відповідність його форми граматичному роду та/або числу іменника.",
    formulas: [{label:"Вказівний",pattern:"este/esta/estes/estas + N"},{label:"Присвійний",pattern:"meu/minha/meus/minhas + N"}],
    examples: [ex("Esta casa é grande.", "Цей будинок великий."), ex("Estas casas são grandes.", "Ці будинки великі."), ex("A minha irmã chegou.", "Моя сестра прийшла.")],
    mistakes: [mistake("узгоджувати meu за родом власника","узгоджувати присвійний із названою річчю","minha irmã означає, що irmã жіночого роду; власник може бути будь-якої статі.","predicted-l1-transfer","high")],
    ukrainian: "Українська також має узгодження присвійних, тому тут є позитивний перенос: питання «якого роду іменник?» працює подібно. Але конкретні парадигми португальської треба вчити окремо.",
    regional: "Базове узгодження стабільне; варіантність стосується передусім вибору самого детермінатива та його взаємодії з іншими компонентами.",

  }),
  page({
    id: "scope-and-reference",
    slug: "scope-reference",
    category: "determiners",
    titleUk: "Сфера дії та референція",
    titlePt: "Escopo e referência",
    titleEn: "Scope and reference",
    summary: "Як кількісні й означальні елементи змінюють інтерпретацію іменної групи.",
    aliases: ["сфера дії","scope","reference","референція"],
    related: ["determiners-overview","quantifiers-overview","generic-reference","articles-definite"],
    status: "draft", origin: "handwritten", depth: "high", ukrainianContrast: "high",
    intro: "Детермінатив не лише відповідає на питання «який/чий». Він може змінювати множину референтів, яку охоплює висловлення. Особливо це видно з todo, cada, algum, nenhum та запереченням.",
    definition: "Сфера дії — частина висловлення, над якою оператор кількості, заперечення або іншого модифікатора має інтерпретаційний вплив.",
    uses: [
      { title: "todo", body: "todo може мати значення «весь/усі» або «кожен» залежно від форми та конструкції.", examples: [ex("Todos os alunos chegaram.", "Усі учні прийшли."), ex("Todo dia trabalho.", "Я працюю щодня.")] },
      { title: "nenhum", body: "Заперечувальний детермінатив виключає всі члени відповідного набору.", examples: [ex("Nenhum aluno faltou.", "Жоден учень не пропустив заняття.")] }
    ],
    examples: [ex("Cada aluno recebeu um livro.", "Кожен учень отримав книжку."), ex("Alguns alunos faltaram.", "Деякі учні пропустили заняття.")],
    mistakes: [mistake("перекладати todo, cada, algum лише одним українським словом","спочатку визначати множину та сферу дії","Одна лексема може мати різні конструкційні інтерпретації.","predicted-l1-transfer","medium")],
    ukrainian: "Українська має власні квантори «весь», «кожен», «деякий», «жоден», але їхня синтаксична поведінка не є дзеркальною португальській.",
    regional: "Інтерпретація залежить від конструкції, позиції та контексту; це не лише питання словникового перекладу.",

  })
];
