import type { GrammarPage } from "../types";
import { ex, mistake } from "../helpers";

export const pages: GrammarPage[] = [
  {
    id: "determiners-overview", slug: "overview", category: "determiners",
    titleUk: "Детермінативи: система перед іменником", titlePt: "Determinantes", titleEn: "Determiners overview",
    summary: "Артиклі, вказівні, присвійні, кількісні та неозначені елементи як одна система іменної групи.",
    aliases: ["детермінативи","determinantes","determiners","іменна група"],
    related: ["articles-definite","articles-indefinite","zero-article","demonstratives","possessives","quantifiers-overview"],
    intro: "Артиклі не існують ізольовано. Перед іменником португальська комбінує різні типи детермінативів: означені й неозначені артиклі, вказівні, присвійні, квантори та інші елементи. Для українськомовного читача це важливо, бо українська не має такої ж артиклевої системи, а визначеність часто відновлюється з контексту.",
    formulas: [{ label: "Іменна група", pattern: "Det + N + Mod", note: "Det може бути артиклем, вказівним, присвійним або квантором; не всі типи вільно комбінуються." }],
    examples: [ex("o meu livro","моя книжка"),ex("este livro","ця книжка"),ex("alguns livros","деякі книжки"),ex("um livro","якась книжка")],
    mistakes: [mistake("вважати o / a аналогом українського «цей»","розрізняти визначеність, дейксис і володіння","Артикль не вказує на просторову близькість.")],
    ukrainian: "Українською визначеність часто відновлюється з контексту, порядком слів або вказівними словами. Португальська частіше граматикалізує її в детермінативі.",
    brPt: "Ядро системи спільне. Відмінності в частотності артикля з власними назвами, присвійними та в розмовних конструкціях описуються окремо.",
    regional: "Функціональне ядро детермінативів стабільне, хоча частотність і локальні моделі варіюють.",
  },
  {
    id: "quantifiers-overview", slug: "quantifiers", category: "determiners",
    titleUk: "Квантифікація: весь, кожен, деякий, жоден", titlePt: "Quantificação", titleEn: "Quantification",
    summary: "todo, cada, algum, nenhum, qualquer, muito, pouco та їхні відмінності.",
    aliases: ["квантифікація","quantifiers","quantificação","todo","cada","algum","nenhum"],
    related: ["indefinites","determiners-overview","negation-ninguem","cardinals"],
    intro: "Квантори визначають обсяг множини або кількість. Українські «всі», «кожен», «будь-який», «деякий» не є взаємозамінними, і португальський артикль додає ще один рівень структури.",
    formulas: [{ label: "Сукупність", pattern: "todo o + N / todos os + N", note: "todo o livro = увесь книжковий об'єкт; todos os livros = усі книжки." },{ label: "Дистрибуція", pattern: "cada + N(sg)", note: "cada livro = кожна книжка; після cada — однина." }],
    uses: [
      { title: "todo", body: "todo o dia = увесь день; у PT-BR todo dia може означати «щодня».", examples: [ex("Li o livro todo.","Я прочитав усю книжку."),ex("Todos os alunos chegaram.","Усі студенти прийшли.")] },
      { title: "cada", body: "Дистрибутивний квантор: члени множини розглядаються по одному.", examples: [ex("Cada aluno recebeu um livro.","Кожен студент отримав книжку.")] },
      { title: "algum / nenhum", body: "algum вводить невизначену наявність; nenhum заперечує її.", examples: [ex("Algum aluno faltou.","Якийсь студент був відсутній."),ex("Nenhum aluno faltou.","Жоден студент не був відсутній.")] },
      { title: "qualquer", body: "Залежно від контексту: «будь-який» або довільний/звичайний.", examples: [ex("Escolhe qualquer livro.","Вибери будь-яку книжку.")] },
    ],
    examples: [ex("muitos problemas","багато проблем"),ex("poucas pessoas","мало людей"),ex("bastante tempo","досить часу"),ex("demasiadas perguntas","надто багато запитань")],
    mistakes: [mistake("cada livros","cada livro","Після cada — однина."),mistake("todos livro","todos os livros / todo o livro","todo/todos взаємодіють з артиклем та узгодженням."),mistake("qualquer = завжди «будь-який»","читати значення в контексті","qualquer має ширше прагматичне поле.")],
    ukrainian: "Українські «весь» і «кожен» теж розрізняють сукупність і дистрибуцію, але португальський артикль додає окремий рівень.",
    brPt: "PT-BR продуктивно використовує todo dia, toda semana зі значенням регулярності. Не плутайте це з todo o dia = «увесь день».",
    regional: "Квантифікація є спільною системою; відмінності частіше стосуються артикля та розмовної частотності.",
    tables: [{ caption: "Ключове розрізнення", headers: ["Форма","Значення","Приклад"], rows: [["todo o","весь / цілий","todo o livro"],["todos os","усі члени множини","todos os livros"],["cada","кожен окремо","cada livro"],["algum","якийсь / деякий","algum livro"],["nenhum","жоден","nenhum livro"],["qualquer","будь-який / довільний","qualquer livro"]] }],
  },
  {
    id: "scope-and-reference", slug: "scope-reference", category: "determiners",
    titleUk: "Сфера дії та референція", titlePt: "Escopo e referência", titleEn: "Scope and reference",
    summary: "Чому вибір детермінатива змінює те, про які об'єкти йдеться.",
    aliases: ["сфера дії","scope","reference","референція","referência"],
    related: ["determiners-overview","quantifiers-overview","generic-reference","articles-definite"],
    intro: "Вибір між um, o, algum, cada, todo, qualquer змінює спосіб, у який слухач будує множину референтів. Це семантичний рівень артиклів і кванторів, якого не можна пояснити лише перекладом.",
    uses: [
      { title: "Новий референт", body: "um вводить невизначений референт.", examples: [ex("Vi um cão.","Я побачив якогось собаку.")] },
      { title: "Відомий референт", body: "o подає референт як ідентифікований у дискурсі або ситуації.", examples: [ex("O cão estava junto à porta.","Собака був біля дверей.")] },
      { title: "Клас", body: "Множинний означений артикль може позначати клас.", examples: [ex("Os cães são animais sociais.","Собаки — соціальні тварини.")] },
      { title: "Сфера квантора", body: "Cada aluno leu um livro не означає обов'язково одну й ту саму книжку для всіх; інтерпретація залежить від контексту.", examples: [ex("Cada aluno leu um livro.","Кожен студент прочитав книжку / по книжці.")] },
    ],
    ukrainian: "Українська дозволяє залишати частину референційної інформації невираженою. Португальський текст частіше змушує вибрати детермінатив.",
    brPt: "Розподіл артикля з узагальненнями й часовими виразами може відрізнятися за нормою та частотністю.",
    regional: "Дистрибутивне та колективне прочитання є семантичною, а не суто регіональною відмінністю.",
  },
  {
    id: "determiners-agreement", slug: "agreement", category: "determiners",
    titleUk: "Узгодження детермінативів", titlePt: "Concordância dos determinantes", titleEn: "Determiner agreement",
    summary: "Рід і число в артиклях, вказівних, присвійних і кванторах.",
    aliases: ["узгодження детермінативів","concordância","determinante"],
    related: ["determiners-overview","noun-gender","noun-number","possessives","demonstratives"],
    intro: "Більшість детермінативів узгоджується з іменником у роді та/або числі. Тому форму треба вибирати за португальським іменником, а не за його українським перекладом.",
    formulas: [{ label: "Артикль", pattern: "o/a + N; os/as + N", note: "Рід і число визначають форму." },{ label: "Вказівний", pattern: "este/esta/estes/estas + N", note: "Вказівний узгоджується з іменником." }],
    examples: [ex("o livro / a casa","книжка / будинок"),ex("estes livros / estas casas","ці книжки / ці будинки"),ex("meu irmão / minha irmã","мій брат / моя сестра"),ex("muitos alunos / muitas alunas","багато студентів / студенток")],
    mistakes: [mistake("esta livro","este livro","Вказівний узгоджується з родом."),mistake("muito pessoas","muitas pessoas","Квантор узгоджується з іменником, коли детермінує групу.")],
    ukrainian: "Український рід часто збігається, але не завжди. Саме тому узгодження треба будувати від португальського іменника.",
    brPt: "Система узгодження спільна; розмовні скорочення не слід переносити в формальне письмо.",
    regional: "Для PT-PT та PT-BR стандартні форми узгодження переважно збігаються.",
  },
];