import type { GrammarPage } from "../types";
import { ex, mistake, page } from "../helpers";

const sources = [
  { label: "Ciberdúvidas da Língua Portuguesa", url: "https://ciberduvidas.iscte-iul.pt/" },
  { label: "Gramática do Português — Fundação Calouste Gulbenkian", url: "https://gulbenkian.pt/publications/gramatica-do-portugues/" },
  { label: "Camões — Referencial Camões PLE", url: "https://www.instituto-camoes.pt/activity/centro-virtual/referencial-camoes-ple" }
];

export const pages: GrammarPage[] = [
  page({
    id: "noun-determiner-closure", slug: "noun-determiner-closure", category: "nouns",
    titleUk: "Іменник, рід, число та детермінативи: карта тонких випадків",
    titlePt: "Nome, género, número e determinantes: mapa dos casos finos",
    titleEn: "Nouns, gender, number and determiners: fine-grained coverage",
    summary: "Модулі про рід власних і запозичених назв, типи множини, count/mass nouns, артиклі, референцію та квантифікатори.",
    aliases: ["рід і число іменників", "noun and determiner closure"],
    related: ["noun-gender","noun-number","articles-definite","articles-indefinite","determiners-overview","quantifiers-overview"],
    status: "review", origin: "handwritten", depth: "high", ukrainianContrast: "high",
    intro: "Базові статті про іменник і детермінативи не завжди закривають усі вузькі інвентарні випадки. Тут вони зібрані як окремі модулі: від роду професій і запозичень до типів множини, масових іменників, власних назв та області дії квантифікаторів.",
    definition: "Цей closure-map описує морфологічні та детермінативні властивості іменних груп, які потребують окремого навчального пояснення навіть тоді, коли належать до ширшої статті.",
    uses: [
      { title: "Рід професій і назв осіб — модулі 28", body: "Рід іменника та стать референта не є тотожними категоріями. Назви професій можуть мати різні морфологічні моделі залежно від слова та різновиду мови.", examples: [ex("A médica chegou cedo.", "Лікарка прийшла рано.", { purpose: "production" })] },
      { title: "Рід запозичень і власних назв — модулі 29–30", body: "Запозичене слово або власна назва може набувати роду за лексичною традицією, формою, семантикою чи усталеним уживанням. Не виводьте рід механічно з української.", examples: [ex("O software foi atualizado.", "Програмне забезпечення оновили.", { purpose: "contrast" })] },
      { title: "Моделі множини — модулі 33–38", body: "Регулярна множина, -s, закінчення після приголосних, варіанти -ão та нерегулярні чергування треба розглядати як систему, а не як один шаблон.", examples: [ex("cidadão → cidadãos", "громадянин → громадяни", { purpose: "comprehension" })] },
      { title: "Незмінні та pluralia tantum — модулі 39–41", body: "Деякі іменники не змінюють форму або мають переважно/лише множинне вживання. Граматичне число не завжди відповідає українському слову один-до-одного.", examples: [ex("as férias", "канікули / відпустка", { purpose: "contrast" })] },
      { title: "Count/mass і колективні іменники — модулі 42–43", body: "Лічильність і масовість впливають на детермінацію, кількісні конструкції та референцію. Collective noun називає сукупність, але граматична поведінка залежить від конструкції.", examples: [ex("dois litros de água", "два літри води", { purpose: "production" })] },
      { title: "Абстрактні, власні та загальні іменники — модулі 44–45", body: "Тип референції взаємодіє з артиклем і контекстом. Власна назва не означає автоматично відсутність артикля.", examples: [ex("A Maria chegou.", "Марія прийшла.", { purpose: "contrast" })] },
      { title: "Складені іменники та іменні групи — модулі 46–48", body: "Compound noun має власну лексичну структуру; група з кількома іменниками потребує аналізу head, modifier і agreement.", examples: [ex("guarda-chuva", "парасолька", { purpose: "comprehension" })] },
      { title: "Артиклі та референція — модулі 49–66", body: "Definite, indefinite і zero article взаємодіють з definiteness, specificity, genericity, анафорою, власними назвами, географічними назвами, професіями, абстрактними й масовими іменниками та фіксованими виразами.", examples: [ex("O Brasil é grande.", "Бразилія велика.", { purpose: "production" }), ex("Preciso de água.", "Мені потрібна вода.", { purpose: "contrast" })] },
      { title: "Демонстративи та присвійні — модулі 67–71", body: "Demonstratives можуть кодувати просторову або дискурсивну дистанцію; possessive constructions мають власну систему детермінації.", examples: [ex("Este livro é meu.", "Ця книжка моя.", { purpose: "production" })] },
      { title: "Квантифікатори й область дії — модулі 72–88", body: "todo, cada, algum, nenhum, qualquer, ambos, outro, mesmo та próprio відрізняються за значенням, узгодженням, референцією й scope. Не зводьте їх до одного українського перекладу.", examples: [ex("Cada aluno recebeu um livro.", "Кожен учень отримав книжку.", { purpose: "production" }), ex("Nem todo aluno chegou.", "Не кожен учень прийшов.", { purpose: "contrast" })] }
    ],
    examples: [
      ex("A médica chegou cedo.", "Лікарка прийшла рано.", { purpose: "production" }),
      ex("Cada aluno recebeu um livro.", "Кожен учень отримав книжку.", { purpose: "production" }),
      ex("Nem todo aluno chegou.", "Не кожен учень прийшов.", { purpose: "contrast" })
    ],
    nonUses: ["Не переносіть український рід автоматично на португальський.", "Не вважайте кожну множину регулярною.", "Не трактуйте відсутність артикля як просту «помилку».", "Не прирівнюйте todo, cada, qualquer та outro лише через український переклад."],
    markers: ["o/a", "um/uma", "cada", "todo", "algum", "nenhum", "qualquer", "ambos"],
    mistakes: [
      mistake("Рід = біологічна стать", "розрізняти grammatical gender і natural sex", "Граматичний рід є властивістю форми/лексеми."),
      mistake("Власна назва завжди без артикля", "перевіряти різновид і тип власної назви", "Артикль із власними назвами варіює."),
      mistake("todo і cada взаємозамінні", "визначати кванторну структуру", "Вони реалізують різні способи квантифікації.")
    ],
    ukrainian: "Українська також має рід, число, лічильність, означеність у дискурсі та квантифікацію, але не має артиклів. Тому частину португальської інформації український переклад передає контекстом.",
    comparisonUk: "Артиклі ≈ немає прямого морфологічного аналога; cada ≈ «кожен», todo ≈ «весь/кожен» залежно від конструкції, nenhum ≈ «жоден/ніякий».",
    regional: "Вживання артиклів із власними назвами та окремі лексичні норми можуть різнитися між PT-BR і PT-PT; регіональну примітку слід читати разом із джерелом.",
    sources
  }),
  page({
    id: "pronoun-clitic-closure", slug: "pronoun-clitic-closure", category: "pronouns",
    titleUk: "Займенники й клітики: повна карта форм і позицій",
    titlePt: "Pronomes e clíticos: mapa completo de formas e posições",
    titleEn: "Pronouns and clitics: forms and placement",
    summary: "Об'єктні, рефлексивні, взаємні, емфатичні та відносні займенники; próclise, ênclise, mesóclise й регіональна варіативність.",
    aliases: ["займенники та клітики", "pronoun clitic closure"],
    related: ["object-pronouns","clitic-pronouns","clitic-placement","clitics-br-pt","clitic-clusters"],
    status: "review", origin: "handwritten", depth: "high", ukrainianContrast: "high",
    intro: "Займенникова система португальської потребує розрізнення tonic pronouns, clitics, syntactic function і variety. Окрема увага потрібна до o/a/os/as, lhe/lhes, reflexive/reciprocal forms, relative forms та розподілу próclise/ênclise/mesóclise.",
    definition: "Клитика — фонологічно слабка займенникова форма, яка залежить від дієслівного хоста; її позиція визначається синтаксисом, морфологією, різновидом і регістром.",
    uses: [
      { title: "Особові та об'єктні займенники — модулі 110–115", body: "Розрізняйте subject, direct object і indirect object. o/a/os/as та lhe/lhes не є просто двома стилістичними варіантами.", examples: [ex("Eu o vi.", "Я його/це бачив.", { purpose: "contrast" }), ex("Eu lhe falei.", "Я сказав йому/їй.", { purpose: "contrast" })] },
      { title: "lhe vs o/a — модуль 116", body: "Форма залежить від syntactic function і valency, а не від того, який український займенник здається природнішим.", examples: [ex("Eu lhe dei o livro.", "Я дав йому книжку.", { purpose: "production" })] },
      { title: "Рефлексивність і взаємність — модулі 118–119", body: "Reflexive se/me/te тощо повертають роль до subject; reciprocal reading потребує множинного antecedent і відповідного контексту.", examples: [ex("Eles se ajudaram.", "Вони допомогли одне одному.", { purpose: "contrast" })] },
      { title: "Омонімія clitic/tonic та omission — модулі 120–123", body: "Нульовий суб'єкт і нульовий об'єкт — різні явища. Emphatic forms не слід змішувати з клитиками.", examples: [ex("Eu mesmo fiz isso.", "Я сам це зробив.", { purpose: "contrast" })] },
      { title: "Відносні форми — модулі 127–135", body: "que, quem, qual, o qual, cujo, onde та o que мають різні синтаксичні ролі. Free relatives не тотожні звичайним relative clauses.", examples: [ex("Quem chegar primeiro entra.", "Хто прийде першим, той заходить.", { purpose: "contrast" })] },
      { title: "a gente, nós і системи звертання — модулі 136–140", body: "a gente граматично узгоджується як третя особа однини, хоча семантично може означати групу, включно з мовцем. tu/você/vocês/vós розподіляються нерівномірно між різновидами та регістрами.", examples: [ex("A gente vai amanhã.", "Ми підемо завтра.", { purpose: "production" })] },
      { title: "Clitic inventory та tonic/clitic contrast — модулі 141–143", body: "Спочатку визначте форму і синтаксичну функцію, а вже потім позицію. Не всі займенники поводяться як clitics.", examples: [ex("Falei com ele.", "Я говорив із ним.", { purpose: "production" })] },
      { title: "Próclise, ênclise, mesóclise і triggers — модулі 144–150", body: "У PE ênclise є базовим шаблоном у багатьох нейтральних контекстах, тоді як певні елементи викликають próclise. У PB próclise значно ширше представлена, особливо в розмовному мовленні; формальна письмова норма має власні варіанти.", examples: [ex("Não me diga isso.", "Не кажіть мені цього.", { purpose: "production" }), ex("Ele apresentou-se.", "Він представився.", { purpose: "contrast" })] },
      { title: "Clitics із підрядністю, питаннями та імперативом — модулі 149–152", body: "Контекст перед дієсловом може змінювати позицію clitic; imperative має власні моделі.", examples: [ex("Quando me vires, avisa.", "Коли мене побачиш, дай знати.", { purpose: "contrast" })] },
      { title: "Clitics з infinitive/gerund та clusters — модулі 153–157", body: "У складених дієслівних конструкціях позиція може залежати від хоста, mood, variety та регістру. Clitic clusters мають обмеження порядку й сумісності.", examples: [ex("Quero vê-lo.", "Я хочу його побачити.", { purpose: "production" })] },
      { title: "Регістр і PT-BR/PT-PT — модуль 160", body: "Не описуйте одну модель як «португальську взагалі»: розрізняйте variety, channel і register. Особливо це важливо для clitic placement.", examples: [ex("Eu te vi ontem.", "Я бачив тебе вчора.", { purpose: "contrast" })] }
    ],
    examples: [ex("Não me diga isso.", "Не кажіть мені цього.", { purpose: "production" }), ex("A gente vai amanhã.", "Ми підемо завтра.", { purpose: "production" })],
    nonUses: ["Не називайте всі займенники clitics.", "Не виводьте позицію clitic лише з українського перекладу.", "Не переносіть правило PE без маркування на PB.", "Не вважайте варіантність тотальною взаємозамінністю."],
    markers: ["o", "a", "os", "as", "lhe", "lhes", "me", "te", "se", "próclise", "ênclise"],
    mistakes: [mistake("lhe = o/a у будь-якій позиції", "визначати syntactic function", "lhe/lhes і o/a/os/as мають різні функції.")],
    ukrainian: "Українська має повні займенники та відмінювання, але не має португальської системи clitics і їхньої позиційної варіативності.",
    comparisonUk: "o/a ≈ «його/її/це» в ролі прямого додатка; lhe ≈ «йому/їй» у відповідних конструкціях; але функціональний розподіл не завжди збігається з українським відмінком.",
    regional: "Для PT-BR/PT-PT clitic placement є доказово важливою зоною варіації; Ciberdúvidas прямо описує систематичні відмінності між різновидами.",
    sources
  }),
  page({
    id: "numeral-preposition-crase-closure", slug: "numeral-preposition-crase-closure", category: "prepositions",
    titleUk: "Числівники, прийменники та crase: розширені модулі",
    titlePt: "Numerais, preposições e crase: módulos ampliados",
    titleEn: "Numerals, prepositions and crase: expanded coverage",
    summary: "Типи числівників, дати, час, кількості, прийменникові значення, contractions, crase та діагностика.",
    aliases: ["числівники прийменники crase", "numeral preposition crase closure"],
    related: ["cardinals","ordinals","prepositions-overview","crase","crase-rules","crase-optional"],
    status: "review", origin: "handwritten", depth: "high", ukrainianContrast: "high",
    intro: "Числівники та прийменники мають багато вузьких конструкцій, які легко загубити в оглядових статтях. Цей модульний блок робить явними одиниці 161–233.",
    definition: "Розширена карта охоплює не лише назви чисел і прийменників, а й синтаксичні ролі, contractions та умови crase.",
    uses: [
      { title: "Числівникова система — модулі 161–165", body: "Cardinal, ordinal, multiplicative, fractional і collective numerals мають різну синтаксичну поведінку.", examples: [ex("dois terços", "дві третини", { purpose: "production" })] },
      { title: "Десяткові числа, відсотки, дати й роки — модулі 166–169", body: "Числова форма залежить від того, чи йдеться про measurement, percentage, date або calendar year.", examples: [ex("vinte e cinco por cento", "двадцять п'ять відсотків", { purpose: "production" })] },
      { title: "Час, тривалість, гроші та одиниці — модулі 170–173", body: "Clock time, duration, money and measurements мають різні прийменникові та іменні шаблони.", examples: [ex("às três horas", "о третій годині", { purpose: "production" })] },
      { title: "Діапазони, NP та великі числа — модулі 174–181", body: "Numerals можуть бути determiner-like, head of an NP або частиною range. mil і milhão/ milhões мають окремі правила узгодження й plural.", examples: [ex("dois milhões de pessoas", "два мільйони людей", { purpose: "production" })] },
      { title: "Прийменникова система — модулі 183–214", body: "a, de, em, por, para, com, sem, sobre, entre, até, desde, contra, perante, sob, trás та просторові/часові/каузальні/цільові значення мають власні семантичні розподіли.", examples: [ex("Vou para Lisboa.", "Я їду до Лісабона.", { purpose: "production" })] },
      { title: "Вибір прийменника як зміна значення — модулі 203–215", body: "Cause, purpose, means, origin, manner і comparison не повинні зводитися до одного українського «за/з/до».", examples: [ex("Foi por medo.", "Він пішов через страх.", { purpose: "contrast" })] },
      { title: "Contractions — модулі 216–223", body: "de/em/a/por + article і demonstrative формують регулярні злиті форми; їх треба відрізняти від випадків, де злиття не відбувається.", examples: [ex("do livro", "з книжки / книжки", { purpose: "production" })] },
      { title: "Crase — модулі 224–233", body: "Crase виникає не просто «перед жіночим словом», а коли синтаксична структура допускає a + a(s). Перевіряйте preposition government і determiner перед іменником.", examples: [ex("Vou à escola.", "Я йду до школи.", { purpose: "production" }), ex("Vou a Lisboa.", "Я їду до Лісабона.", { purpose: "contrast" })] }
    ],
    examples: [ex("dois milhões de pessoas", "два мільйони людей", { purpose: "production" }), ex("Vou à escola.", "Я йду до школи.", { purpose: "production" })],
    nonUses: ["Не визначайте crase лише за наявністю жіночого іменника.", "Не перекладайте всі прийменники одним українським словом.", "Не змішуйте duration і clock time.", "Не вважайте milhão незмінним числівником."],
    markers: ["a", "de", "em", "por", "para", "à", "mil", "milhão", "%"],
    mistakes: [mistake("à = просто жіноча форма a", "перевіряти структуру a + a(s)", "Crase є результатом злиття, а не окремим прийменником.")],
    ukrainian: "Українська не має crase як графічно-граматичної категорії; прийменникові відношення часто реалізуються відмінками.",
    comparisonUk: "a/de/em/por/para мають кілька українських відповідників залежно від значення; crase ≈ немає прямого аналога.",
    regional: "Норми crase та окремі прийменникові переваги слід прив'язувати до різновиду й нормативного джерела.",
    sources
  }),
  page({
    id: "verb-tense-mood-closure", slug: "verb-tense-mood-closure", category: "verbs",
    titleUk: "Час, спосіб і модальність: розширена карта дієслівної системи",
    titlePt: "Tempo, modo e modalidade: mapa ampliado do sistema verbal",
    titleEn: "Tense, mood and modality: expanded verbal coverage",
    summary: "Парадигми часу, aspectual interpretation, sequence of tenses, subjunctive, imperative та модальність.",
    aliases: ["часи способи модальність", "verb tense mood closure"],
    related: ["verb-system","tense-aspect","subjunctive-overview","indicative-vs-subjunctive","modality-overview"],
    status: "review", origin: "handwritten", depth: "high", ukrainianContrast: "high",
    intro: "Огляд дієслівної системи не замінює окремого пояснення значень часів, sequence of tenses і mood. Цей блок робить явними інвентарні одиниці 234–312, не перетворюючи їх на список форм без семантики.",
    definition: "Час кодує temporal reference, aspect структуру події, mood пов'язує форму з типом висловлення/ставлення, а modality описує можливість, необхідність, дозвіл чи волевиявлення.",
    uses: [
      { title: "Будова дієслівної системи — модулі 234–265", body: "Person/number, conjugation class, regular/irregular patterns, transitivity, valency, argument structure, causatives, raising, control і productive morphology утворюють різні рівні опису.", examples: [ex("Eles fazem isso.", "Вони це роблять.", { purpose: "production" })] },
      { title: "Present — модулі 266–269", body: "Presente do indicativo може мати present, habitual, generic та future-oriented readings залежно від контексту.", examples: [ex("Amanhã vou cedo.", "Завтра я піду рано.", { purpose: "contrast" })] },
      { title: "Минулі часи — модулі 270–275", body: "Pretérito perfeito, imperfeito, composto та mais-que-perfeito не відповідають механічно українським часово-видовим формам.", examples: [ex("Quando cheguei, ele já tinha saído.", "Коли я прийшов, він уже пішов.", { purpose: "contrast" })] },
      { title: "Майбутнє й conditional — модулі 276–279", body: "Futuro, futuro perfeito, condicional і compound tenses мають temporal, modal та discourse uses.", examples: [ex("Ele teria chegado cedo.", "Він, мабуть/мав би приїхати рано.", { purpose: "contrast" })] },
      { title: "Час і дискурс — модулі 280–288", body: "Sequence of tenses, anteriority, simultaneity, posteriority та reported speech формують систему temporal anchoring.", examples: [ex("Disse que viria.", "Він сказав, що прийде.", { purpose: "production" })] },
      { title: "Indicative та subjunctive — модулі 289–303", body: "Indicativo/subjuntivo не варто пояснювати як «реальне/нереальне». Вибір залежить від конструкції, semantic stance, negation, relative/complement clauses, concessive/conditional environments та independent uses.", examples: [ex("Espero que ele venha.", "Сподіваюся, що він прийде.", { purpose: "production" })] },
      { title: "Imperative — модулі 304–307", body: "Affirmative and negative imperatives взаємодіють із pronouns, person system, negation та politeness.", examples: [ex("Não faça isso.", "Не робіть цього.", { purpose: "production" })] },
      { title: "Модальність — модулі 308–312", body: "Conditional, epistemic, deontic, volitional та possibility/necessity/permission readings часто перетинаються з lexical verbs і discourse context.", examples: [ex("Pode entrar.", "Можете зайти.", { purpose: "contrast" })] }
    ],
    examples: [ex("Espero que ele venha.", "Сподіваюся, що він прийде.", { purpose: "production" }), ex("Disse que viria.", "Він сказав, що прийде.", { purpose: "production" })],
    nonUses: ["Не ототожнюйте Portuguese tense з Ukrainian aspect.", "Не зводьте subjunctive до «невпевненості».", "Не аналізуйте future лише як майбутній час.", "Не виводьте mood із перекладу."],
    markers: ["presente", "pretérito", "futuro", "condicional", "indicativo", "subjuntivo", "imperativo"],
    mistakes: [mistake("Subjunctive = нереальність", "аналізувати constructional trigger і stance", "Subjunctive має ширший розподіл.")],
    ukrainian: "Українська має багатшу видову систему дієслова, тому Portuguese tense/aspect не має простого one-to-one відповідника.",
    comparisonUk: "perfeito/imperfeito треба зіставляти з часово-видовою інтерпретацією, а не лише з українським минулим часом.",
    regional: "Основна система спільна для PT-BR/PT-PT, але частотність окремих форм і перифраз може відрізнятися.",
    sources
  }),
  page({
    id: "nonfinite-aspect-se-negation-closure", slug: "nonfinite-aspect-se-negation-closure", category: "verbs",
    titleUk: "Неособові форми, аспект, se та заперечення: closure map",
    titlePt: "Formas não finitas, aspeto, se e negação: mapa de cobertura",
    titleEn: "Non-finite forms, aspect, se and negation coverage",
    summary: "Інфінітив, gerúndio, particípio, aspectual periphrases, se constructions та система заперечення.",
    aliases: ["неособові форми aspect se negation", "nonfinite aspect se closure"],
    related: ["personal-infinitive","gerund-form","participle","aspect-overview","se-overview","negation-nao"],
    status: "review", origin: "handwritten", depth: "high", ukrainianContrast: "high",
    intro: "Блок 313–390 об'єднує кілька систем, які взаємодіють, але не повинні зливатися в одне правило: infinitive, gerund, participle, aspectual periphrases, se та negation.",
    definition: "Non-finite forms мають власну синтаксичну поведінку; aspectual periphrases композиційно подають фазу події; se має кілька граматичних функцій; negation має sentential, constituent і pragmatic readings.",
    uses: [
      { title: "Infinitive — модулі 313–325", body: "Розрізняйте personal/impersonal infinitive, infinitive subject, control, prepositional infinitive, infinitival clauses, modal/perception/causative complements, ao + infinitivo та clitic placement.", examples: [ex("É importante estudar.", "Важливо вчитися.", { purpose: "production" }), ex("É importante estudarmos.", "Важливо, щоб ми вчилися.", { purpose: "contrast" })] },
      { title: "Gerund і progressive — модулі 326–331", body: "Gerund може виражати manner, simultaneity або входити до progressive construction. PT-BR і PT-PT мають помітні різниці в progressive patterns.", examples: [ex("Estou trabalhando.", "Я працюю / зараз працюю.", { purpose: "contrast" })] },
      { title: "Participle — модулі 332–340", body: "Regular/irregular/double participles взаємодіють із ter/haver, ser, estar та agreement. Не всі participles мають однакову поведінку.", examples: [ex("Tenho feito muito.", "Я багато робив останнім часом.", { purpose: "contrast" })] },
      { title: "Aspectual periphrases — модулі 341–360", body: "Acabar de, voltar a, começar a, continuar a, deixar de, ir + infinitivo, estar + gerund/infinitive, andar a, ficar a, vir a, estar para, ter de/que, haver de, poder/dever/querer виражають phase, aspect або modality.", examples: [ex("Acabei de chegar.", "Я щойно прийшов.", { purpose: "production" })] },
      { title: "Se — модулі 361–373", body: "Reflexive, reciprocal, pronominal, passive, impersonal, middle, anticausative і lexicalised se потребують різних diagnostics. Не всі se є «зворотним займенником».", examples: [ex("Vendem-se casas.", "Продаються будинки.", { purpose: "contrast" }), ex("Ele se levantou.", "Він підвівся.", { purpose: "production" })] },
      { title: "Negation — модулі 374–390", body: "Não, constituent negation, negative concord, ninguém/nada/nenhum/nunca/jamais/nem, preverbal/postverbal patterns, double and contrastive negation мають різні функції.", examples: [ex("Ninguém veio.", "Ніхто не прийшов.", { purpose: "production" }), ex("Nunca vi isso.", "Я ніколи цього не бачив.", { purpose: "production" })] }
    ],
    examples: [ex("Vendem-se casas.", "Продаються будинки.", { purpose: "contrast" }), ex("Ninguém veio.", "Ніхто не прийшов.", { purpose: "production" })],
    nonUses: ["Не перекладайте se одним українським «ся».", "Не вважайте gerund еквівалентом українського дієприслівника в усіх контекстах.", "Не вважайте negative concord логічною «подвійною помилкою».", "Не змішуйте aspectual auxiliary і lexical verb."],
    markers: ["infinitivo", "gerúndio", "particípio", "se", "não", "ninguém", "nada", "nunca"],
    mistakes: [mistake("se завжди = reflexive", "перевіряти subject/object/valency diagnostics", "Se має кілька граматичних функцій.")],
    ukrainian: "Українська має відмінні моделі рефлексивності, видів та заперечення; прямий переклад не відтворює всі Portuguese constructions.",
    comparisonUk: "se може відповідати «ся», пасивній формі, безособовій конструкції або не мати окремого українського відповідника.",
    regional: "Progressive construction і clitic placement особливо чутливі до PT-BR/PT-PT; окремі aspectual periphrases також мають різну частотність.",
    sources
  }),
  page({
    id: "clause-syntax-closure", slug: "clause-syntax-closure", category: "syntax",
    titleUk: "Синтаксис клауз: порядок слів, доповнення, координація та підрядність",
    titlePt: "Sintaxe das orações: ordem, complementos, coordenação e subordinação",
    titleEn: "Clause syntax: word order, complements, coordination and subordination",
    summary: "SVO, subject/object placement, information structure, clefts, ellipsis, coordination та типи підрядних речень.",
    aliases: ["синтаксис клауз", "clause syntax closure"],
    related: ["syntax-overview","word-order","coordination","subordination","subordinate-clauses"],
    status: "review", origin: "handwritten", depth: "high", ukrainianContrast: "high",
    intro: "Синтаксичний інвентар 413–494 вимагає не лише загальної сторінки про порядок слів, а й явного покриття constituent roles, information structure, coordination/subordination та relative clauses.",
    definition: "Clause syntax описує структуру предикації, позиції аргументів і adjuncts, зв'язок між клаузами та інформаційне структурування.",
    uses: [
      { title: "Canonical SVO і constituent placement — модулі 413–425", body: "SVO є важливим базовим шаблоном, але null subject, focus, topicalisation та inversion створюють систематичні варіанти.", examples: [ex("A Ana comprou o livro.", "Ана купила книжку.", { purpose: "production" })] },
      { title: "Topicalisation та dislocation — модулі 426–428", body: "Topicalisation, left/right dislocation і ordinary subject placement не є одним явищем. Аналізуйте інформаційну структуру й syntactic integration.", examples: [ex("Esse livro, eu já li.", "Цю книжку я вже прочитав.", { purpose: "contrast" })] },
      { title: "Clefts, focus та information structure — модулі 429–433", body: "Cleft/pseudo-cleft constructions, focus, emphasis і given/new information організують повідомлення, а не просто «переставляють слова».", examples: [ex("Foi a Ana que ligou.", "Це Ана подзвонила.", { purpose: "contrast" })] },
      { title: "Complex predicates, nominalisation та ellipsis — модулі 434–439", body: "Causative, raising, control, complex predicates, nominalisation та ellipsis мають різні structural diagnostics.", examples: [ex("Ele fez o filho sair.", "Він змусив сина вийти.", { purpose: "contrast" })] },
      { title: "Coordination — модулі 440–455", body: "Coordination може поєднувати clauses, NPs, adjectives та інші constituents; punctuation і discourse connectives треба відрізняти від syntactic conjunction.", examples: [ex("Maria e João chegaram.", "Марія та Жуан прийшли.", { purpose: "production" })] },
      { title: "Subordination — модулі 456–482", body: "Complement, subject, object, predicative, relative, causal, concessive, conditional, temporal, purpose, consecutive, comparative, conformative, proportional, modal і locative clauses утворюють різні підтипи.", examples: [ex("Acho que ele vem.", "Я думаю, що він прийде.", { purpose: "production" })] },
      { title: "Relative clauses — модулі 483–494", body: "Relative que/quem/o qual/cujo/onde/o que, preposition + relative, restrictive vs explanatory interpretation, punctuation, antecedent selection і mood утворюють окрему систему.", examples: [ex("O livro que comprei chegou.", "Книжка, яку я купив, прийшла.", { purpose: "contrast" })] }
    ],
    examples: [ex("Foi a Ana que ligou.", "Це Ана подзвонила.", { purpose: "contrast" }), ex("Acho que ele vem.", "Я думаю, що він прийде.", { purpose: "production" })],
    nonUses: ["Не називайте будь-який незвичний порядок слів інверсією.", "Не плутайте focus і topicalisation.", "Не зводьте всі subordinate clauses до одного «підрядного речення».", "Не визначайте restrictive/explanatory лише за комою без аналізу референції."],
    markers: ["SVO", "que", "quem", "cujo", "onde", "foi... que", "porque", "embora", "se"],
    mistakes: [mistake("Український вільніший порядок слів переноситься без змін", "визначати інформаційну структуру та syntactic constraints", "Порядок слів португальської має власні обмеження.")],
    ukrainian: "Українська має значно гнучкіший морфологічно підтриманий порядок слів, тоді як португальська сильніше спирається на position, agreement і information structure.",
    comparisonUk: "Topicalisation часто відповідає українському винесенню теми, але syntactic diagnostics не тотожні.",
    regional: "Окремі word-order і null-subject patterns можуть відрізнятися між PT-BR/PT-PT; не змішуйте regional preference з grammatical impossibility.",
    sources
  }),
  page({
    id: "passive-impersonal-existential-closure", slug: "passive-impersonal-existential-closure", category: "syntax",
    titleUk: "Пасив, безособовість та екзистенційні конструкції",
    titlePt: "Passiva, impessoalidade e construções existenciais",
    titleEn: "Passive, impersonal and existential constructions",
    summary: "ser + particípio, passive se, impersonal se, haver, há, ter, existir, meteorological predicates та resultative estar + particípio.",
    aliases: ["пасив безособові екзистенційні конструкції", "passive impersonal existential closure"],
    related: ["passive-ser","passive-se","impersonal-se","existential-haver","resultative-estar-participle"],
    status: "review", origin: "handwritten", depth: "high", ukrainianContrast: "high",
    intro: "Інвентар 495–510 містить конструкції, які часто плутають через поверхневу схожість. Основне завдання — розрізнити passive, impersonal, existential і resultative readings.",
    definition: "Passive changes the grammatical prominence of the patient; impersonal constructions lack a canonical referential subject; existential constructions introduce existence/presence; resultative describes a state resulting from an event.",
    uses: [
      { title: "ser + particípio — модулі 495–497", body: "Canonical passive має ser + participle; agent може бути виражений por або іншим засобом залежно від конструкції.", examples: [ex("O livro foi escrito por Ana.", "Книжку написала Ана.", { purpose: "production" })] },
      { title: "Passive se vs impersonal se — модулі 498–500", body: "Діагностика залежить від agreement, transitivity і possibility of a patient-like subject. Не кожне se + verb є пасивом.", examples: [ex("Vendem-se casas.", "Продаються будинки.", { purpose: "contrast" })] },
      { title: "haver/há — модулі 501–502", body: "Existential haver у стандартних конструкціях поводиться як impersonal: há muitas pessoas, havia problemas. Agreement не слід механічно будувати за plural complement.", examples: [ex("Há muitas pessoas aqui.", "Тут багато людей.", { purpose: "production" })] },
      { title: "ter existential у PB — модуль 503", body: "Existential ter широко засвідчене в Brazilian Portuguese, особливо в усному/неформальному мовленні; нормативний статус і регістр треба подавати окремо від descriptive fact.", examples: [ex("Tem muita gente aqui.", "Тут багато людей.", { purpose: "contrast" })] },
      { title: "existir, meteorological і impersonal predicates — модулі 504–507", body: "Existir має referential subject; meteorological predicates та temporal fazer мають іншу структуру.", examples: [ex("Existem várias opções.", "Є кілька варіантів.", { purpose: "production" })] },
      { title: "é preciso та resultative estar + particípio — модулі 508–510", body: "É preciso — impersonal/modal construction; estar + participle може описувати resultative state, який не тотожний passive.", examples: [ex("É preciso estudar.", "Потрібно вчитися.", { purpose: "production" }), ex("A porta está fechada.", "Двері зачинені.", { purpose: "contrast" })] }
    ],
    examples: [ex("Há muitas pessoas aqui.", "Тут багато людей.", { purpose: "production" }), ex("A porta está fechada.", "Двері зачинені.", { purpose: "contrast" })],
    nonUses: ["Не називайте кожне se passive.", "Не узгоджуйте haver existential як звичайне дієслово з plural complement.", "Не прирівнюйте passive і resultative.", "Не видавайте PB existential ter за універсальну норму всіх різновидів."],
    markers: ["foi escrito", "vende-se", "há", "tem", "existem", "é preciso", "está fechado"],
    mistakes: [mistake("Vendem-se casas = reflexive se", "перевіряти transitivity і agreement", "Тут se бере участь у passive construction.")],
    ukrainian: "Українська має пасив, безособові та екзистенційні конструкції, але структурні діагностики відрізняються.",
    comparisonUk: "há/tem/existir часто перекладаються «є», але Portuguese grammar розрізняє їхню структуру.",
    regional: "Existential ter особливо важливе для PB; у PE стандартна система віддає перевагу haver/existir у відповідних контекстах.",
    sources
  }),
  page({
    id: "agreement-word-formation-closure", slug: "agreement-word-formation-closure", category: "word-formation",
    titleUk: "Узгодження та словотвір: продуктивні моделі й межі",
    titlePt: "Concordância e formação de palavras: modelos produtivos e limites",
    titleEn: "Agreement and word formation: productive patterns and limits",
    summary: "Узгодження в складних групах, coordinated subjects, collective nouns, derivation, affixation, diminutives, conversion, compounding та neologisms.",
    aliases: ["узгодження і словотвір", "agreement word formation closure"],
    related: ["agreement-sv","agreement-special","prefixation","suffixation","compounding"],
    status: "review", origin: "handwritten", depth: "high", ukrainianContrast: "high",
    intro: "Окремі інвентарні одиниці 511–549 стосуються не нових частин мови, а тонких правил узгодження та продуктивності словотворчих моделей. Вони потребують explicit coverage, щоб не залишатися прихованими всередині оглядових статей.",
    definition: "Agreement is grammatical dependency between forms; derivation creates lexical items or changes category/meaning; inflection realizes grammatical categories without creating a new lexeme.",
    uses: [
      { title: "Agreement map — модулі 511–525", body: "Nominal, adjective, determiner, subject-verb, predicative, mixed-gender, coordinated-subject, collective-noun, a gente, haver, se, numeral, participle та semantic-vs-grammatical agreement мають різні diagnostics.", examples: [ex("A maioria chegou cedo.", "Більшість прийшла рано.", { purpose: "contrast" })] },
      { title: "Derivation vs inflection — модуль 526", body: "Inflection changes grammatical form within a lexeme; derivation creates a new lexical item or category. Межа інколи потребує лексикографічного й морфологічного аналізу.", examples: [ex("feliz → felizes", "щасливий → щасливі", { purpose: "contrast" })] },
      { title: "Prefixation і suffixation — модулі 527–530", body: "Productive prefixes/suffixes можуть змінювати meaning або category; продуктивність не означає, що кожне формально можливе слово є нормативним.", examples: [ex("feliz → infelizmente", "щасливий → на жаль / нещасливо", { purpose: "comprehension" })] },
      { title: "Negative/evaluative derivation — модулі 531–535", body: "Negative prefixes, diminutives, augmentatives, pejorative and affective suffixes мають semantic/pragmatic effects, які не можна зводити до розміру.", examples: [ex("casinha", "будиночок", { purpose: "contrast" })] },
      { title: "Nominalisation, adjectivisation, verbal derivation — модулі 536–538", body: "Category-changing derivation може створювати нові аргументні та syntactic properties.", examples: [ex("decidir → decisão", "вирішувати → рішення", { purpose: "comprehension" })] },
      { title: "Conversion і compounding — модулі 540–544", body: "Zero derivation і compounding мають різні формальні ознаки; compound noun/adjective/verb не слід визначати лише за написанням.", examples: [ex("o jantar", "вечеря / прийом їжі", { purpose: "contrast" })] },
      { title: "Lexicalisation, productivity, neologisms — модулі 545–549", body: "Lexicalised formations можуть втратити прозорість, а neologism formation використовує продуктивні й напівпродуктивні моделі. Orthography may preserve or obscure morphology.", examples: [ex("guarda-chuva", "парасолька", { purpose: "comprehension" })] }
    ],
    examples: [ex("A maioria chegou cedo.", "Більшість прийшла рано.", { purpose: "contrast" }), ex("casinha", "будиночок", { purpose: "contrast" })],
    nonUses: ["Не робіть словотвірне правило з одного слова.", "Не вважайте кожне зменшення фізичним зменшенням.", "Не плутайте derivation з inflection.", "Не оголошуйте продуктивною будь-яку теоретично можливу форму."],
    markers: ["-inho", "-ão", "in-", "des-", "re-", "prefixo", "sufixo", "composição"],
    mistakes: [mistake("casinha = лише маленький будинок", "аналізувати affective/pragmatic meaning", "Diminutive може виражати ставлення, а не тільки розмір.")],
    ukrainian: "Українська має розвинений словотвір і зменшувальні/збільшувальні суфікси, але конкретні Portuguese affixes та їх продуктивність не збігаються.",
    comparisonUk: "Португальські diminutives часто мають українські функціональні аналоги, але формальна модель інша.",
    regional: "Продуктивність окремих suffixes та неологізмів залежить від жанру, регіону й часу; normative status треба відділяти від corpus attestation.",
    sources
  }),
  page({
    id: "phonology-orthography-closure", slug: "phonology-orthography-closure", category: "phonology",
    titleUk: "Фонологія, вимова та орфографія: системне покриття",
    titlePt: "Fonologia, pronúncia e ortografia: cobertura sistemática",
    titleEn: "Phonology, pronunciation and orthography: systematic coverage",
    summary: "Голосні, носові дифтонги, приголосні, наголос, prosody, connected speech, IPA та графемно-фонемні відповідності.",
    aliases: ["фонологія та орфографія", "phonology orthography closure"],
    related: ["phonetics-phonology","vowel-system","consonant-system","syllabification","stress-phonology","punctuation"],
    status: "review", origin: "handwritten", depth: "high", ukrainianContrast: "high",
    intro: "Фонологічний блок 550–615 потребує явного розрізнення system-level description, pronunciation guidance і orthographic rules. Особливо важливо не описувати PT-BR як єдину вимову португальської.",
    definition: "Phonology studies contrastive sound organization; phonetics describes realization; orthography maps written forms to conventions rather than one-to-one sounds.",
    uses: [
      { title: "Phonetics vs phonology — модулі 550–551", body: "Phoneme/allophone distinction prevents the error of treating every pronunciation difference as a separate phoneme.", examples: [ex("rato", "щур", { purpose: "comprehension" })] },
      { title: "Vowels and diphthongs — модулі 552–559", body: "Open/closed e/o, unstressed reduction, nasal vowels/diphthongs, oral diphthongs, triphthongs and glides form interacting subsystems.", examples: [ex("mãe", "мати", { purpose: "comprehension" })] },
      { title: "Consonant variation — модулі 560–567", body: "r/rr, s, x, lh/nh/ch, c/ç, g/j and b/v have context-sensitive realizations and regional variation.", examples: [ex("carro", "автомобіль", { purpose: "comprehension" })] },
      { title: "Syllables, stress and prosody — модулі 568–575", body: "Syllable structure, syllabification, stress, prosody, intonation and rhythm interact but are distinct levels.", examples: [ex("música", "музика", { purpose: "comprehension" })] },
      { title: "Connected speech — модулі 576–578", body: "Reduction, deletion, elision and linking are channel-sensitive phonetic processes; do not turn them into spelling rules.", examples: [ex("de água", "води / з води", { purpose: "comprehension" })] },
      { title: "IPA and pronunciation methodology — модулі 579–583", body: "IPA is a descriptive tool; unfamiliar words should be checked against reliable pronunciation sources. PT-BR/PT-PT and regional pronunciation deserve separate notes.", examples: [ex("Lisboa", "Лісабон", { purpose: "comprehension" })] },
      { title: "Orthography — модулі 584–615", body: "Alphabet, letter names, grapheme-sound correspondences, accentuation, acute/circumflex/grave/tilde/cedilla, capitalization, hyphenation, Acordo Ortográfico and PT-BR/PT-PT spelling variants form a distinct system.", examples: [ex("ação", "дія", { purpose: "comprehension" })] }
    ],
    examples: [ex("mãe", "мати", { purpose: "comprehension" }), ex("ação", "дія", { purpose: "comprehension" })],
    nonUses: ["Не ототожнюйте букву з фонемою.", "Не переносіть одну regional pronunciation як universal.", "Не вважайте connected-speech reduction орфографічною нормою.", "Не змішуйте accent marks із crase."],
    markers: ["IPA", "r/rr", "s", "x", "lh", "nh", "ç", "á", "â", "ã"],
    mistakes: [mistake("Одна літера = один звук", "аналізувати grapheme-sound correspondence", "Португальська має контекстні та морфофонологічні відповідності.")],
    ukrainian: "Українська кирилиця має інші grapheme-phoneme correspondences; португальські nasal vowels та accentuation потребують окремого навчання.",
    comparisonUk: "IPA є спільним описовим інструментом, але українські орфографічні правила не переносяться на португальську.",
    regional: "PT-BR/PT-PT pronunciation differences є системними в окремих ділянках; African varieties додають власну regional variation.",
    sources
  }),
  page({
    id: "semantics-pragmatics-discourse-closure", slug: "semantics-pragmatics-discourse-closure", category: "semantics",
    titleUk: "Семантика, прагматика й дискурс: карта інтерпретації",
    titlePt: "Semântica, pragmática e discurso: mapa da interpretação",
    titleEn: "Semantics, pragmatics and discourse: interpretation map",
    summary: "Референція, scope, ambiguity, speech acts, politeness, information structure, cohesion, genres та reported speech.",
    aliases: ["семантика прагматика дискурс", "semantics pragmatics discourse closure"],
    related: ["reference-overview","pragmatics-overview","speech-acts","information-structure","discourse-overview"],
    status: "review", origin: "handwritten", depth: "high", ukrainianContrast: "high",
    intro: "Останні блоки інвентарю 616–743 не є «словником термінів». Вони описують, як граматична форма взаємодіє зі значенням, контекстом, інформаційною структурою, жанром та різновидами португальської.",
    definition: "Semantics describes encoded meaning; pragmatics explains context-sensitive interpretation; discourse studies how grammatical choices function across connected text and interaction.",
    uses: [
      { title: "Lexical vs grammatical meaning — модулі 616–620", body: "Tense, aspect and event structure можуть бути граматично закодовані або лексично уточнені. Розрізнення потрібне для правильного аналізу перефразування.", examples: [ex("Ele começou a trabalhar.", "Він почав працювати.", { purpose: "production" })] },
      { title: "Event structure — модулі 621–630", body: "States, activities, accomplishments, achievements, habituality, iteration, inception, continuation, termination і resultative meaning допомагають пояснювати aspectual choice.", examples: [ex("Ele começou a correr.", "Він почав бігати.", { purpose: "contrast" })] },
      { title: "Modality — модулі 631–636", body: "Possibility, necessity, permission, volition та epistemic/evidential interpretation можуть реалізуватися через mood, modal verbs, adverbs і discourse.", examples: [ex("Talvez ele venha.", "Можливо, він прийде.", { purpose: "production" })] },
      { title: "Reference, deixis, anaphora, quantification, scope — модулі 637–644", body: "Definiteness, specificity, genericity, deixis, anaphora, cataphora, quantification and scope формують інтерпретацію nominal and sentential structures.", examples: [ex("Este livro é meu.", "Ця книжка моя.", { purpose: "contrast" })] },
      { title: "Ambiguity — модулі 645–648", body: "Semantic, structural and lexical ambiguity треба розрізняти; grammar choice may resolve or preserve ambiguity.", examples: [ex("Vi o homem com o telescópio.", "Я бачив чоловіка з телескопом.", { purpose: "contrast" })] },
      { title: "Pragmatics and speech acts — модулі 649–674", body: "Requests, commands, advice, offers, invitations, permission, prohibition, agreement, correction, confirmation, refusal, politeness, directness, hedging, social distance, address forms and pragmatic particles depend on context.", examples: [ex("Pode fechar a janela?", "Можете зачинити вікно?", { purpose: "contrast" })] },
      { title: "Discourse organization — модулі 675–701", body: "Topic/comment, theme/rheme, focus, given/new, cohesion, sequencing, narrative, description, exposition, argumentation, formal/academic/journalistic/spoken prose and reported speech require text-level analysis.", examples: [ex("Quanto ao relatório, ele será enviado amanhã.", "Щодо звіту, його надішлють завтра.", { purpose: "contrast" })] },
      { title: "Collocation and lexical frames — модулі 702–719", body: "Verb-noun, adjective-noun, verb-preposition, adjective-preposition, noun-preposition collocations and lexicalised constructions constrain grammar choice. False friends and calques are learner-relevant but require evidence.", examples: [ex("tomar uma decisão", "прийняти рішення", { purpose: "production" })] },
      { title: "Pluricentric Portuguese — модулі 720–743", body: "European, Brazilian, Angolan, Mozambican and other Lusophone varieties should be treated as varieties of one pluricentric language. Separate standard/normative status, attestation frequency, social/register variation and evidence-scoped regional notes.", examples: [ex("Tu vais.", "Ти йдеш.", { purpose: "contrast" })] }
    ],
    examples: [ex("Pode fechar a janela?", "Можете зачинити вікно?", { purpose: "contrast" }), ex("tomar uma decisão", "прийняти рішення", { purpose: "production" })],
    nonUses: ["Не називайте pragmatic interpretation purely grammatical.", "Не робіть learner-error claims без evidence.", "Не змішуйте frequency з grammaticality.", "Не називайте одну regional form «неправильною» без нормативного джерела."],
    markers: ["topic", "focus", "scope", "speech act", "politeness", "register", "PT-BR", "PT-PT"],
    mistakes: [mistake("Часте = нормативне", "розділяти frequency, grammaticality і normative status", "Це різні типи тверджень.")],
    ukrainian: "Українська має аналогічні прагматичні та дискурсивні функції, але граматичні ресурси для їх реалізації відрізняються.",
    comparisonUk: "Speech act і discourse functions часто мають функціональні аналоги, але не обов'язково тотожні форми.",
    regional: "Цей блок за визначенням потребує variety/register/channel/evidence scoping; не узагальнюйте PT-BR на всю португальську.",
    sources
  })
];
