import type { GrammarPage } from "../types";
const p=(id:string,slug:string,titleUk:string,titlePt:string,titleEn:string,summary:string,intro:string,teachingNote:string,examples:GrammarPage["examples"],related:string[]=[]):GrammarPage=>({id,slug,category:"nouns",titleUk,titlePt,titleEn,summary,aliases:[titleUk,slug],related,intro:teachingNote ? `${intro}\n\n${teachingNote}` : intro,examples,markers:[],mistakes:[]});
export const pages:GrammarPage[]=[
p("noun-gender","noun-gender","Рід іменників","Género dos nomes","Noun gender","Чоловічий і жіночий рід.","Рід у португальській — граматична властивість іменника, від якої залежать артиклі та узгодження. Закінчення допомагають, але не гарантують рід: ` o problema `, ` a mão `.","Вивчайте іменник разом з артиклем, особливо для винятків.",[{pt:"o problema",uk:"проблема"},{pt:"a mão",uk:"рука"},{pt:"o mapa",uk:"карта"}],["gender-vs-ukrainian","articles-definite","adjective-agreement"]),
p("gender-vs-ukrainian","gender-vs-ukrainian","Португальський рід vs український","Género e ucraniano","Gender vs Ukrainian","Розбіжності граматичного роду.","Рід португальського іменника не завжди збігається з українським. Це впливає на артикль, прикметник і займенник, а не лише на переклад.","Корисна стратегія — запам'ятовувати лексему як ` o/a + іменник `.",[{pt:"o problema é sério",uk:"проблема серйозна"},{pt:"a foto está pronta",uk:"фото готове"}],["noun-gender","agreement-na"]),
{
  id: "noun-number",
  slug: "noun-number",
  category: "nouns",
  titleUk: "Однина і множина",
  titlePt: "Número dos nomes",
  titleEn: "Noun number",
  summary: "Число іменників: базова множина, закінчення, незмінювані форми та випадки, де форму треба запам'ятати.",
  aliases: ["число іменників", "однина", "множина", "número", "plural"],
  related: ["plural-formation", "irregular-plurals", "ao-plurals"],
  intro: "Число показує, чи йдеться про один референт, чи про множину. У португальській множина часто має прозору орфографічну форму, але спосіб її утворення залежить від фіналі слова: casa → casas, papel → papéis, animal → animais, mão → mãos.",
  definition: "Граматичне число протиставляє однину (singular) і множину (plural). Для іменника форма числа взаємодіє з артиклем, прикметником, займенником та дієсловом.",
  formation: "Найпростіша модель — додавання -s після голосного: casa → casas. Після -r і -z зазвичай додається -es: flor → flores, rapaz → rapazes. Кінцеве -m переходить у -ns: homem → homens. Для -al/-el/-ol/-ul характерні -ais/-éis/-óis/-uis: animal → animais, papel → papéis. Слова на -ão мають кілька лексичних моделей (-ões, -ães, -ãos), тому їх краще вчити разом із множиною.",
  uses: [
    { title: "Після голосного", body: "До більшості іменників, що закінчуються на голосний, додається -s.", examples: [{pt:"casa → casas",uk:"дім → будинки"},{pt:"livro → livros",uk:"книжка → книжки"}] },
    { title: "Після -r, -z та -m", body: "Форма множини змінює фінальну частину слова, а не просто додає українське закінчення.", examples: [{pt:"flor → flores",uk:"квітка → квіти"},{pt:"rapaz → rapazes",uk:"хлопець → хлопці"},{pt:"homem → homens",uk:"чоловік → чоловіки"}] },
    { title: "Зміна голосного або наголосу", body: "Множина іноді супроводжується зміною наголосу чи якості голосного, тому написання варто перевіряти разом із вимовою.", examples: [{pt:"ovo → ovos",uk:"яйце → яйця"},{pt:"avô → avôs",uk:"дідусь → дідусі"}] },
    { title: "Однакова графічна форма", body: "Деякі слова мають однакову форму в однині та множині; число тоді показують детермінативи й узгодження.", examples: [{pt:"o lápis → os lápis",uk:"олівець → олівці"},{pt:"o vírus → os vírus",uk:"вірус → віруси"}] }
  ],
  examples: [{pt:"A casa é antiga.",uk:"Будинок старий."},{pt:"As casas são antigas.",uk:"Будинки старі."},{pt:"O animal está aqui.",uk:"Тварина тут."},{pt:"Os animais estão aqui.",uk:"Тварини тут."}],
  mistakes: [
    {wrong:"papels",correct:"papéis",explanation:"Кінцеве -el має модель множини -éis."},
    {wrong:"homems",correct:"homens",explanation:"Кінцеве -m переходить у -ns."},
    {wrong:"lápises",correct:"lápis",explanation:"lápis має однакову графічну форму в однині та множині; число видно з контексту."}
  ],
  ukrainian: "Українська має відмінювання іменників за відмінками та числами, тоді як португальська множина не є аналогом українського закінчення в усіх словах. Спочатку визначте португальську орфографічну модель, а вже потім добирайте український відповідник.",
  brPt: "Основні моделі множини спільні для PT-BR і PT-PT. Вимова окремих форм та лексичні переваги можуть відрізнятися, але це не створює двох окремих систем числа.",
  regional: "Опис стосується стандартної сучасної португальської. Окремі незмінювані або запозичені слова можуть мати додаткову варіативність.",
  sources: [{label:"Camões — Referencial Camões PLE",url:"https://www.instituto-camoes.pt/activity/centro-virtual/referencial-camoes-ple"}],
  depth: "high"
},
p("plural-formation","plural-formation","Утворення множини","Formação do plural","Plural formation","Регулярні моделі множини.","Найтиповіша множина додає ` -s `, але ` -r, -z, -m, -al/-el/-ol/-ul ` мають окремі моделі. Деякі форми треба вчити лексично.","Форма множини може змінювати наголос або голосний, тому орфографія й фонетика пов'язані.",[{pt:"flor → flores",uk:"квітка → квіти"},{pt:"animal → animais",uk:"тварина → тварини"},{pt:"homem → homens",uk:"чоловік → чоловіки"}],["noun-number","irregular-plurals","ao-plurals"]),
p("ao-plurals","ao-plurals","Множина на -ão","Plural em -ão","-ão plurals","Три основні моделі множини слів на -ão.","Слова на ` -ão ` можуть мати множину ` -ões, -ães ` або ` -ãos `; вибір значною мірою лексичний. Не виводьте форму лише з одного універсального правила.","Запам'ятовуйте частотні слова разом із множиною.",[{pt:"nação → nações",uk:"нація → нації"},{pt:"pão → pães",uk:"хліб → хліби"},{pt:"irmão → irmãos",uk:"брат → брати"}],["plural-formation","irregular-plurals"]),
p("irregular-plurals","irregular-plurals","Нерегулярні множини","Plurais irregulares","Irregular plurals","Множини, які не виводяться простою механічною формулою.","Частина множин має чергування основи або нестандартне закінчення: ` cão → cães `, ` mal → males `, ` lápis → lápis `. Такі форми варто вчити як словникові пари.","Нерегулярність не означає відсутність моделей: частина форм повторюється в групах.",[{pt:"cão → cães",uk:"собака → собаки"},{pt:"mal → males",uk:"зло → зла"},{pt:"lápis → lápis",uk:"олівець → олівці"}],["noun-number","ao-plurals"]),
p("compound-nouns","compound-nouns","Складні іменники","Nomes compostos","Compound nouns","Множина складених іменників.","Складені іменники мають кілька моделей множини залежно від частин і ступеня лексикалізації: ` guarda-chuva → guarda-chuvas `, ` segunda-feira → segundas-feiras `.","Не множте кожне слово окремо без перевірки конкретної конструкції.",[{pt:"guarda-chuva → guarda-chuvas",uk:"парасоля → парасолі"},{pt:"segunda-feira → segundas-feiras",uk:"понеділок → понеділки"}],["plural-formation","word-formation-affixes"]),
p("common-epicene","common-epicene","Спільний рід і назви статі","Nomes comuns de dois géneros","Common-gender nouns","Іменники, де рід не виражений окремою формою слова.","У деяких назвах професій і осіб форма іменника спільна, а рід показує артикль або узгодження: ` o estudante / a estudante `. Це відрізняється від слів із двома лексичними формами.","Не створюйте жіночу форму автоматично лише за аналогією.",[{pt:"o estudante / a estudante",uk:"студент / студентка"},{pt:"o artista / a artista",uk:"артист / артистка"}],["professions-gender","noun-gender"]),
p("professions-gender","professions-gender","Назви професій і рід","Género das profissões","Gender of professions","Форми назв професій у чоловічому та жіночому роді.","Португальська має як парні форми, так і спільнорідні назви. Жіночі форми не слід механічно будувати одним суфіксом.","Сучасна нормативна практика приймає багато жіночих назв професій, але конкретна форма може бути лексичною.",[{pt:"o professor / a professora",uk:"викладач / викладачка"},{pt:"o estudante / a estudante",uk:"студент / студентка"},{pt:"a médica",uk:"лікарка"}],["common-epicene","noun-gender"]),
p("diminutives","diminutives","Зменшувальні форми","Diminutivos","Diminutives","Зменшення, пестливість і прагматичні відтінки.","Суфікси ` -inho/-inha ` та ` -zinho/-zinha ` можуть виражати не лише фізичний малий розмір, а й пестливість, близькість або інші контекстні відтінки.","Значення зменшувального визначається контекстом; не перекладайте його завжди як «маленький».",[{pt:"casa → casinha",uk:"дім → хатинка / будиночок"},{pt:"café → cafezinho",uk:"кава → кавка / чашка кави"}],["word-formation-affixes","register"]),
p("augmentatives","augmentatives","Збільшувальні форми","Aumentativos","Augmentatives","Збільшення та оцінні суфікси.","Суфікси на кшталт ` -ão/-ona `, ` -zão/-zona ` можуть виражати великий розмір, інтенсивність або оцінку. Значення залежить від слова й контексту.","Аугментатив може бути схвальним, іронічним або негативним.",[{pt:"casa → casarão",uk:"дім → великий будинок / хоромина"},{pt:"calor → calorzão",uk:"сильна спека"}],["word-formation-affixes","register"])
];