import type { GrammarPage } from "../types";
const p=(id:string,slug:string,t:string,pt:string,en:string,s:string,i:string,e:GrammarPage["examples"],r:string[]=[]):GrammarPage=>({id,slug,category:"periphrases",titleUk:t,titlePt:pt,titleEn:en,summary:s,aliases:[t,slug],related:r,intro:i,examples:e});
export const pages:GrammarPage[]=[
p("ter-de","ter-de","ter de + infinitivo","Ter de + infinitivo","ter de + infinitive","Необхідність і обов'язок.","ter de + infinitivo виражає необхідність або обов'язок. Час допоміжного дієслова змінює часову перспективу.","Порівнюйте з dever: значення частково перетинаються, але конструкції не тотожні.",[{pt:"Tenho de trabalhar.",uk:"Я мушу працювати."},{pt:"Tive de sair.",uk:"Мені довелося піти."}],["modality-overview","infinitive-prepositions"]),
p("haver-de","haver-de","haver de + infinitivo","Haver de + infinitivo","haver de + infinitive","Намір, майбутнє або зобов'язання.","haver de + infinitivo має модальні та часові значення, часто з відтінком наміру, прогнозу або неминучості.","Контекст визначає, чи це майбутність, обіцянка чи припущення.",[{pt:"Hei de voltar.",uk:"Я ще повернуся / маю повернутися."}],["modality-overview","futuro"]),
p("acabar-de","acabar-de","acabar de + infinitivo","Acabar de + infinitivo","acabar de + infinitive","Нещодавно завершена дія.","acabar de + infinitivo позначає подію, що відбулася щойно або безпосередньо перед моментом відліку.","Не плутайте з простим завершеним часом.",[{pt:"Acabei de chegar.",uk:"Я щойно прийшов/прийшла."}],["aspect-overview","infinitive-prepositions"]),
p("voltar-a","voltar-a","voltar a + infinitivo","Voltar a + infinitivo","voltar a + infinitive","Повторення дії.","voltar a + infinitivo означає повторне виконання дії: «знову зробити».","Значення повторення походить від конструкції, а не лише від дієслова voltar.",[{pt:"Voltou a chover.",uk:"Знову почався дощ."}],["aspect-overview","infinitive-prepositions"]),
p("comecar-a","comecar-a","começar a + infinitivo","Começar a + infinitivo","começar a + infinitive","Початок дії.","começar a + infinitivo позначає початок ситуації або процесу. Це фазова перифраза.","Відрізняйте її від простого початку об'єкта: починається саме дія.",[{pt:"Começou a chover.",uk:"Почався дощ."}],["aspect-overview","infinitive-prepositions"]),
p("ir-infinitive","ir-infinitive","ir + infinitivo","Ir + infinitivo","ir + infinitive","Плановане або близьке майбутнє.","ir + infinitivo широко вживається для майбутніх ситуацій, особливо в розмовній мові. Часова перспектива залежить від форми ir.","Не плутайте його з буквальним рухом: vou estudar може не означати «іду вчитися».",[{pt:"Vou estudar amanhã.",uk:"Я завтра вчитимуся / збираюся вчитися."}],["futuro","verb-system"]),
p("other-periphrases","other","Інші перифрази","Outras perífrases","Other periphrases","andar a, ficar a, vir a та estar para: додаткові перифрастичні моделі.","Португальська має низку перифрастичних конструкцій, у яких допоміжне або напівдопоміжне дієслово додає фазове, аспектуальне чи часово-модальне значення. andar a + infinitivo може позначати тривалу або повторювану дію; ficar a + infinitivo — стан або дію, що продовжується після певної події; vir a + infinitivo — розвиток до результату; estar para + infinitivo — близькість або підготовленість до дії залежно від контексту.","Не перекладайте ці моделі механічно за значенням окремого дієслова: перифраза утворює власну конструктивну інтерпретацію. Розподіл окремих моделей також залежить від різновиду португальської.",[{pt:"Ando a estudar português.",uk:"Я зараз активно / останнім часом вивчаю португальську.",variety:"PT"},{pt:"Ficou a trabalhar até tarde.",uk:"Він / вона залишився працювати допізна."},{pt:"Veio a descobrir a verdade.",uk:"Зрештою він / вона дізнався / дізналася правду."},{pt:"O comboio está para chegar.",uk:"Потяг має ось-ось прибути."}],["progressive-br-pt","aspect-overview","complex-predicates","estar-a-infinitive"])
];