import type { GrammarPage } from "../types";
const p=(id:string,slug:string,t:string,pt:string,en:string,s:string,i:string,e:GrammarPage["examples"],r:string[]=[]):GrammarPage=>({id,slug,category:"periphrases",titleUk:t,titlePt:pt,titleEn:en,summary:s,aliases:[t,slug],related:r,intro:i,examples:e});
export const pages:GrammarPage[]=[
p("ter-de","ter-de","ter de + infinitivo","Ter de + infinitivo","ter de + infinitive","Необхідність і обов'язок.","ter de + infinitivo виражає необхідність або обов'язок. Час допоміжного дієслова змінює часову перспективу.","Порівнюйте з dever: значення частково перетинаються, але конструкції не тотожні.",[{pt:"Tenho de trabalhar.",uk:"Я мушу працювати."},{pt:"Tive de sair.",uk:"Мені довелося піти."}],["modality-overview","infinitive-prepositions"]),
p("haver-de","haver-de","haver de + infinitivo","Haver de + infinitivo","haver de + infinitive","Намір, майбутнє або зобов'язання.","haver de + infinitivo має модальні та часові значення, часто з відтінком наміру, прогнозу або неминучості.","Контекст визначає, чи це майбутність, обіцянка чи припущення.",[{pt:"Hei de voltar.",uk:"Я ще повернуся / маю повернутися."}],["modality-overview","future"]),
p("acabar-de","acabar-de","acabar de + infinitivo","Acabar de + infinitivo","acabar de + infinitive","Нещодавно завершена дія.","acabar de + infinitivo позначає подію, що відбулася щойно або безпосередньо перед моментом відліку.","Не плутайте з простим завершеним часом.",[{pt:"Acabei de chegar.",uk:"Я щойно прийшов/прийшла."}],["aspect-overview","infinitive-prepositions"]),
p("voltar-a","voltar-a","voltar a + infinitivo","Voltar a + infinitivo","voltar a + infinitive","Повторення дії.","voltar a + infinitivo означає повторне виконання дії: «знову зробити».","Значення повторення походить від конструкції, а не лише від дієслова voltar.",[{pt:"Voltou a chover.",uk:"Знову почався дощ."}],["aspect-overview","infinitive-prepositions"]),
p("comecar-a","comecar-a","começar a + infinitivo","Começar a + infinitivo","começar a + infinitive","Початок дії.","começar a + infinitivo позначає початок ситуації або процесу. Це фазова перифраза.","Відрізняйте її від простого початку об'єкта: починається саме дія.",[{pt:"Começou a chover.",uk:"Почався дощ."}],["aspect-overview","infinitive-prepositions"]),
p("ir-infinitive","ir-infinitive","ir + infinitivo","Ir + infinitivo","ir + infinitive","Плановане або близьке майбутнє.","ir + infinitivo широко вживається для майбутніх ситуацій, особливо в розмовній мові. Часова перспектива залежить від форми ir.","Не плутайте його з буквальним рухом: vou estudar може не означати «іду вчитися».",[{pt:"Vou estudar amanhã.",uk:"Я завтра вчитимуся / збираюся вчитися."}],["futuro","verb-system"])
];