import type { GrammarPage } from "../types";
import { ex, mistake } from "../helpers";

export const pages: GrammarPage[] = [
  {
    id: "pragmatics-overview", slug: "overview", category: "pragmatics",
    titleUk: "Прагматика: значення в контексті", titlePt: "Pragmática", titleEn: "Pragmatics",
    summary: "Як контекст, стосунки між співрозмовниками та ситуація змінюють інтерпретацію граматично правильного речення.",
    aliases: ["прагматика","pragmatics","pragmática","контекст"],
    related: ["speech-acts","politeness","modal-particles","information-structure"],
    intro: "Граматика визначає, що речення може означати; прагматика пояснює, що мовець робить цим реченням у конкретній ситуації. Pode abrir a janela? формально питання про можливість, але в нормальній ситуації часто є ввічливим проханням.",
    uses: [
      { title: "Питання як прохання", body: "Мовець може формально питати про можливість, очікуючи дії.", examples: [ex("Pode fechar a porta?","Можете зачинити двері?")] },
      { title: "Заперечення як корекція", body: "Não, ... не лише заперечує істинність, а й може виправляти попередню репліку.", examples: [ex("Não, não foi ontem; foi hoje.","Ні, не вчора; сьогодні.")] },
      { title: "Контекст визначає силу", body: "Está frio aqui. може бути повідомленням або непрямим проханням зачинити вікно.", examples: [ex("Está frio aqui.","Тут холодно.")] },
    ],
    mistakes: [mistake("перекладати кожне питання буквально","розрізняти форму й мовленнєву дію","Питальна форма може реалізувати прохання, пропозицію чи запрошення.")],
    ukrainian: "Українська теж широко використовує непрямі прохання, тому механізм не чужий. Важливо не переносити готові формули ввічливості з української буквально.",
    brPt: "Інтонація, частки та звертання особливо важливі в розмовному PT-BR; значення не слід описувати лише словниковим перекладом.",
    regional: "Прагматична інтерпретація залежить від ситуації, соціальних норм і регіону.",
  },
  {
    id: "speech-acts", slug: "speech-acts", category: "pragmatics",
    titleUk: "Мовленнєві акти", titlePt: "Atos de fala", titleEn: "Speech acts",
    summary: "Повідомлення, прохання, наказ, пропозиція, обіцянка, вибачення та інші дії мовлення.",
    aliases: ["мовленнєві акти","speech acts","atos de fala","прохання","наказ"],
    related: ["pragmatics-overview","imperative-affirmative","imperative-negative","politeness","questions"],
    intro: "Одна граматична форма може виконувати різні мовленнєві дії. Імператив типовий для наказу, але в контексті може бути інструкцією або запрошенням. Питання може бути проханням.",
    uses: [
      { title: "Прохання", body: "Імператив, питання з poder та умовні формули дають різний ступінь прямоти.", examples: [ex("Fecha a janela.","Зачини вікно."),ex("Pode fechar a janela?","Можете зачинити вікно?"),ex("Podia fechar a janela?","Чи не могли б ви зачинити вікно?")] },
      { title: "Порада", body: "Dever + infinitivo може бути порадою, а не юридичним обов'язком.", examples: [ex("Devias descansar.","Тобі варто відпочити.",{ variety: "PT" })] },
      { title: "Запрошення", body: "Імператив і vamos + infinitivo можуть бути запрошенням до спільної дії.", examples: [ex("Vamos sair?","Підемо?")] },
    ],
    mistakes: [mistake("вважати imperativo завжди грубим наказом","дивитися на ситуацію, звертання й інтонацію","Та сама форма може бути нейтральною інструкцією або дружнім запрошенням.")],
    ukrainian: "Українські «давай», «будь ласка», умовні форми та інтонація виконують аналогічну роботу. Відрізняються конкретні конвенції формулювання.",
  },
  {
    id: "politeness", slug: "politeness", category: "pragmatics",
    titleUk: "Ввічливість і дистанція", titlePt: "Cortesia e distância", titleEn: "Politeness and social distance",
    summary: "tu, você, o senhor/a senhora, умовні форми та непрямі прохання.",
    aliases: ["ввічливість","politeness","cortesia","tu","você","senhor"],
    related: ["tu-vs-voce","speech-acts","questions","conditional"],
    intro: "Ввічливість у португальській не зводиться до одного «ввічливого займенника». Важливі вибір звертання, дієслівна форма, непрямість, por favor, титули та соціальна дистанція. Система сильно варіює між Бразилією, Португалією та іншими країнами.",
    uses: [
      { title: "Пряме прохання", body: "Імператив може бути цілком нормальним між близькими співрозмовниками.", examples: [ex("Espera um momento.","Зачекай хвилинку.")] },
      { title: "Непряме прохання", body: "Умовна форма пом'якшує прохання.", examples: [ex("Podia ajudar-me?","Чи не могли б ви мені допомогти?",{ variety: "PT" }),ex("Você poderia me ajudar?","Чи могли б ви мені допомогти?",{ variety: "BR" })] },
      { title: "Формальне звертання", body: "o senhor / a senhora виражає дистанцію, але доречність залежить від ситуації.", examples: [ex("O senhor precisa de ajuda?","Вам потрібна допомога?")] },
    ],
    mistakes: [mistake("você = універсально ввічливе «Ви»","вибирати форму за регіоном і соціальною ситуацією","У різних лузофонних спільнотах статус você відрізняється.")],
    ukrainian: "Українське «Ви» не має одного прямого відповідника. У португаломовному світі вибір tu/você/senhor може бути регіонально й соціально чутливим.",
    brPt: "PT-BR широко використовує você та регіональні форми, але соціальний статус і частотність відрізняються між регіонами.",
    regional: "PT-PT, PT-BR, PALOP та інші різновиди мають різні системи звертання.",
  },
  {
    id: "modal-particles", slug: "particles", category: "pragmatics",
    titleUk: "Прагматичні частки та маленькі слова", titlePt: "Partículas pragmáticas", titleEn: "Pragmatic particles",
    summary: "já, ainda, mesmo, só, afinal, então та інші слова, що організують інтерпретацію.",
    aliases: ["частки","particles","partículas","já","ainda","mesmo","só","afinal","então"],
    related: ["pragmatics-overview","aspect-overview","discourse-markers","focus"],
    intro: "Деякі короткі слова мають значення, яке не можна передати одним словниковим відповідником. já може кодувати час, зміну стану або очікування; mesmo — тотожність, підсилення або згоду; só — обмеження.",
    uses: [
      { title: "já", body: "Часове «вже» може переходити в значення зміни стану або протиставлення очікуванню.", examples: [ex("Já chegou.","Він/вона вже прийшов/прийшла."),ex("Agora já sei.","Тепер я вже знаю.")] },
      { title: "ainda", body: "«ще» або «досі»; з não — «ще не».", examples: [ex("Ainda não chegou.","Він/вона ще не прийшов/прийшла."),ex("Ainda trabalha aqui.","Він/вона досі тут працює.")] },
      { title: "só", body: "Обмеження: «лише, тільки». Позиція впливає на те, що саме обмежується.", examples: [ex("Só a Ana veio.","Прийшла лише Ана."),ex("A Ana só veio ontem.","Ана прийшла лише вчора.")] },
    ],
    mistakes: [mistake("перекладати já завжди як «вже»","дивитися на стан, час і дискурсивний контраст","У контексті já може означати зміну стану або протиставлення.")],
    ukrainian: "Українські «вже», «ще», «саме», «лише», «таки» мають подібну контекстну гнучкість. Не вчіть їх як простий словник відповідників.",
  },
  {
    id: "register-and-directness", slug: "register", category: "pragmatics",
    titleUk: "Регістр, прямота і стиль", titlePt: "Registo, grau de diretividade e estilo", titleEn: "Register and directness",
    summary: "Нейтральне, розмовне, формальне та письмове формулювання однієї функції.",
    aliases: ["регістр","register","registo","directness","стиль"],
    related: ["pragmatics-overview","politeness","speech-acts","regional"],
    intro: "Граматично правильне речення може бути недоречним за стилем. Для довідника корисно показувати одну функцію в нейтральному, розмовному та формальному варіантах, не оголошуючи один із них «правильнішим».",
    examples: [
      ex("Quero falar consigo.","Я хочу з вами поговорити.",{ variety: "PT", register: "neutral" }),
      ex("Quero falar com você.","Я хочу поговорити з вами.",{ variety: "BR", register: "neutral" }),
      ex("Gostaria de falar consigo.","Я хотів/хотіла б з вами поговорити.",{ variety: "PT", register: "formal" }),
      ex("Queria falar com você.","Я хотів/хотіла поговорити з вами.",{ variety: "BR", register: "neutral" }),
    ],
    mistakes: [mistake("позначати розмовну форму як «неправильну»","позначати register і variety","Регістр — не те саме, що граматична правильність.")],
    brPt: "PT-BR і PT-PT мають різні конвенції звертання та займенникових конструкцій; приклади мають маркувати різновид.",
    regional: "Для PALOP та інших різновидів потрібні окремі корпусні приклади, перш ніж робити широкі нормативні висновки.",
  },
];