import type { GrammarPage } from "../types";
const p=(id:string,slug:string,t:string,pt:string,en:string,s:string,i:string,teachingNote:string,e:GrammarPage["examples"],r:string[]=[]):GrammarPage=>({id,slug,category:"prepositions",titleUk:t,titlePt:pt,titleEn:en,summary:s,aliases:[t,slug],related:r,intro:teachingNote ? `${i}\n\n${teachingNote}` : i,examples:e});
export const pages:GrammarPage[]=[
p("prepositions-overview","overview","Прийменники: система","Preposições","Prepositions overview","Основні прийменники та їхні функції.","Прийменники a, de, em, por, para, com, sem та інші вводять аргументи, обставини й сталі конструкції. Їх не можна повністю звести до українських відмінків.","Вивчайте прийменник разом із керуванням дієслова або сталою рамкою.",[{pt:"Vou a Lisboa.",uk:"Я їду до Лісабона."},{pt:"Moro em Lisboa.",uk:"Я живу в Лісабоні."}],["government-overview","contractions-overview"]),
p("prep-a","a","Прийменник a","Preposição a","Preposition a","Напрямок, адресат, час і керування.","a вводить низку різних відношень: напрямок, адресата, момент часу та аргумент деяких дієслів. Перед означеним артиклем виникають контракції ao, à, aos, às.","Не перекладайте a одним українським прийменником.",[{pt:"Vou ao Porto.",uk:"Я їду до Порту."},{pt:"Chego às oito.",uk:"Я прибуваю о восьмій."},{pt:"Dou o livro a Maria.",uk:"Я даю книжку Марії."}],["a-article","crase","government-overview"]),
p("prep-de","de","Прийменник de","Preposição de","Preposition de","Походження, належність, матеріал і багато керувальних моделей.","de має широкий спектр функцій: origem, posse, matéria, характеристика та інфінітивні конструкції. Перед артиклем він часто контрагується: do, da, dos, das.","Значення визначається конструкцією.",[{pt:"Sou de Kyiv.",uk:"Я з Києва."},{pt:"O livro de Maria.",uk:"Книжка Марії."}],["de-article","infinitive-prepositions"]),
p("prep-em","em","Прийменник em","Preposição em","Preposition em","Місце, час і стан.","em вводить місце, час та інші обставинні або лексикалізовані відношення. Перед артиклем виникають no, na, nos, nas.","Відрізняйте em від a у моделях руху та місця.",[{pt:"Estou em casa.",uk:"Я вдома."},{pt:"Moro no Porto.",uk:"Я живу в Порту."}],["em-article","existential"]),
p("prep-por","por","Прийменник por","Preposição por","Preposition por","Шлях, причина, засіб, тривалість та агент пасиву.","por має кілька системних значень і контрагується з артиклем у pelo/pela/pelos/pelas.","Не зводьте por до одного українського «через».",[{pt:"Passei por Lisboa.",uk:"Я проїхав/проїхала через Лісабон."},{pt:"Foi escrito por Ana.",uk:"Це було написано Аною."}],["por-article","ser-passive","por-para"]),
p("prep-para","para","Прийменник para","Preposição para","Preposition para","Напрямок, мета, адресат і призначення.","para часто виражає спрямованість до цілі, призначення або адресата. У розмовній мові, особливо в PT-BR, можливе скорочення pra.","Не змішуйте para з por лише за українським перекладом.",[{pt:"Vou para casa.",uk:"Я йду додому."},{pt:"Isto é para ti.",uk:"Це для тебе."}],["por-para","infinitive-prepositions"]),
p("por-para","por-para","por чи para","Por ou para","por vs para","Контраст траєкторії/причини та цілі/спрямованості.","Контраст залежить від конструкції. para часто кодує ціль, адресата або призначення; por — шлях, причину, обмін, тривалість або агента пасиву. Це не абсолютна семантична дихотомія.","Вивчайте дієслово та прийменникову рамку разом.",[{pt:"Estudo para aprender.",uk:"Я навчаюся, щоб навчитися."},{pt:"Passei por Coimbra.",uk:"Я проїхав/проїхала через Коїмбру."}],["prep-por","prep-para","government-overview"]),
p("prep-com","com-sem","com і sem","Com e sem","com and sem","Супровід, інструмент і відсутність.","com виражає супровід або засіб, sem — відсутність. com має особливі займенникові форми comigo, contigo тощо.","Порівнюйте прийменник із займенниковою формою.",[{pt:"Vou com ele.",uk:"Я йду з ним."},{pt:"Café sem açúcar.",uk:"Кава без цукру."}],["prepositional-pronouns"]),
p("prep-other","other","Інші прийменники","Outras preposições","Other prepositions","sobre, entre, até, desde, contra, perante та інші.","Другорядні прийменники мають конкретні просторові, часові та абстрактні значення. Частина з них входить до складених прийменників.","Вчіть їх через приклади, а не через довгий список перекладів.",[{pt:"entre amigos",uk:"між друзями"},{pt:"desde ontem",uk:"від учора"},{pt:"até amanhã",uk:"до завтра"}],["compound-prepositions","prepositions-overview"]),
p("verb-preposition","verb-preposition","Дієслово + прийменник","Verbo e preposição","Verb + preposition","Керування дієслів.","Деякі дієслова вибирають прийменник як частину своєї валентної моделі: gostar de, assistir a у нормативній моделі, precisar de. Український переклад не гарантує той самий прийменник.","Запам'ятовуйте дієслово разом із його моделлю.",[{pt:"Gosto de música.",uk:"Я люблю музику."},{pt:"Preciso de ajuda.",uk:"Мені потрібна допомога."}],["government-overview","valency-overview"]),
p("compound-prepositions","compound","Складені прийменники","Locuções prepositivas","Compound prepositions","de acordo com, por causa de, apesar de та інші.","Складені прийменники функціонують як одна прийменникова рамка, хоча графічно складаються з кількох слів.","Їхня семантика часто не дорівнює сумі окремих слів.",[{pt:"por causa da chuva",uk:"через дощ"},{pt:"de acordo com a lei",uk:"відповідно до закону"}],["prep-other","subordinating"])
];