import type { GrammarPage } from "../types";
const p=(id:string,slug:string,t:string,pt:string,en:string,s:string,i:string,teachingNote:string,e:GrammarPage["examples"],r:string[]=[]):GrammarPage=>({id,slug,category:"pronouns",titleUk:t,titlePt:pt,titleEn:en,summary:s,aliases:[t,slug],related:r,intro:teachingNote ? `${i}\n\n${teachingNote}` : i,examples:e});
export const pages:GrammarPage[]=[
p("personal-pronouns","personal","Особові займенники","Pronomes pessoais","Personal pronouns","Повні та короткі особові форми.","Особові займенники розрізняють особу, число та синтаксичну функцію. Система суб'єктних і об'єктних форм не збігається з українською один до одного.","Вивчайте форму разом із функцією: підмет, прямий або непрямий додаток.",[{pt:"Eu trabalho.",uk:"Я працюю."},{pt:"Ela falou comigo.",uk:"Вона говорила зі мною."}],["subject-pronouns","object-pronouns"]),
p("subject-pronouns","subject","Займенники-підмети","Pronomes sujeito","Subject pronouns","eu, tu, ele/ela, nós, vocês, eles/elas та варіанти звертання.","Особовий займенник-підмет часто опускається, але вживається для контрасту, уточнення або коли форма недостатня для ідентифікації.","Не перекладайте кожне українське «я/ти» окремим займенником.",[{pt:"Eu é que fiz.",uk:"Саме я це зробив/зробила."},{pt:"Nós chegámos cedo.",uk:"Ми прийшли рано."}],["null-subject","tu-voce"]),
p("tu-voce","tu-voce","tu і você","Tu e você","tu and você","Системи звертання та узгодження.","tu поєднується з формою 2-ї особи, você — з 3-ю. Розподіл між ними залежить від країни, регіону, покоління й соціальної ситуації.","В українській «ти/ви» не має прямої відповідності одному португальському займеннику.",[{pt:"Tu és muito gentil.",uk:"Ти дуже люб'язний/люб'язна.",variety:"PT"},{pt:"Você é muito gentil.",uk:"Ти / ви дуже люб'язні.",variety:"BR"}],["tu-voce-regional","politeness"]),
p("voces-vos","voces-vos","vocês і vós","Vocês e vós","vocês and vós","Множинні форми звертання.","vocês узгоджується як 3-тя особа множини. vós має обмежене сучасне вживання та зберігається в окремих релігійних, історичних, регіональних або стилістичних контекстах.","Не переносіть українське «ви» механічно на одну форму.",[{pt:"Vocês têm tempo?",uk:"У вас є час?"},{pt:"Vós sois testemunhas.",uk:"Ви є свідками.",register:"literary"}],["forms-of-address","tu-voce"]),
p("nos-a-gente","nos-a-gente","nós і a gente","Nós e a gente","nós and a gente","Ми: займенник і розмовна іменна конструкція.","nós керує 1-ю особою множини. a gente в сучасній мові часто функціонує як займенникова конструкція з 3-ю особою однини, особливо в PT-BR.","Не узгоджуйте a gente автоматично як nós: у стандартному вживанні a gente має форму 3-ї особи однини, хоча значення референта — «ми». Це стосується узгодження присудка; займенникове значення визначається контекстом.",[{pt:"A gente vai amanhã.",uk:"Ми підемо завтра.",variety:"BR"},{pt:"Nós vamos amanhã.",uk:"Ми підемо завтра."}],["agreement-sv","pt-br-pt-pt"]),
p("forms-of-address","forms-of-address","Форми звертання","Formas de tratamento","Forms of address","tu, você, o senhor, a senhora та інші форми.","Вибір форми звертання — граматичний і соціальний водночас. Значення você не однакове в усіх португаломовних спільнотах.","Оцінюйте форму разом із регістром і соціальною ситуацією.",[{pt:"O senhor pode entrar.",uk:"Ви можете увійти."},{pt:"A senhora deseja café?",uk:"Ви бажаєте кави?",register:"formal"}],["politeness","tu-voce"]),
p("object-pronouns","object-pronouns","Об'єктні займенники","Pronomes objeto","Object pronouns","Прямий і непрямий додаток.","Португальська розрізняє прямі об'єктні форми та форми, пов'язані з непрямим додатком. Їхня позиція також залежить від клитичної системи.","Функція дієслова важливіша за механічний переклад українського відмінка.",[{pt:"Vi-o ontem.",uk:"Я бачив його вчора."},{pt:"Disse-lhe a verdade.",uk:"Я сказав/сказала йому правду."}],["direct-object","indirect-object","clitic-pronouns"]),
p("direct-object","direct-object","Прямий додаток","Objeto direto","Direct object","Прямий об'єкт дієслова.","Прямий додаток відповідає аргументу, без якого деякі перехідні дієслова не мають повної інтерпретації. Його займенникова реалізація відрізняється від непрямого додатка.","Перевіряйте валентність конкретного дієслова.",[{pt:"Comprei o livro.",uk:"Я купив/купила книжку."},{pt:"Vi-o ontem.",uk:"Я бачив/бачила його вчора."}],["valency-overview","object-pronouns"]),
p("indirect-object","indirect-object","Непрямий додаток","Objeto indireto","Indirect object","Додаток, який часто вводиться прийменником або формою lhe.","Модель непрямого додатка залежить від керування дієслова. У португальській не кожен український давальний відповідає займеннику lhe.","Вивчайте дієслово разом із його прийменниковою моделлю.",[{pt:"Dei o livro ao João.",uk:"Я дав/дала книжку Жуану."},{pt:"Dei-lhe o livro.",uk:"Я дав/дала йому книжку."}],["government-overview","lhe-vs-o"]),
p("lhe-vs-o","lhe-vs-o","lhe та o/a","lhe e o/a","lhe vs o/a","Непрямий і прямий об'єктні займенники.","У стандартному описі `lhe` пов'язаний з непрямим додатком, а `o/a/os/as` — із прямим об'єктом. У розмовному мовленні, особливо в PT-BR, займенникова референція може реалізуватися інакше, тому не варто переносити формальний розподіл як повний опис усіх розмовних різновидів.","Не вибирайте займенник лише за українським «йому/його»: перевіряйте синтаксичну функцію.",[{pt:"Vi-o.",uk:"Я бачив його."},{pt:"Lhe telefonei.",uk:"Я йому зателефонував/зателефонувала."}],["direct-object","indirect-object","clitics-br-pt"]),
p("prepositional-pronouns","prepositional","Займенники після прийменників","Pronomes preposicionados","Prepositional pronouns","mim, ti, ele/ela, nós та конструкції після прийменника.","Після більшості прийменників використовуються спеціальні форми: para mim, de ti, com ele. Прийменник com має лексикалізовані форми comigo, contigo, consigo тощо.","Не використовуйте суб'єктні форми після кожного прийменника.",[{pt:"Isto é para mim.",uk:"Це для мене."},{pt:"Fala comigo.",uk:"Поговори зі мною."}],["prep-pronoun-contr","prepositions-overview"]),
p("reflexive-pronouns","reflexive","Зворотні займенники","Pronomes reflexos","Reflexive pronouns","se, me, te, nos, vos та зворотна інтерпретація.","Зворотність — одна з функцій клитичної системи. Форма se може бути також взаємною, безособовою, пасивною або частиною лексикалізованого дієслова.","Спочатку визначайте функцію se, а не називайте його завжди «зворотним».",[{pt:"Ele lavou-se.",uk:"Він помився.",variety:"PT"},{pt:"Eles abraçaram-se.",uk:"Вони обійнялися."}],["se-reflexive","se-reciprocal","se-overview"]),
p("demonstratives","demonstratives","Вказівні займенники","Demonstrativos","Demonstratives","este, esse, aquele та пов'язані форми.","Вказівні можуть кодувати дейксис, дискурсивну відстань або контраст. Система й фактична частотність різняться між PT-BR і PT-PT.","Не перекладайте кожне este/esse одним сталим українським словом.",[{pt:"este livro",uk:"ця книжка"},{pt:"aquele dia",uk:"той день"}],["reference-overview","determiners-overview"]),
p("possessives","possessives","Присвійні форми","Possessivos","Possessives","meu, teu, seu, nosso, vosso та узгодження.","Присвійні узгоджуються з предметом володіння, а не з особою власника: minha casa, meus livros. В окремих різновидах артикль перед присвійним має різну частотність.","Розрізняйте граматичну форму власника та рід/число предмета.",[{pt:"minha casa",uk:"мій будинок / моя оселя"},{pt:"meus livros",uk:"мої книжки"}],["articles-possessives","determiners-agreement"]),
p("indefinites","indefinites","Неозначені займенники","Pronomes indefinidos","Indefinite pronouns","algum, nenhum, alguém, ninguém, tudo, nada та інші.","Неозначені форми квантифікують або посилаються на невизначений референт. Вони мають власні правила роду, числа та заперечення.","Розрізняйте займенник і детермінатив: algum livro та alguém não є однією конструкцією.",[{pt:"Alguém chegou.",uk:"Хтось прийшов."},{pt:"Ninguém respondeu.",uk:"Ніхто не відповів."}],["quantifiers-overview","negation-ninguem"]),
p("interrogative-pronouns","interrogatives","Питальні займенники","Pronomes interrogativos","Interrogative pronouns","quem, o que, qual, quanto та їхні конструкції.","Питальна форма залежить від того, чи запитується про особу, предмет, вибір із множини або кількість. Прийменник часто залишається перед займенником.","Не змішуйте o que та que як визначник перед іменником.",[{pt:"Quem chegou?",uk:"Хто прийшов?"},{pt:"Qual preferes?",uk:"Який ти обираєш?"},{pt:"Quanto custa?",uk:"Скільки коштує?"}],["wh-questions","questions-yesno"]),
p("relative-pronouns","relatives","Відносні займенники","Pronomes relativos","Relative pronouns","que, quem, o qual, cujo, onde та їхні функції.","Відносний займенник зв'язує підрядне речення з антецедентом. Вибір форми залежить від ролі в підрядному та від прийменникового керування.","Окремо вивчайте функцію, прийменник і тип антецедента. Прийменник належить до синтаксичної рамки підрядного: de quem falei, але com quem trabalho.",[{pt:"A pessoa que chegou.",uk:"Людина, яка прийшла."},{pt:"A cidade onde vivo.",uk:"Місто, де я живу."},{pt:"A pessoa que vi ontem.",uk:"Людина, яку я бачив/бачила вчора."},{pt:"A pessoa de quem falei ontem.",uk:"Людина, про яку я говорив/говорила вчора."}],["relative-que","relative-quem","relative-onde"])
];