import type { GrammarPage } from "../types";
const p=(id:string,slug:string,t:string,pt:string,en:string,s:string,i:string,e:GrammarPage["examples"],r:string[]=[]):GrammarPage=>({id,slug,category:"relative",titleUk:t,titlePt:pt,titleEn:en,summary:s,aliases:[t,slug],related:r,intro:i,examples:e});
export const pages:GrammarPage[]=[
p("relative-que","que","Відносний que","Pronome relativo que","Relative que","Найчастотніший відносний елемент.","que може виконувати роль підмета або додатка у відносному реченні. Якщо дієслово вимагає прийменника, прийменник може передувати que у формальному стилі.","Функцію que визначайте всередині підрядного, а не лише за перекладом «який».",[{pt:"O livro que comprei.",uk:"Книжка, яку я купив/купила."},{pt:"A pessoa que chegou.",uk:"Людина, яка прийшла."}],["relative-pronouns","advanced-relatives"]),
p("relative-quem","quem","Відносний quem","Pronome relativo quem","Relative quem","Відносні конструкції про осіб.","quem використовується з антецедентами-особами та особливо природний після прийменника: a pessoa com quem falei.","Не замінюйте quem на que без урахування ролі та прийменника.",[{pt:"A pessoa com quem falei.",uk:"Людина, з якою я говорив/говорила."}],["relative-pronouns","prep-com"]),
p("relative-o-qual","o-qual","o qual та варіанти","o qual e variantes","o qual relatives","Формальні та уточнювальні відносні форми.","o qual, a qual, os quais, as quais узгоджуються з антецедентом і особливо корисні після прийменників або там, де потрібно уникнути неоднозначності.","Форма не є просто «більш правильною» версією que: вона має інший розподіл.",[{pt:"A razão pela qual saí.",uk:"Причина, через яку я пішов/пішла."}],["relative-que","advanced-relatives","prep-por"]),
p("relative-cujo","cujo","cujo","Cujo","whose relative","Присвійний відносний займенник.","cujo означає відношення належності та узгоджується з наступним іменником: o autor cujo livro li. Після cujo артикль не ставиться.","Не перекладайте cujo як буквальне окреме «чий» у всіх контекстах.",[{pt:"O autor cujo livro li.",uk:"Автор, книжку якого я прочитав/прочитала."}],["relative-pronouns","articles-definite"]),
p("relative-onde","onde","Відносне onde","Onde relativo","Relative onde","Місце як антецедент.","onde вводить відносну конструкцію з локативним значенням. У частині контекстів можливі em que та no qual.","Вибір форми залежить від семантики місця та стилю.",[{pt:"A cidade onde vivo.",uk:"Місто, де я живу."},{pt:"A cidade em que vivo.",uk:"Місто, у якому я живу."}],["relative-pronouns","prep-em"]),
p("relative-restrictive","restrictive","Обмежувальні й пояснювальні відносні","Relativas restritivas e explicativas","Restrictive vs non-restrictive relatives","Кома змінює спосіб прив'язки інформації до іменника.","Обмежувальна відносна частина допомагає ідентифікувати підмножину; пояснювальна додає побічну інформацію й виділяється пунктуацією. Інтерпретація залежить від контексту.","Не ставте кому лише за аналогією з українським перекладом.",[{pt:"Os alunos que estudaram passaram.",uk:"Учні, які вчилися, склали іспит."},{pt:"O João, que estudou muito, passou.",uk:"Жуан, який багато вчився, склав іспит."}],["punctuation","advanced-relatives"])
];