import type { GrammarPage } from "../types";
const p=(id:string,slug:string,titleUk:string,titlePt:string,titleEn:string,summary:string,intro:string,examples:GrammarPage["examples"],related:string[]=[]):GrammarPage=>({id,slug,category:"spelling",titleUk,titlePt,titleEn,summary,aliases:[titleUk,slug],related,intro,examples,markers:[],mistakes:[]});
export const pages:GrammarPage[]=[
p("alphabet","alphabet","Алфавіт і назви літер","Alfabeto","Alphabet","Літери, диграфи й назви графем.","Португальська використовує латинку. Важливо відрізняти назву літери від її звукової реалізації: ` h ` самостійно зазвичай не позначає звук, а ` ch, lh, nh ` — диграфи.","Вимова залежить від позиції, слова та різновиду португальської.",[{pt:"chave",uk:"ключ"},{pt:"filho",uk:"син"},{pt:"vinho",uk:"вино"}],["reading-rules","phonetics-overview"]),
p("reading-rules","reading-rules","Правила читання","Regras de leitura","Reading rules","Базові відповідності графем і вимови.","Читання залежить від позиції та сусідніх літер: ` c ` перед ` e/i ` відрізняється від ` c ` перед ` a/o/u `, а ` g ` перед ` e/i ` — від ` g ` перед ` a/o/u `. Це правила орфографії, а не універсальна фонетична транскрипція.","Не виводьте вимову слова лише з однієї літери: наголос, позиція складу та різновид можуть змінювати реалізацію.",[{pt:"casa",uk:"дім"},{pt:"cidade",uk:"місто"},{pt:"gente",uk:"люди"}],["alphabet","phonetics-overview","stress"]),
p("stress","stress","Наголос і правила його позначення","Acentuação tónica","Stress","Наголошений склад і графічний акцент.","Графічний акцент не дорівнює самому словесному наголосу: наголос є властивістю слова, а ` á, é, í, ó, ú `, ` â, ê, ô ` тощо лише позначають його в певних орфографічних умовах.","Перевіряйте наголос слова разом із його нормативним написанням.",[{pt:"café",uk:"кава"},{pt:"médico",uk:"лікар"},{pt:"telefone",uk:"телефон"}],["diacritics","stress-phonology"]),
p("diacritics","diacritics","Діакритичні знаки","Acentos e sinais diacríticos","Diacritics","Графічні знаки, що розрізняють вимову або наголос.","Гострий, циркумфлекс і тильда виконують різні функції. ` ã ` та ` õ ` позначають назалізацію; ` é/ê ` і ` ó/ô ` можуть розрізняти відкритість голосного.","Не називайте кожен знак просто наголосом: тильда має окрему фонетико-орфографічну функцію.",[{pt:"avó / avô",uk:"бабуся / дідусь"},{pt:"nação",uk:"нація"},{pt:"você",uk:"ти / ви — залежно від контексту"}],["stress","phonetics-overview","nasal-vowels"]),
p("homograph-accents","homograph-accents","Акцент як розрізнення омографів","Acento distintivo","Distinguishing accents","Випадки, де діакритика допомагає розрізнити форми.","Сучасна орфографія зберігає окремі графічні розрізнення, але не кожна пара омографів має акцент. Вивчайте конкретні нормативні пари.","Приклад ` pôr ` розрізняється від ` por `; це окремий випадок орфографічної норми.",[{pt:"Vou pôr o livro aqui.",uk:"Я покладу книжку сюди."},{pt:"Passei por Lisboa.",uk:"Я проїхав/проїхала через Лісабон."}],["diacritics","acordo-ortografico"]),
p("capitalization","capitalization","Великі літери","Maiúsculas","Capitalization","Власні назви, початок речення й офіційні назви.","Великі літери в португальській не копіюють українські механічно. Назви місяців і днів тижня зазвичай пишуться з малої: ` segunda-feira `, ` maio `.","Офіційні назви можуть мати власні конвенції.",[{pt:"segunda-feira",uk:"понеділок"},{pt:"maio",uk:"травень"},{pt:"Portugal",uk:"Португалія"}],["punctuation","acordo-ortografico"]),
p("punctuation","punctuation","Пунктуація","Pontuação","Punctuation","Коми, двокрапка, тире й лапки в португальському тексті.","Пунктуація частково перетинається з синтаксисом: кома не ставиться просто там, де україномовний читач робить паузу. Особливо важливі межі підрядних і вставних конструкцій.","Порівнюйте структуру речення, а не лише інтонаційну паузу української.",[{pt:"Quando cheguei, ele saiu.",uk:"Коли я прийшов/прийшла, він вийшов."},{pt:"João, vem cá.",uk:"Жуане, йди сюди."}],["word-order","subordinating","acordo-ortografico"]),
p("acordo-ortografico","acordo-ortografico","Acordo Ortográfico 1990","Acordo Ortográfico","Orthographic Agreement","Основні наслідки орфографічної угоди 1990 року.","Угода уніфікувала частину написань, але не усунула всіх відмінностей між різновидами португальської. Вимова, лексика й частина графічних відмінностей залишаються варіативними.","Не трактуйте Acordo Ortográfico як повне злиття PT-BR і PT-PT.",[{pt:"ação",uk:"дія"},{pt:"facto / fato",uk:"факт — варіанти за різновидом"}],["spelling-br-pt","diacritics"]),
p("spelling-br-pt","spelling-br-pt","Орфографічні відмінності PT-BR і PT-PT","Ortografia BR e PT","BR vs PT spelling","Написання, що може відрізнятися між Бразилією та Португалією.","Частина відмінностей пов'язана з тим, чи вимовляється приголосний: ` facto / fato `, ` receção / recepção ` залежно від норми та слова. Не кожна різниця є універсальною для всіх країн.","Позначайте різновид у словнику або прикладі, якщо написання змінюється.",[{pt:"facto",uk:"факт",variety:"PT"},{pt:"fato",uk:"факт",variety:"BR"},{pt:"receção",uk:"прийом / рецепція",variety:"PT"}],["acordo-ortografico","pt-br-pt-pt"])
];