import type { GrammarPage } from "../types";
const p=(id:string,slug:string,t:string,pt:string,en:string,s:string,i:string,e:GrammarPage["examples"],r:string[]=[]):GrammarPage=>({id,slug,category:"subordinate",titleUk:t,titlePt:pt,titleEn:en,summary:s,aliases:[t,slug],related:r,intro:i,examples:e});
export const pages:GrammarPage[]=[
p("complement-clauses","complement","Підрядні додаткові речення","Orações completivas","Complement clauses","Речення, що заповнюють валентність предиката.","Підрядне може бути аргументом дієслова, прикметника або іменника. Вибір indicativo, conjuntivo чи infinitivo залежить від значення й конструкції.","Не визначайте спосіб лише за наявністю сполучника que.",[{pt:"Sei que ele vem.",uk:"Я знаю, що він прийде."},{pt:"Quero que ele venha.",uk:"Я хочу, щоб він прийшов."}],["indicative-vs-subjunctive","infinitive-vs-subjunctive"]),
p("causal-clauses","causal","Причинові підрядні","Orações causais","Causal clauses","porque, como, visto que та інші причинні зв'язки.","Причинові сполучники пояснюють причину ситуації. Вибір форми залежить від інформаційної структури та регістру.","Розрізняйте причину й наслідок.",[{pt:"Fiquei em casa porque chovia.",uk:"Я залишився/лишилася вдома, бо йшов дощ."}],["porque-forms","subordinating"]),
p("purpose-clauses","purpose","Мета","Orações finais","Purpose clauses","para que та конструкції з infinitivo.","Мета часто виражається para + infinitivo, якщо суб'єкт контролює обидві дії, або para que + conjuntivo, коли підрядне має окремий суб'єкт.","Не перетворюйте різницю суб'єкта на механічне правило без урахування контролю.",[{pt:"Estudo para aprender.",uk:"Я вчуся, щоб навчитися."},{pt:"Estudo para que os meus pais fiquem tranquilos.",uk:"Я вчуся, щоб мої батьки були спокійні."}],["infinitive-vs-subjunctive","prep-para"]),
p("conditional-clauses","conditional-clauses","Умовні речення","Orações condicionais","Conditional clauses","se та інші умови.","Умовні конструкції поєднують різні часи й способи залежно від типу умови. Реальна, відкрита, гіпотетична та нереальна інтерпретації не зводяться до однієї таблиці.","Особливо важливі futuro do conjuntivo, imperfeito do conjuntivo та condicional.",[{pt:"Se tiver tempo, vou.",uk:"Якщо матиму час, піду."},{pt:"Se tivesse tempo, iria.",uk:"Якби я мав/мала час, пішов/пішла б."}],["futuro-subjuntivo","conditional-clauses","imperfeito-subjuntivo"]),
p("concessive-clauses","concessive","Допустові підрядні","Orações concessivas","Concessive clauses","embora, apesar de та інші конструкції.","Допустові конструкції виражають ситуацію, яка не усуває очікуваного наслідку. embora типово поєднується з conjuntivo; apesar de — з іменною або інфінітивною конструкцією.","Відрізняйте concessão від простої причини.",[{pt:"Embora esteja cansado, vou.",uk:"Хоча я втомлений, я піду."},{pt:"Apesar de estar cansado, vou.",uk:"Попри втому, я піду."}],["subjunctive-triggers","infinitive-prepositions"]),
p("temporal-clauses","temporal","Часові підрядні","Orações temporais","Temporal clauses","quando, enquanto, antes de, depois de та інші.","Часові конструкції співвідносять дві події. Вибір modo залежить від того, чи подія подається як фактична, повторювана, майбутня або залежна від умови.","Не переносіть український час без аналізу часової перспективи.",[{pt:"Quando cheguei, ele saiu.",uk:"Коли я прийшов/прийшла, він вийшов."},{pt:"Quando chegares, liga-me.",uk:"Коли прийдеш, подзвони мені."}],["futuro-subjuntivo","sequence-of-tenses"]),
p("consecutive-clauses","consecutive","Наслідкові підрядні","Orações consecutivas","Consecutive clauses","так що, настільки що та наслідок.","Конструкції nas consequências виражають результат або наслідок ступеня чи події. Важливо не плутати їх із причинними.","Зв'язок може бути explícito через tão/tanto + que.",[{pt:"Estava tão cansado que dormi.",uk:"Я був такий втомлений, що заснув."}],["subordinating","comparative-clauses"]),
p("comparative-clauses","comparative","Порівняльні підрядні","Orações comparativas","Comparative clauses","como, do que, quanto та порівняльні рамки.","Порівняльні конструкції можуть бути простими або містити ціле підрядне. Вибір зв'язки залежить від моделі порівняння.","Порівнюйте структуру, а не окремий сполучник.",[{pt:"Ele trabalha mais do que eu.",uk:"Він працює більше, ніж я."},{pt:"Tão rápido como antes.",uk:"Так само швидко, як раніше."}],["comparatives","subordinating"])
];