import type { GrammarPage } from "../types";
import { ex, mistake } from "../helpers";

export const pages: GrammarPage[] = [
  {
    id: "causative-constructions", slug: "causative", category: "syntax",
    titleUk: "Каузативні конструкції", titlePt: "Construções causativas", titleEn: "Causative constructions",
    summary: "Змусити, дозволити або організувати дію іншого: fazer, mandar, deixar та інші моделі.",
    aliases: ["каузатив","causative","causativo","fazer","mandar","deixar"],
    related: ["valency-overview","infinitive","clitics","complex-predicates"],
    intro: "Каузативна конструкція додає каузатора — учасника, який спричиняє або організовує дію іншого. У португальській різні дієслова кодують примус, дозвіл або організацію дії. Не всі моделі мають однаковий ступінь контролю.",
    formulas: [
      { label: "Примус / спричинення", pattern: "fazer + NP + Inf", note: "Каузатор спричиняє виконання дії." },
      { label: "Наказ", pattern: "mandar + NP + Inf", note: "mandar підкреслює наказ або доручення." },
      { label: "Дозвіл", pattern: "deixar + NP + Inf", note: "deixar може означати дозволяти комусь щось зробити." },
    ],
    examples: [
      ex("A professora fez os alunos repetir a frase.","Учителька змусила учнів повторити фразу."),
      ex("O chefe mandou o funcionário esperar.","Керівник наказав працівникові чекати."),
      ex("Os pais deixaram a criança brincar.","Батьки дозволили дитині гратися."),
    ],
    mistakes: [mistake("fazer = просто «робити» у всіх конструкціях","розрізняти просте fazer і каузативну модель","У конструкції fazer + NP + infinitivo fazer означає спричинення.")],
    ukrainian: "Українська має «змусити», «дозволити», «велiти», тому функція знайома. Але португальська часто пакує її в конструкцію з infinitivo.",
    brPt: "Основні каузативні моделі спільні. Клитики та порядок займенників можуть відрізнятися.",
  },
  {
    id: "raising-and-control", slug: "raising-control", category: "syntax",
    titleUk: "Raising і control: два типи інфінітивних конструкцій", titlePt: "Elevação e controlo", titleEn: "Raising and control",
    summary: "Чому parecer, querer, tentar та інші дієслова поводяться по-різному з інфінітивом.",
    aliases: ["raising","control","elevação","controlo","parecer","tentar","querer"],
    related: ["infinitive","causative-constructions","subject-placement","complement-clauses"],
    intro: "У поверхневій формі parecer + infinitivo і querer + infinitivo схожі, але синтаксично їхня структура різна. У control підмет головної клаузи контролює невиражений суб'єкт інфінітива: João tentou sair. У raising предикат верхнього рівня не додає нового агента до події: João parece estar cansado.",
    uses: [
      { title: "Control", body: "tentar, querer, decidir та подібні предикати мають семантичного учасника, який контролює дію інфінітива.", examples: [ex("A Maria tentou sair.","Марія спробувала вийти."),ex("O João decidiu estudar.","Жуан вирішив учитися.")] },
      { title: "Raising", body: "parecer подає властивість або враження щодо підмета інфінітивної події.", examples: [ex("O João parece estar cansado.","Здається, Жуан утомлений."),ex("Parece haver um problema.","Здається, є проблема.")] },
    ],
    mistakes: [mistake("аналізувати parecer як звичайне «хотіти/намагатися»","розрізняти семантичного контролера і піднятий аргумент","parecer не означає, що суб'єкт «робить» parecer.")],
    ukrainian: "Українська передає ці відмінності словами «здаватися», «намагатися», «вирішити», але інфінітивна структура не збігається один до одного.",
  },
  {
    id: "nominalization", slug: "nominalization", category: "syntax",
    titleUk: "Номіналізація: коли дія стає іменником", titlePt: "Nominalização", titleEn: "Nominalization",
    summary: "formação, crescimento, decisão та перетворення предикативної структури на іменну.",
    aliases: ["номіналізація","nominalization","nominalização","віддієслівний іменник"],
    related: ["word-formation-affixes","valency-overview","relative","complement-clauses"],
    intro: "Номіналізація перетворює подію, стан або властивість на іменну структуру. Це не лише словотвір: разом зі словом змінюється синтаксична організація. Formação do projeto відповідає за функцією ao projeto na frase em que alguém forma o projeto, але не має тієї самої граматичної структури.",
    examples: [
      ex("A construção da ponte demorou dois anos.","Будівництво мосту тривало два роки."),
      ex("A decisão de sair foi difícil.","Рішення піти було складним."),
      ex("O crescimento da cidade continua.","Зростання міста триває."),
      ex("É importante que ele venha.","Важливо, щоб він прийшов.",{ note: "Клауза зберігає предикативну структуру; це не номіналізація." }),
    ],
    mistakes: [mistake("вважати qualquer V → N механічним правилом","вчити лексему разом із моделлю доповнення","Суфікс і керування номіналізованого іменника не завжди передбачувані.")],
    ukrainian: "Українська активно номіналізує дієслова, але керування може змінюватися: «вирішити щось» → «рішення чогось/щодо чогось». У португальській також треба вивчати модель.",
  },
  {
    id: "advanced-relatives", slug: "advanced-relatives", category: "syntax",
    titleUk: "Складні відносні речення", titlePt: "Orações relativas avançadas", titleEn: "Advanced relative clauses",
    summary: "Restrictive/non-restrictive, прийменник + relative, cujo, o que та вибір форми.",
    aliases: ["складні відносні","advanced relatives","orações relativas","cujo","o que"],
    related: ["relative","prepositions","articles-definite","subordinate"],
    intro: "Відносне речення може обмежувати множину референтів або додавати коментар до вже ідентифікованого референта. Від цього залежить пунктуація та інтерпретація. У складніших моделях важливі прийменник + відносний займенник, cujo та o que.",
    uses: [
      { title: "Обмежувальне", body: "Визначає, про яких саме членів множини йдеться.", examples: [ex("Os alunos que estudaram passaram.","Студенти, які вчилися, склали іспит.")] },
      { title: "Пояснювальне", body: "Додає інформацію про вже визначений референт і виділяється комами.", examples: [ex("A Ana, que mora em Lisboa, chegou ontem.","Ана, яка живе в Лісабоні, приїхала вчора.")] },
      { title: "Прийменник + relative", body: "Прийменник залежить від функції відносного компонента.", examples: [ex("A pessoa com quem falei chegou.","Людина, з якою я говорив/говорила, прийшла."),ex("O assunto de que falámos era importante.","Тема, про яку ми говорили, була важливою.")] },
      { title: "cujo", body: "cujo виражає належність і узгоджується з наступним іменником.", examples: [ex("O autor cujo livro li vive aqui.","Автор, чию книжку я прочитав/прочитала, живе тут.")] },
    ],
    mistakes: [mistake("O livro que falei sobre","O livro de que falei / sobre o qual falei","Прийменник не можна випадково залишити після дієслова, якщо модель вимагає його перед relative."),mistake("вважати кому факультативною завжди","визначати restrictive vs non-restrictive","Кома змінює структуру та інтерпретацію.")],
    ukrainian: "Українська також має обмежувальні та пояснювальні відносні речення. Особлива увага потрібна до португальських прийменникових моделей.",
  },
  {
    id: "complex-predicates", slug: "complex-predicates", category: "syntax",
    titleUk: "Складені предикати й аналітичні конструкції", titlePt: "Predicados complexos", titleEn: "Complex predicates",
    summary: "Допоміжні, модальні, фазові та каузативні компоненти одного предиката.",
    aliases: ["складений предикат","complex predicate","predicado complexo","перифраза"],
    related: ["periphrases","causative-constructions","aspect-overview","modality-overview"],
    intro: "У португальській кілька дієслів можуть спільно утворювати один предикативний комплекс: estar a trabalhar, ter de sair, começar a chover, fazer alguém rir. Для читача важливо відрізняти лексичне дієслово від допоміжного, модального або фазового компонента.",
    examples: [
      ex("Estou a trabalhar.","Я зараз працюю.",{ variety: "PT" }),
      ex("Estou trabalhando.","Я зараз працюю.",{ variety: "BR" }),
      ex("Tenho de sair.","Я мушу піти."),
      ex("Começou a chover.","Почався дощ / почало дощити."),
      ex("Ela fez-me rir.","Вона змусила мене сміятися."),
    ],
    mistakes: [mistake("перекладати кожне дієслово окремо","визначати, чи утворюють дієслова єдиний предикативний комплекс","Допоміжне або фазове дієслово змінює граматичну інтерпретацію всього комплексу.")],
    brPt: "PT-BR частіше використовує конструкції з gerúndio, PT-PT — estar a + infinitivo. Інші перифрази мають власну регіональну частотність.",
  },
];