import type { GrammarPage } from "../types";
import { ex, mistake, page } from "../helpers";

export const pages: GrammarPage[] = [
  page({
    id: "tense-vs-ukrainian", slug: "tense-vs-ukrainian", category: "tenses",
    titleUk: "Португальські часи та український вид",
    titlePt: "Tempos verbais e o ucraniano", titleEn: "Portuguese tense vs Ukrainian aspect",
    summary: "Чому португальський час не можна перекладати українським доконаним/недоконаним видом один до одного.",
    aliases: ["часи й вид","tense vs aspect","tempos verbais","вид українською"],
    related: ["tense-aspect","perfeito-vs-imperfeito","preterito-perfeito","preterito-imperfeito","aspect-overview"],
    status:"draft",origin:"handwritten",depth:"high",ukrainianContrast:"high",
    intro:"Українська граматика виразно протиставляє доконаний і недоконаний вид. У португальській pretérito perfeito і imperfeito не є прямою парою «доконаний/недоконаний». Вони організують часову та аспектуальну перспективу по-різному, тому переклад треба будувати від ситуації, а не від назви часу.",
    definition:"Контраст португальських часів та українського виду — зіставлення двох різних способів структурувати час, завершеність, тривалість і фон події.",
    uses:[
      {title:"Подія як ціле",body:"Pretérito perfeito simple часто подає минулу подію як завершену в часовій рамці.",examples:[ex("Ontem comprei um livro.","Учора я купив/купила книжку.")]},
      {title:"Фон або стан",body:"Imperfecto часто описує стан, звичку або незавершену перспективу в минулому.",examples:[ex("Quando era criança, lia muito.","Коли я був/була дитиною, я багато читав/читала.")]},
      {title:"Український вид не є алгоритмом",body:"Один португальський час може перекладатися доконаним або недоконаним дієсловом залежно від контексту.",examples:[ex("Estava a ler quando ele chegou.","Я читав/читала, коли він прийшов.")]}
    ],
    examples:[ex("Fui ao mercado e comprei pão.","Я пішов/пішла на ринок і купив/купила хліб."),ex("Ia ao mercado todos os sábados.","Я ходив/ходила на ринок щосуботи.")],
    mistakes:[mistake("вибирати perfeito = доконаний, imperfeito = недоконаний","аналізувати часову рамку та перспективу події","Назви португальських часів не є перекладами українських видових категорій.","predicted-l1-transfer","high")],
    ukrainian:"Український вид — сильна граматична підказка, але вона не повинна замінювати аналіз португальського часу. Особливо обережно працюйте з imperfeito, станами та звичками.",
    regional:"Базовий контраст часів спільний; перифрастичні моделі та деякі частотні переваги можуть відрізнятися між BR і PT.",
  }),
  page({
    id:"sequence-of-tenses",slug:"sequence-of-tenses",category:"tenses",
    titleUk:"Узгодження часів",titlePt:"Concordância dos tempos",titleEn:"Sequence of tenses",
    summary:"Як час підрядної частини співвідноситься з часом головної.",
    aliases:["узгодження часів","sequence of tenses","concordância dos tempos"],
    related:["compound-clauses","reported-speech","tense-aspect","indicative-vs-subjunctive"],
    status:"draft",origin:"handwritten",depth:"high",ukrainianContrast:"medium",
    intro:"Час у підрядній частині не завжди механічно копіює час головного дієслова. Треба розрізняти одночасність, попередність і наступність щодо точки відліку та враховувати тип підрядної конструкції.",
    definition:"Узгодження часів — взаємодія часових форм головної та залежної частин для вираження їхнього часового співвідношення.",
    uses:[
      {title:"Одночасність",body:"Подія або стан підрядної частини може бути одночасним із точкою відліку.",examples:[ex("Disse que estava cansado.","Я сказав/сказала, що був/була втомлений/втомлена.")]},
      {title:"Попередність",body:"Для події, що передує точці відліку, використовують відповідну минулу або складену форму.",examples:[ex("Disse que já tinha saído.","Я сказав/сказала, що вже пішов/пішла.")]}
    ],
    examples:[ex("Acho que ele vem.","Думаю, що він прийде."),ex("Achei que ele vinha.","Я думав/думала, що він прийде.")],
    mistakes:[mistake("копіювати український час без визначення точки відліку","визначати співвідношення часу між двома подіями","Одна українська форма може відповідати різним португальським часовим перспективам.","predicted-l1-transfer","medium")],
    ukrainian:"Українська теж виражає часові співвідношення, але не має тотожної системи португальських форм. Корисно спочатку встановити точку відліку, а потім вибирати форму.",
    regional:"Окремі розмовні моделі непрямої мови можуть варіюватися; приклади треба оцінювати разом із регістром.",
  }),
  page({
    id:"future-subjunctive",slug:"futuro-subjuntivo",category:"subordinate",
    titleUk:"Futuro do conjuntivo",titlePt:"Futuro do conjuntivo",titleEn:"Future subjunctive",
    summary:"Особлива форма conjuntivo для майбутніх умовних, часових та відносних конструкцій.",
    aliases:["futuro do conjuntivo","future subjunctive","майбутній кон'юнктив"],
    related:["subjunctive-overview","conditional-clauses","temporal-clauses","relative-restrictive"],
    status:"draft",origin:"handwritten",depth:"high",ukrainianContrast:"high",
    intro:"Futuro do conjuntivo — окрема португальська форма, яку не слід плутати з presente do conjuntivo. Вона особливо характерна для майбутніх умовних і деяких часових/відносних конструкцій: se vieres, quando chegares, quem quiser.",
    definition:"Futuro do conjuntivo — форма conjuntivo, що локалізує залежну ситуацію в майбутньому щодо точки відліку.",
    formulas:[{label:"Умова",pattern:"se + futuro do conjuntivo"},{label:"Час",pattern:"quando/logo que/assim que + futuro do conjuntivo"}],
    examples:[ex("Se tiveres tempo, liga-me.","Якщо матимеш час, зателефонуй мені."),ex("Quando chegares, avisa-me.","Коли приїдеш, дай мені знати.")],
    mistakes:[mistake("Se você venha amanhã...","Se você vier amanhã...","У майбутній відкритій умові потрібен futuro do conjuntivo, а не presente do conjuntivo.","predicted-l1-transfer","high"),mistake("плутати futuro do conjuntivo з futuro do indicativo","перевіряти синтаксичний тригер","Форма визначається конструкцією, а не лише значенням «майбутнє».","editorial","high")],
    ukrainian:"Українська не має окремої морфологічної форми з таким самим розподілом. Українське «якщо прийдеш» приховує португальську різницю між типами conjuntivo.",
    regional:"Форма є частиною стандартної граматики основних різновидів; частотність залежить від типу конструкції та каналу.",
  }),
  page({
    id:"se-passive",slug:"se-passive",category:"se",
    titleUk:"Пасивне se",titlePt:"Se apassivador",titleEn:"Passive se",
    summary:"Конструкція з se, де логічний об'єкт поводиться як підмет і визначає узгодження.",
    aliases:["пасивне se","se apassivador","passive se"],
    related:["se-overview","se-impersonal","se-middle","se-agreement","agreement-sv"],
    status:"draft",origin:"handwritten",depth:"high",ukrainianContrast:"high",
    intro:"У пасивній конструкції з se прямий об'єкт активної конструкції стає синтаксичним підметом іменної групи, а дієслово узгоджується з нею: Vendem-se casas. Це треба відрізняти від безособового se, де дієслово не має такого узгодження.",
    definition:"Пасивне se — конструкція, у якій se маркує пасивну інтерпретацію, а пацієнс займає підметову позицію та узгоджується з дієсловом.",
    uses:[
      {title:"Узгодження",body:"У множині дієслово узгоджується з іменною групою.",examples:[ex("Vendem-se casas.","Продаються будинки.")]},
      {title:"Порівняння з безособовим se",body:"Для діагностики перевіряйте, чи є група після дієслова узгоджуваним підметом.",examples:[ex("Procura-se um professor.","Шукають викладача.")]}
    ],
    examples:[ex("Alugam-se apartamentos.","Здаються квартири."),ex("Publicaram-se os resultados.","Результати опублікували / були опубліковані.")],
    mistakes:[mistake("Alugam-se apartamento","Alugam-se apartamentos","За пасивного se множинний пацієнс узгоджується з дієсловом.","predicted-l1-transfer","high"),mistake("називати всі se безособовими","визначати тип конструкції та узгодження","se має кілька граматичних функцій.","editorial","high")],
    ukrainian:"Українська має пасивні конструкції, але не має такого самого se-маркера. Тому переклад «продають / продаються» не завжди показує португальську синтаксичну структуру.",
    regional:"Конструкція належить до стандартної граматики, але реальна частотність і альтернативні безособові моделі можуть різнитися за різновидами.",
  }),
  page({
    id:"se-impersonal",slug:"se-impersonal",category:"se",
    titleUk:"Безособове se",titlePt:"Se impessoal",titleEn:"Impersonal se",
    summary:"se, яке не створює узгодження з конкретним пацієнсом і подає невизначеного агента.",
    aliases:["безособове se","se impessoal","impersonal se"],
    related:["se-overview","se-passive","se-middle","null-subject","agreement-sv"],
    status:"draft",origin:"handwritten",depth:"high",ukrainianContrast:"high",
    intro:"Безособове se використовують для невизначеного людського агента: Vive-se bem aqui. На відміну від пасивного se, конструкція не поводиться як звичайний пасив із пацієнсом-підметом та узгодженням.",
    definition:"Безособове se — маркер конструкції з невираженим або невизначеним людським агентом.",
    examples:[ex("Vive-se bem nesta cidade.","У цьому місті добре живеться."),ex("Trabalha-se muito aqui.","Тут багато працюють.")],
    mistakes:[mistake("вважати se impessoal пасивним за замовчуванням","перевіряти тип предиката й узгодження","Безособове se та пасивне se мають різну синтаксичну поведінку.","predicted-l1-transfer","high")],
    ukrainian:"Українські безособові та неозначено-особові конструкції можуть передавати близький зміст, але не мають того самого se.",
    regional:"Конкретні діагностики й альтернативні моделі варто перевіряти для цільового різновиду.",
  })
];
