import type { GrammarPage } from "../types";
const p=(id:string,slug:string,t:string,pt:string,en:string,s:string,i:string,teachingNote:string,e:GrammarPage["examples"],r:string[]=[]):GrammarPage=>({id,slug,category:"verbs",titleUk:t,titlePt:pt,titleEn:en,summary:s,aliases:[t,slug],related:r,intro:teachingNote ? `${i}\n\n${teachingNote}` : i,examples:e});
export const pages:GrammarPage[]=[
p("verb-system","system","Дієслівна система","Sistema verbal","Verb system","Особа, час, спосіб і перифрази.","Португальське дієслово кодує особу, число, час, спосіб та інші граматичні значення. Частина значень виражається аналітично.","Не вчіть форми лише як таблицю: пов'язуйте їх із синтаксичною функцією.",[{pt:"eu falo",uk:"я говорю"},{pt:"nós falámos",uk:"ми говорили / поговорили",variety:"PT"}],["verb-system","subjunctive-overview","ir-infinitive"]),
p("regular-ar","regular-ar","Регулярні дієслова на -ar","Verbos regulares em -ar","Regular -ar verbs","Модель falar та інших дієслів.","Дієслова на -ar утворюють регулярні особові форми за типовою парадигмою, хоча окремі орфографічні чергування мають свої правила.","Вивчайте основу та закінчення окремо.",[{pt:"falo, falas, fala",uk:"говорю, говориш, говорить"},{pt:"falamos",uk:"ми говоримо"}],["verb-system","presente"]),
p("regular-er","regular-er","Регулярні дієслова на -er","Verbos regulares em -er","Regular -er verbs","Модель comer.","Дієслова на -er мають іншу парадигму закінчень, але принцип виділення основи та закінчення той самий.","Порівнюйте comer з falar, не виводячи одну модель з іншої.",[{pt:"como, comes, come",uk:"їм, їси, їсть"}],["verb-system","presente"]),
p("regular-ir","regular-ir","Регулярні дієслова на -ir","Verbos regulares em -ir","Regular -ir verbs","Модель abrir.","Дієслова на -ir мають власні закінчення в частині часів і способів, хоча багато форм близькі до -er.","Вивчайте повну парадигму, якщо дієслово частотне.",[{pt:"abro, abres, abre",uk:"відкриваю, відкриваєш, відкриває"}],["verb-system","presente"]),
p("stem-changing","stem-changing","Чергуються голосні в основі","Alternâncias do radical","Stem-changing verbs","Нерегулярність основи.","Частина дієслів має чергування голосних або інші зміни основи в окремих формах. Це не одна універсальна модель.","Запам'ятовуйте групу форм конкретного дієслова.",[{pt:"poder → posso",uk:"могти → можу"},{pt:"fazer → faço",uk:"робити → роблю"}],["irregular-verbs","spelling-changing"]),
p("spelling-changing","spelling-changing","Орфографічні зміни основи","Alterações ortográficas","Spelling-changing verbs","Зміни написання для збереження вимови.","Деякі дієслова змінюють написання перед певними закінченнями, щоб зберегти звукове значення основи.","Це орфографічна, а не завжди морфологічно нерегулярна зміна.",[{pt:"ficar → fiquei",uk:"залишатися → залишився/лася"},{pt:"pagar → paguei",uk:"платити → заплатив/ла"}],["reading-rules","acordo-ortografico"]),
p("irregular-verbs","irregular","Нерегулярні дієслова","Verbos irregulares","Irregular verbs","ser, estar, ter, fazer, dizer, ir та інші.","Нерегулярні дієслова мають форми, які не виводяться лише з регулярної моделі. Найчастотніші варто вчити першими як парадигми.","Нерегулярність часто локальна: одне дієслово може мати регулярні форми в одних часах і нерегулярні в інших.",[{pt:"sou, és, é",uk:"є / являюся, єш, є",variety:"PT"},{pt:"vou, vais, vai",uk:"іду, йдеш, іде"}],["ser","estar","ir-vir"]),
p("ser","ser","ser","Ser","ser","Ідентифікація, класифікація та характеристики.","ser пов'язує підмет із іменною або прикметниковою характеристикою та бере участь у пасиві. Вибір ser/estar залежить від конструкції та значення, а не лише від простого правила «постійне/тимчасове».","Порівнюйте ser із estar у конкретних контекстах.",[{pt:"Ela é médica.",uk:"Вона лікарка."},{pt:"O livro é interessante.",uk:"Книжка цікава."}],["ser-estar","ser-passive"]),
p("estar","estar","estar","Estar","estar","Стан, місце та прогресивні конструкції.","estar бере участь у предикатах стану, локалізації та прогресивних конструкціях. Його значення залежить від лексичної рамки.","Не зводьте estar до українського «бути» без аналізу предиката.",[{pt:"Estou em casa.",uk:"Я вдома."},{pt:"Estou a estudar.",uk:"Я зараз навчаюся.",variety:"PT"}],["ser-estar","progressive-br-pt"]),
p("ficar","ficar","ficar","Ficar","ficar","Залишатися, ставати, перебувати в місці.","ficar має кілька пов'язаних, але різних значень: локалізація, залишення в стані, зміна стану та результативні конструкції.","Переклад «залишатися» не охоплює всі моделі.",[{pt:"Fico em casa.",uk:"Я залишаюся вдома."},{pt:"A porta ficou aberta.",uk:"Двері залишилися відчиненими."}],["ser-estar-ficar"]),
p("ser-estar","ser-estar","ser чи estar","Ser ou estar","ser vs estar","Контраст предикації та стану.","ser часто вводить класифікацію, ідентичність або характеристику; estar — стан, локалізацію чи інший контекстуальний предикат. Межі залежать від конструкції.","Не вчіть правило як абсолютну семантичну дихотомію.",[{pt:"Ele é brasileiro.",uk:"Він бразилець."},{pt:"Ele está cansado.",uk:"Він втомлений."}],["ser","estar"]),
p("ser-estar-ficar","ser-estar-ficar","ser, estar і ficar","Ser, estar e ficar","ser, estar and ficar","Три дієслова зв'язки та зміни стану.","ser, estar і ficar частково перетинаються, але мають різні валентні та семантичні рамки. ficar особливо важливий для результативних і локативних конструкцій.","Порівнюйте мінімальні контрасти в контексті.",[{pt:"A porta está aberta.",uk:"Двері відчинені."},{pt:"A porta ficou aberta.",uk:"Двері залишилися відчиненими."}],["ser-estar","ficar"]),
p("ter","ter","ter","Ter","ter","Володіння, стани та допоміжні конструкції.","ter виражає володіння та входить до багатьох сталих конструкцій і складених часових форм.","Перевіряйте, чи ter є повнозначним дієсловом, чи допоміжним.",[{pt:"Tenho um livro.",uk:"У мене є книжка."},{pt:"Tenho estudado muito.",uk:"Я багато вчуся останнім часом."}],["ter-haver","compound-tenses"]),
p("haver","haver","haver","Haver","haver","Екзистенційні та допоміжні конструкції.","haver може бути допоміжним дієсловом і входити до екзистенційної конструкції há. В екзистенційному значенні форма há не узгоджується з множиною.","Не змішуйте haver з ter у регіональних екзистенційних моделях.",[{pt:"Há muitas pessoas aqui.",uk:"Тут багато людей."},{pt:"Há dois problemas.",uk:"Є дві проблеми."}],["ter-haver","existential","agreement-sv"]),
p("ter-haver","ter-haver","ter чи haver","Ter ou haver","ter vs haver","Допоміжні та екзистенційні функції.","У сучасній португальській ter і haver мають різний розподіл. ter широко використовується як допоміжне в складених конструкціях, haver — в окремих книжних/складених і екзистенційних моделях.","Визначайте функцію перед вибором дієслова.",[{pt:"Tenho estudado.",uk:"Я навчався/навчалася останнім часом."},{pt:"Há problemas.",uk:"Є проблеми."}],["ter","haver"]),
p("gostar","gostar","gostar de","Gostar de","gostar de","Подобатися, любити та керування de.","gostar у стандартній моделі керує de: gostar de música, gostar de alguém. Це важливий приклад дієслівного керування.","Український переклад «любити» не підказує португальський прийменник.",[{pt:"Gosto de música.",uk:"Я люблю музику."},{pt:"Gosto deste livro.",uk:"Мені подобається ця книжка."}],["verb-preposition","government-overview"]),
p("saber-conhecer","saber-conhecer","saber і conhecer","Saber e conhecer","saber vs conhecer","Знати факт/уміння та бути знайомим із людиною/місцем.","saber часто стосується інформації або вміння, conhecer — знайомства з особою, місцем чи досвідом. Контекст визначає точний переклад.","Не перекладайте обидва дієслова одним українським «знати».",[{pt:"Sei a resposta.",uk:"Я знаю відповідь."},{pt:"Conheço Lisboa.",uk:"Я знаю Лісабон / знайомий із Лісабоном."}],["valency-overview"]),
p("levar-trazer","levar-trazer","levar і trazer","Levar e trazer","levar vs trazer","Рух відносно точки відліку.","levar зазвичай кодує перенесення від точки відліку, trazer — до неї або разом із нею. Поняття deictic center залежить від контексту.","Визначайте, де перебуває мовцева точка відліку.",[{pt:"Leva isto para casa.",uk:"Віднеси це додому."},{pt:"Traz o livro.",uk:"Принеси книжку."}],["ir-vir"]),
p("ir-vir","ir-vir","ir і vir","Ir e vir","ir vs vir","Йти/їхати від і до точки відліку.","ir позначає рух від деїктичного центру, vir — до нього. У непрямій мові точка відліку може змінюватися.","Контекст важливіший за сталий переклад «йти/приходити».",[{pt:"Vou para casa.",uk:"Я йду додому."},{pt:"Vem cá.",uk:"Іди сюди / приходь сюди."}],["levar-trazer","reference-overview"]),
p("poder-dever-querer","poder-dever-querer","poder, dever, querer","Poder, dever, querer","poder, dever, querer","Можливість, обов'язок і воля.","Ці дієслова формують модальні конструкції з інфінітивом. Їхня семантика залежить від часу, способу й контексту.","Порівнюйте dever як обов'язок і висновок та poder як можливість, дозвіл або ввічливе прохання.",[{pt:"Posso entrar?",uk:"Можна увійти?"},{pt:"Deves estudar.",uk:"Тобі слід вчитися."},{pt:"Quero sair.",uk:"Я хочу вийти."}],["modality-overview","infinitive-vs-subjunctive"]),
p("pronominal-verbs","pronominal","Зворотні та прономінальні дієслова","Verbos pronominais","Pronominal verbs","Дієслова з обов'язковою або лексичною займенниковою формою.","Частина дієслів уживається з clitic pronoun як частина лексичної моделі: lembrar-se, queixar-se тощо. Це не завжди просте зворотне значення.","Вивчайте дієслово разом із його займенниковою рамкою.",[{pt:"Lembro-me disso.",uk:"Я це пам'ятаю.",variety:"PT"},{pt:"Ele queixou-se.",uk:"Він поскаржився.",variety:"PT"}],["se-pronominal","clitic-placement"]),
p("por-verb","por-verb","Дієслово pôr і похідні","Pôr e derivados","pôr and derivatives","Нерегулярна модель pôr.","pôr має окрему парадигму та похідні типу propor, compor, impor. В орфографії його треба відрізняти від прийменника por.","Наголос і діакритика тут мають функціональне значення.",[{pt:"Vou pôr a mesa.",uk:"Я накрию на стіл."},{pt:"Ele põe o livro aqui.",uk:"Він кладе книжку сюди."}],["irregular-verbs","homograph-accents"])
];