import type { CategoryDef } from "./types";

export const CATEGORIES: CategoryDef[] = [
  {
    id: "fundamentals",
    slug: "fundamentals",
    titleUk: "Основи",
    titlePt: "Fundamentos",
    description: "Будова речення, частини мови, рід, число, регістри.",
    group: "core",
  },
  {
    id: "spelling",
    slug: "spelling",
    titleUk: "Орфографія і наголос",
    titlePt: "Ortografia",
    description: "Алфавіт, читання, діакритика, пунктуація, орфографічна угода.",
    group: "core",
  },
  {
    id: "phonetics",
    slug: "phonetics",
    titleUk: "Фонетика і вимова",
    titlePt: "Fonética e pronúncia",
    description: "Звукова система, голосні, носові голосні, приголосні, наголос і просодія.",
    group: "core",
  },
  {
    id: "determiners",
    slug: "determiners",
    titleUk: "Детермінативи і квантифікація",
    titlePt: "Determinantes e quantificação",
    description: "Артиклі як система, квантори, референція, сфера дії та узгодження.",
    group: "core",
  },
  {
    id: "valency",
    slug: "valency",
    titleUk: "Валентність і керування",
    titlePt: "Valência e regência",
    description: "Аргументна структура, керування дієслів і відмінність від вільних модифікаторів.",
    group: "syntax",
  },
  {
    id: "nouns",
    slug: "nouns",
    titleUk: "Іменники",
    titlePt: "Substantivos",
    description: "Рід, множина, складні іменники, зменшувальні форми.",
    group: "core",
  },
  {
    id: "articles",
    slug: "articles",
    titleUk: "Артиклі",
    titlePt: "Artigos",
    description: "Означений, неозначений і нульовий артикль; власні назви.",
    group: "core",
  },
  {
    id: "adjectives",
    slug: "adjectives",
    titleUk: "Прикметники",
    titlePt: "Adjetivos",
    description: "Узгодження, позиція, порівняння, суперлатив.",
    group: "core",
  },
  {
    id: "adverbs",
    slug: "adverbs",
    titleUk: "Прислівники",
    titlePt: "Advérbios",
    description: "Утворення на -mente, позиція, já / ainda / sempre.",
    group: "core",
  },
  {
    id: "pronouns",
    slug: "pronouns",
    titleUk: "Займенники",
    titlePt: "Pronomes",
    description: "Особові, об'єктні, вказівні, присвійні, відносні.",
    group: "core",
  },
  {
    id: "clitics",
    slug: "clitics",
    titleUk: "Клитики",
    titlePt: "Próclise e ênclise",
    description: "Colocação pronominal: próclise, ênclise, mesóclise.",
    group: "core",
  },
  {
    id: "numerals",
    slug: "numerals",
    titleUk: "Числівники",
    titlePt: "Numerais",
    description: "Кількісні, порядкові, дати й час.",
    group: "core",
  },
  {
    id: "prepositions",
    slug: "prepositions",
    titleUk: "Прийменники",
    titlePt: "Preposições",
    description: "a, de, em, por, para та керування дієслів.",
    group: "core",
  },
  {
    id: "contractions",
    slug: "contractions",
    titleUk: "Контракції",
    titlePt: "Contrações",
    description: "do, no, ao, pelo та контракції із займенниками.",
    group: "core",
  },
  {
    id: "crase",
    slug: "crase",
    titleUk: "Crase",
    titlePt: "Crase",
    description: "à, às, àquele: коли злиття a + a обов'язкове.",
    group: "core",
  },
  {
    id: "semantics",
    slug: "semantics",
    titleUk: "Семантика",
    titlePt: "Semântica",
    description: "Аспект, модальність, референція, визначеність і родові значення.",
    group: "ref",
  },
  {
    id: "pragmatics",
    slug: "pragmatics",
    titleUk: "Прагматика",
    titlePt: "Pragmática",
    description: "Мовленнєві акти, ввічливість, контекст, частки та регістри.",
    group: "ref",
  },
  {
    id: "discourse",
    slug: "discourse",
    titleUk: "Дискурс і текст",
    titlePt: "Discurso e texto",
    description: "Зв'язність, дискурсивні маркери, інформаційна структура та еліпсис.",
    group: "ref",
  },
  {
    id: "conjunctions",
    slug: "conjunctions",
    titleUk: "Сполучники",
    titlePt: "Conjunções",
    description: "Сурядні й підрядні сполучники, вибір способу.",
    group: "syntax",
  },
  {
    id: "verbs",
    slug: "verbs",
    titleUk: "Дієслова",
    titlePt: "Verbos",
    description: "Система дієслова, ser / estar / ficar, ter / haver.",
    group: "verb",
  },
  {
    id: "tenses",
    slug: "tenses",
    titleUk: "Часи індикатива",
    titlePt: "Tempos do indicativo",
    description: "Presente, pretéritos, futuro, condicional, аспект.",
    group: "verb",
  },
  {
    id: "moods",
    slug: "moods",
    titleUk: "Способи",
    titlePt: "Modos",
    description: "Conjuntivo / subjuntivo, імператив, логіка вибору.",
    group: "verb",
  },
  {
    id: "infinitive",
    slug: "infinitive",
    titleUk: "Інфінітив",
    titlePt: "Infinitivo",
    description: "Особовий і безособовий інфінітив, інфінітив vs кон'юнктив.",
    group: "verb",
  },
  {
    id: "gerund",
    slug: "gerund",
    titleUk: "Герундій і дієприкметник",
    titlePt: "Gerúndio e particípio",
    description: "Gerúndio, particípio, прогресив PT-BR / PT-PT.",
    group: "verb",
  },
  {
    id: "periphrases",
    slug: "periphrases",
    titleUk: "Перифрази",
    titlePt: "Perífrases",
    description: "ter de, acabar de, ir + infinitivo та інші.",
    group: "verb",
  },
  {
    id: "se",
    slug: "se",
    titleUk: "Конструкції з se",
    titlePt: "Construções com se",
    description: "Рефлексив, пасив, безособове se, узгодження.",
    group: "syntax",
  },
  {
    id: "syntax",
    slug: "syntax",
    titleUk: "Синтаксис",
    titlePt: "Sintaxe",
    description: "Порядок слів, емфаза, cleft, непряма мова.",
    group: "syntax",
  },
  {
    id: "negation",
    slug: "negation",
    titleUk: "Заперечення",
    titlePt: "Negação",
    description: "não, ninguém, nada, подвійне заперечення.",
    group: "syntax",
  },
  {
    id: "questions",
    slug: "questions",
    titleUk: "Питання",
    titlePt: "Interrogação",
    description: "Загальні й спеціальні питання, порядок слів.",
    group: "syntax",
  },
  {
    id: "agreement",
    slug: "agreement",
    titleUk: "Узгодження",
    titlePt: "Concordância",
    description: "Підмет–дієслово, іменник–прикметник, особливі випадки.",
    group: "syntax",
  },
  {
    id: "relative",
    slug: "relative",
    titleUk: "Відносні речення",
    titlePt: "Orações relativas",
    description: "que, quem, o qual, cujo, onde.",
    group: "syntax",
  },
  {
    id: "subordinate",
    slug: "subordinate",
    titleUk: "Підрядні речення",
    titlePt: "Orações subordinadas",
    description: "Умова, мета, причина, час, допустовість.",
    group: "syntax",
  },
  {
    id: "passive",
    slug: "passive",
    titleUk: "Пасив і безособові",
    titlePt: "Passiva e impessoal",
    description: "ser + particípio, há / tem, безособові конструкції.",
    group: "syntax",
  },
  {
    id: "word-formation",
    slug: "word-formation",
    titleUk: "Словотвір",
    titlePt: "Formação de palavras",
    description: "Префікси, суфікси, зменшувальні й збільшувальні.",
    group: "core",
  },
  {
    id: "regional",
    slug: "regional",
    titleUk: "Регіональні варіанти",
    titlePt: "Variedades",
    description: "PT-BR, PT-PT, африканські різновиди, форми звертання.",
    group: "ref",
  },
];

export const CATEGORY_BY_SLUG = Object.fromEntries(
  CATEGORIES.map((c) => [c.slug, c]),
) as Record<string, CategoryDef>;

export const GROUP_LABELS: Record<CategoryDef["group"], string> = {
  core: "Морфологія",
  verb: "Дієслово",
  syntax: "Синтаксис",
  ref: "Довідка",
};

export const TOP_NAV = [
  { href: "/pt", label: "Граматика" },
  { href: "/comparisons", label: "Порівняння" },
  { href: "/regional", label: "Варіанти" },
  { href: "/tables", label: "Таблиці" },
] as const;
