/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComparisonsRouteImport } from './routes/comparisons'
import { Route as PtRouteImport } from './routes/pt'
import { Route as RegionalRouteImport } from './routes/regional'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as ComparisonsIndexRouteImport } from './routes/comparisons.index'
import { Route as ComparisonsSlugRouteImport } from './routes/comparisons.$slug'
import { Route as PtIndexRouteImport } from './routes/pt.index'
import { Route as PtCategoryRouteImport } from './routes/pt.$category'
import { Route as RegionalIndexRouteImport } from './routes/regional.index'
import { Route as RegionalSlugRouteImport } from './routes/regional.$slug'
import { Route as TablesIndexRouteImport } from './routes/tables.index'
import { Route as PtCategoryIndexRouteImport } from './routes/pt.$category.index'
import { Route as PtCategorySlugRouteImport } from './routes/pt.$category.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonsRoute = ComparisonsRouteImport.update({
  id: '/comparisons',
  path: '/comparisons',
  getParentRoute: () => rootRouteImport,
} as any)
const PtRoute = PtRouteImport.update({
  id: '/pt',
  path: '/pt',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionalRoute = RegionalRouteImport.update({
  id: '/regional',
  path: '/regional',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonsIndexRoute = ComparisonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComparisonsRoute,
} as any)
const ComparisonsSlugRoute = ComparisonsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ComparisonsRoute,
} as any)
const PtIndexRoute = PtIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PtRoute,
} as any)
const PtCategoryRoute = PtCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => PtRoute,
} as any)
const RegionalIndexRoute = RegionalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegionalRoute,
} as any)
const RegionalSlugRoute = RegionalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RegionalRoute,
} as any)
const TablesIndexRoute = TablesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TablesRoute,
} as any)
const PtCategoryIndexRoute = PtCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PtCategoryRoute,
} as any)
const PtCategorySlugRoute = PtCategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PtCategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparisons': typeof ComparisonsRouteWithChildren
  '/pt': typeof PtRouteWithChildren
  '/regional': typeof RegionalRouteWithChildren
  '/search': typeof SearchRoute
  '/tables': typeof TablesRouteWithChildren
  '/comparisons/$slug': typeof ComparisonsSlugRoute
  '/pt/$category': typeof PtCategoryRouteWithChildren
  '/regional/$slug': typeof RegionalSlugRoute
  '/comparisons/': typeof ComparisonsIndexRoute
  '/pt/': typeof PtIndexRoute
  '/regional/': typeof RegionalIndexRoute
  '/tables/': typeof TablesIndexRoute
  '/pt/$category/$slug': typeof PtCategorySlugRoute
  '/pt/$category/': typeof PtCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/comparisons/$slug': typeof ComparisonsSlugRoute
  '/regional/$slug': typeof RegionalSlugRoute
  '/comparisons': typeof ComparisonsIndexRoute
  '/pt': typeof PtIndexRoute
  '/regional': typeof RegionalIndexRoute
  '/tables': typeof TablesIndexRoute
  '/pt/$category/$slug': typeof PtCategorySlugRoute
  '/pt/$category': typeof PtCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparisons': typeof ComparisonsRouteWithChildren
  '/pt': typeof PtRouteWithChildren
  '/regional': typeof RegionalRouteWithChildren
  '/search': typeof SearchRoute
  '/tables': typeof TablesRouteWithChildren
  '/comparisons/$slug': typeof ComparisonsSlugRoute
  '/pt/$category': typeof PtCategoryRouteWithChildren
  '/regional/$slug': typeof RegionalSlugRoute
  '/comparisons/': typeof ComparisonsIndexRoute
  '/pt/': typeof PtIndexRoute
  '/regional/': typeof RegionalIndexRoute
  '/tables/': typeof TablesIndexRoute
  '/pt/$category/$slug': typeof PtCategorySlugRoute
  '/pt/$category/': typeof PtCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comparisons'
    | '/pt'
    | '/regional'
    | '/search'
    | '/tables'
    | '/comparisons/$slug'
    | '/pt/$category'
    | '/regional/$slug'
    | '/comparisons/'
    | '/pt/'
    | '/regional/'
    | '/tables/'
    | '/pt/$category/$slug'
    | '/pt/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/comparisons/$slug'
    | '/regional/$slug'
    | '/comparisons'
    | '/pt'
    | '/regional'
    | '/tables'
    | '/pt/$category/$slug'
    | '/pt/$category'
  id:
    | '__root__'
    | '/'
    | '/comparisons'
    | '/pt'
    | '/regional'
    | '/search'
    | '/tables'
    | '/comparisons/$slug'
    | '/pt/$category'
    | '/regional/$slug'
    | '/comparisons/'
    | '/pt/'
    | '/regional/'
    | '/tables/'
    | '/pt/$category/$slug'
    | '/pt/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparisonsRoute: typeof ComparisonsRouteWithChildren
  PtRoute: typeof PtRouteWithChildren
  RegionalRoute: typeof RegionalRouteWithChildren
  SearchRoute: typeof SearchRoute
  TablesRoute: typeof TablesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparisons': {
      id: '/comparisons'
      path: '/comparisons'
      fullPath: '/comparisons'
      preLoaderRoute: typeof ComparisonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt': {
      id: '/pt'
      path: '/pt'
      fullPath: '/pt'
      preLoaderRoute: typeof PtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regional': {
      id: '/regional'
      path: '/regional'
      fullPath: '/regional'
      preLoaderRoute: typeof RegionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparisons/': {
      id: '/comparisons/'
      path: '/'
      fullPath: '/comparisons/'
      preLoaderRoute: typeof ComparisonsIndexRouteImport
      parentRoute: typeof ComparisonsRoute
    }
    '/comparisons/$slug': {
      id: '/comparisons/$slug'
      path: '/$slug'
      fullPath: '/comparisons/$slug'
      preLoaderRoute: typeof ComparisonsSlugRouteImport
      parentRoute: typeof ComparisonsRoute
    }
    '/pt/': {
      id: '/pt/'
      path: '/'
      fullPath: '/pt/'
      preLoaderRoute: typeof PtIndexRouteImport
      parentRoute: typeof PtRoute
    }
    '/pt/$category': {
      id: '/pt/$category'
      path: '/$category'
      fullPath: '/pt/$category'
      preLoaderRoute: typeof PtCategoryRouteImport
      parentRoute: typeof PtRoute
    }
    '/regional/': {
      id: '/regional/'
      path: '/'
      fullPath: '/regional/'
      preLoaderRoute: typeof RegionalIndexRouteImport
      parentRoute: typeof RegionalRoute
    }
    '/regional/$slug': {
      id: '/regional/$slug'
      path: '/$slug'
      fullPath: '/regional/$slug'
      preLoaderRoute: typeof RegionalSlugRouteImport
      parentRoute: typeof RegionalRoute
    }
    '/tables/': {
      id: '/tables/'
      path: '/'
      fullPath: '/tables/'
      preLoaderRoute: typeof TablesIndexRouteImport
      parentRoute: typeof TablesRoute
    }
    '/pt/$category/': {
      id: '/pt/$category/'
      path: '/'
      fullPath: '/pt/$category/'
      preLoaderRoute: typeof PtCategoryIndexRouteImport
      parentRoute: typeof PtCategoryRoute
    }
    '/pt/$category/$slug': {
      id: '/pt/$category/$slug'
      path: '/$slug'
      fullPath: '/pt/$category/$slug'
      preLoaderRoute: typeof PtCategorySlugRouteImport
      parentRoute: typeof PtCategoryRoute
    }
  }
}

interface ComparisonsRouteChildren {
  ComparisonsSlugRoute: typeof ComparisonsSlugRoute
  ComparisonsIndexRoute: typeof ComparisonsIndexRoute
}

const ComparisonsRouteChildren: ComparisonsRouteChildren = {
  ComparisonsSlugRoute: ComparisonsSlugRoute,
  ComparisonsIndexRoute: ComparisonsIndexRoute,
}

const ComparisonsRouteWithChildren = ComparisonsRoute._addFileChildren(
  ComparisonsRouteChildren,
)

interface PtCategoryRouteChildren {
  PtCategorySlugRoute: typeof PtCategorySlugRoute
  PtCategoryIndexRoute: typeof PtCategoryIndexRoute
}

const PtCategoryRouteChildren: PtCategoryRouteChildren = {
  PtCategorySlugRoute: PtCategorySlugRoute,
  PtCategoryIndexRoute: PtCategoryIndexRoute,
}

const PtCategoryRouteWithChildren = PtCategoryRoute._addFileChildren(
  PtCategoryRouteChildren,
)

interface PtRouteChildren {
  PtCategoryRoute: typeof PtCategoryRouteWithChildren
  PtIndexRoute: typeof PtIndexRoute
}

const PtRouteChildren: PtRouteChildren = {
  PtCategoryRoute: PtCategoryRouteWithChildren,
  PtIndexRoute: PtIndexRoute,
}

const PtRouteWithChildren = PtRoute._addFileChildren(PtRouteChildren)

interface RegionalRouteChildren {
  RegionalSlugRoute: typeof RegionalSlugRoute
  RegionalIndexRoute: typeof RegionalIndexRoute
}

const RegionalRouteChildren: RegionalRouteChildren = {
  RegionalSlugRoute: RegionalSlugRoute,
  RegionalIndexRoute: RegionalIndexRoute,
}

const RegionalRouteWithChildren = RegionalRoute._addFileChildren(
  RegionalRouteChildren,
)

interface TablesRouteChildren {
  TablesIndexRoute: typeof TablesIndexRoute
}

const TablesRouteChildren: TablesRouteChildren = {
  TablesIndexRoute: TablesIndexRoute,
}

const TablesRouteWithChildren =
  TablesRoute._addFileChildren(TablesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparisonsRoute: ComparisonsRouteWithChildren,
  PtRoute: PtRouteWithChildren,
  RegionalRoute: RegionalRouteWithChildren,
  SearchRoute: SearchRoute,
  TablesRoute: TablesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
